Repository Caltech-IPAC/firefly, pull requests merged in 2019-11, with the labels that each got.

#905 Firefly-416: useFieldGroupConnector was not unmounting fields properly
  src/firefly/html/test/template.html
  src/firefly/js/ui/FieldGroupConnector.jsx
  src/firefly/js/visualize/MenuItemKeys.js
  src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
  src/firefly/js/visualize/ui/MatchLockDropDown.jsx
  src/firefly/js/visualize/ui/VisToolbarView.jsx
Labels: UI, bug

#906 Adjust error message produced when attempting to load 1D image
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
Labels: Image, bug

#903 Correct Markdown syntax
  README.md
Labels: documentation

#907 FIREFLY-414: Fail to retrieve results from LSST async TAP queries
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServiceInput.java
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
  src/firefly/test/edu/caltech/ipac/firefly/server/network/HttpServicesTest.java
Labels: bug

#909 FIREFLY-434_ResolveServerCommands.ResolveName_is_showing_errors_when_…
  src/firefly/java/edu/caltech/ipac/firefly/server/ServCommand.java
  src/firefly/java/edu/caltech/ipac/firefly/server/rpc/ResolveServerCommands.java
Labels: Infrastructure, bug

#912 IRSA-3272: Header popup panel was not updating as the FITS image changed
  src/firefly/html/firefly-dev.html
  src/firefly/js/visualize/ui/FitsHeaderView.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Labels: Image, bug

#913 FIREFLY-443: put back cube images
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Labels: Image, bug

#884 DM-20248: client side format
  src/firefly/html/demo/table-api.html
  src/firefly/html/test/images/tbl_format1.png
  src/firefly/html/test/images/tbl_links.png
  src/firefly/html/test/images/tbl_propData.png
  src/firefly/html/test/index.html
  src/firefly/html/test/styles.css
  src/firefly/html/test/test-misc.html
  src/firefly/html/test/tests-main.html
  src/firefly/html/test/tests-table.html
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/table/DataType.java
  src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
  src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
  src/firefly/java/edu/caltech/ipac/table/TableMeta.java
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/js/api/ApiHighlevelBuild.js
  src/firefly/js/charts/ChartUtil.js
  src/firefly/js/charts/dataTypes/FireflyGenericData.js
  src/firefly/js/externalSource/__tests__/sprintf-test.js
  src/firefly/js/externalSource/sprintf.js
  src/firefly/js/tables/FilterInfo.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/tables/__tests__/TableUtil-test.js
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/IpacTableTest.java
  src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/TableTest.java
  src/firefly/test/edu/caltech/ipac/table/VotableTest.java
Labels: Table, enhancement

#914 Irsa 3284
  config/app.config
  docs/new-release-procedure.md
  src/firefly/java/edu/caltech/ipac/firefly/resources/irsa-image-master-table.csv
  src/firefly/java/edu/caltech/ipac/firefly/server/ServCommand.java
  src/firefly/java/edu/caltech/ipac/firefly/server/rpc/ResolveServerCommands.java
Labels: Image

#917 Firefly-450: Migrate MOC loading logic from upload panel to TableType Watcher
  src/firefly/html/test/images/loading-4-mocs.png
  src/firefly/html/test/images/moc-overlay-on-hips.png
  src/firefly/html/test/images/two-hips-1-image.png
  src/firefly/html/test/index.html
  src/firefly/html/test/test-hips-mocs.html
  src/firefly/html/test/test-misc.html
  src/firefly/html/test/tests-viewer.html
  src/firefly/js/Firefly.js
  src/firefly/js/api/ApiBuild.js
  src/firefly/js/api/ApiHighlevelBuild.js
  src/firefly/js/api/ApiUtil.js
  src/firefly/js/core/MasterSaga.js
  src/firefly/js/data/MetaConst.js
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/visualize/HiPSMocUtil.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/saga/MOCWatcher.js
  src/firefly/js/visualize/ui/ApiFullImageDisplay.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/python/SamplePythonLauncher.py
  src/firefly/python/display/.gitignore
  src/firefly/python/display/License.txt
  src/firefly/python/display/README.md
  src/firefly/python/display/firefly_client/__init__.py
  src/firefly/python/display/firefly_client/firefly_client.py
  src/firefly/python/display/setup.cfg
  src/firefly/python/display/setup.py
  src/firefly/python/firefly_widgets/examples/firefly_widgets.ipynb
  src/firefly/python/firefly_widgets/examples/test.ipynb
Labels: Infrastructure, UI, enhancement

#919 Firefly-395: Layers dialog improvements
  src/firefly/js/api/ApiBuild.js
  src/firefly/js/core/ReduxFlux.js
  src/firefly/js/drawingLayers/Artifact.js
  src/firefly/js/drawingLayers/Catalog.js
  src/firefly/js/drawingLayers/ImageRoot.js
  src/firefly/js/drawingLayers/ImageRootUI.jsx
  src/firefly/js/drawingLayers/SearchTarget.js
  src/firefly/js/util/Color.js
  src/firefly/js/visualize/Point.js
  src/firefly/js/visualize/RelatedDataUtil.js
  src/firefly/js/visualize/draw/DrawLayer.js
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/ui/DrawLayerItemView.jsx
  src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
  src/firefly/js/visualize/ui/WorldPtFormat.jsx
Labels: UI, enhancement

#918 Firefly-435: fixed a LSST footprint bug that was introduced by table changes churn
  src/firefly/js/visualize/task/LSSTFootprintTask.js
Labels: bug, overlay-drawing
