Repository Caltech-IPAC/firefly, pull requests merged in 2020-06, with the labels that each got.

#976 FIREFLY-177:Add more generic parser/analyzer to support non standard FITS header
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaFitsConverterUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java
Labels: Image, enhancement

#980 Firefly-573: fix two bugs
  src/firefly/js/tables/ui/TableSave.jsx
  src/firefly/js/ui/DropDownContainer.jsx
Labels: bug

#979 Firefly-524: DataProducts viewer update
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysisReport.java
  src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/Demo1Analyzer.java
  src/firefly/js/data/FileAnalysis.js
  src/firefly/js/metaConvert/DataProductsCntlr.js
  src/firefly/js/metaConvert/DataProductsType.js
  src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/visualize/ui/ColorBandPanel.jsx
  src/firefly/js/visualize/ui/ColorDialog.jsx
  src/firefly/js/visualize/ui/MetaDataMultiProductViewer.jsx
  src/firefly/js/visualize/ui/MultiProductViewer.jsx
Labels: Infrastructure, UI

#983 firelfy-347:tickbox on top of catalog search column
  src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
Labels: bug

#981 IRSA-1530:Finder Chart : Orientation keyword in API
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FlipXY.java
Labels: bug

#985 firefly-594:FlipXY's unit test "FlipXTest" is failed
  src/firefly/test/edu/caltech/ipac/firefly/util/FitsGenerator.java
Labels: bug

#987 Firefly-568: Web api updates and other optimizations and code clean up
  src/firefly/html/images/12x12_clipboard-checked.png
  src/firefly/js/Firefly.js
  src/firefly/js/api/WebApi.js
  src/firefly/js/api/webApiCommands/ImageCommands.js
  src/firefly/js/api/webApiCommands/TapCommands.js
  src/firefly/js/data/form/PositionFieldDef.js
  src/firefly/js/metaConvert/DataProductsCntlr.js
  src/firefly/js/ui/PopupPanelHelper.js
  src/firefly/js/ui/WebApiHelpInfoPage.css
  src/firefly/js/ui/WebApiHelpInfoPage.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/util/BrowserUtil.js
  src/firefly/js/util/MathUtil.js
  src/firefly/js/util/PositionParser.js
  src/firefly/js/util/StringUtils.js
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/CsysConverter.js
  src/firefly/js/visualize/HiPSUtil.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/PlotAttribute.js
  src/firefly/js/visualize/PlotState.js
  src/firefly/js/visualize/PlotTransformUtils.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/Point.js
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/ZoomUtil.js
  src/firefly/js/visualize/iv/ImageViewerStatus.jsx
  src/firefly/js/visualize/iv/TileDrawHelper.jsx
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/reducer/HandlePlotCreation.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/task/WcsMatchTask.js
  src/firefly/js/visualize/task/ZoomTask.js
  src/firefly/js/visualize/ui/ColorBandPanel.jsx
  src/firefly/js/visualize/ui/MultiProductViewer.jsx
Labels: API, Infrastructure

#984 FIREFLY-564: label changed in the target panel
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Labels: UI

#974 Firefly-62 Adding examples for tooltip hovertemplate, with numeric …
  src/firefly/html/demo/ffapi-sed.html
Labels: UI

#991 firefly-530:More coordinate hiccups
  src/firefly_data/footprint/Footprint_SOFIA.reg
Labels: enhancement
