Repository Caltech-IPAC/firefly, pull requests merged in 2020-03, with the labels that each got.

#938 FIREFLY-488: enforce new cache policy
  buildScript/tasks.gincl
  buildScript/webpack.config.js
  src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/CatMasterTableQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchProcessor.java
  src/firefly/js/Firefly.js
  src/firefly/js/rpc/SearchServicesJson.js
Labels: Infrastructure

#944 Firefly-501: fixes region saving
  src/firefly/js/visualize/region/RegionDescription.js
Labels: bug

#931 firefly-468-Unit test is needed for Wavelength calculation for different WCS
  src/firefly/js/visualize/Point.js
  src/firefly/js/visualize/projection/__tests__/Projection-test.js
  src/firefly/js/visualize/projection/__tests__/Wavelength-test.js
  src/firefly/test/edu/caltech/ipac/firefly/util/FileLoader.java
  src/firefly/test/edu/caltech/ipac/firefly/util/FitsHeaderToJson.java
  src/firefly/test/edu/caltech/ipac/visualize/plot/ImageHeaderTest.java
  src/firefly/test/edu/caltech/ipac/visualize/plot/projection/ProjectionTest.java
Labels: testing

#942 IRSA-1571:Finder Chart API: color images for SEIP and Akari are not supported for the moment in API mode. ColorImage Download in Finderchart UI is not working either.
  src/firefly/java/edu/caltech/ipac/firefly/data/FinderChartRequestUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/ServiceRetriever.java
  src/firefly/java/edu/caltech/ipac/visualize/net/AtlasImageParams.java
Labels: enhancement

#945 Firefly-499: fixed actions being lost in WebsocketConnector
  src/firefly/html/test/images/remote-API-triview-table.png
  src/firefly/html/test/tests-viewer.html
  src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/events/WebsocketConnector.java
  src/firefly/js/api/ApiViewer.js
  src/firefly/js/core/AppDataCntlr.js
  src/firefly/js/core/JsonUtils.js
  src/firefly/js/drawingLayers/Catalog.js
  src/firefly/js/templates/fireflyslate/FireflySlate.jsx
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/hydra/HydraViewer.jsx
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/reducer/HandlePlotCreation.js
  src/firefly/js/visualize/reducer/OverlayPlotView.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
Labels: Infrastructure, bug

#935 Firefly-482-Firefly can not display mouse readout for some Herschel PACS data
  src/firefly/java/edu/caltech/ipac/visualize/plot/ImageHeader.java
  src/firefly/js/visualize/projection/ProjectionHeaderParser.js
Labels: Image, bug

#947 Firefly-503, firefly-511 - fixed
  src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
  src/firefly/js/drawingLayers/DistanceTool.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/task/PlotChangeTask.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/task/WcsMatchTask.js
Labels: bug, multi-ticket

#948 Firefly-510 - partial bug fix.
  src/firefly/html/firefly-dev.html
  src/firefly/html/ts.html
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/WebPlotRequest.js
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/task/PlotAdminTask.js
  src/firefly/js/visualize/task/WcsMatchTask.js
Labels: bug

#949 Firefly-518: Added better method method of managing overlay position
  src/firefly/html/test/test-coverage.html
  src/firefly/js/data/MetaConst.js
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
Labels: API

#950 firefly-514: revamped how we use starlink fits table reading so that we can close the FITS file.
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
Labels: bug

#946 FIREFLY-461: add VO resources to Firefly table.
  src/firefly/html/test/tests-table.html
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/table/DataGroup.java
  src/firefly/java/edu/caltech/ipac/table/GroupInfo.java
  src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
  src/firefly/java/edu/caltech/ipac/table/ResourceInfo.java
  src/firefly/java/edu/caltech/ipac/table/TableMeta.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/tables/ui/ObjectTree.jsx
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TablePanel.jsx
Labels: API, Table

#953 IRSA-3411-download popup shouldn't have 'cancel'
  src/firefly/js/ui/DownloadDialog.jsx
Labels: enhancement

#955 FIREFLY-523: fix fixed column cell transparency issue
  config/app.config
  docs/new-release-procedure.md
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TableRenderer.js
Labels: Table

#952 Firefly-497: Updates for Data Products Viewer
  src/firefly/js/Firefly.js
  src/firefly/js/metaConvert/DataProductsCntlr.js
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/DataProductsType.js
  src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/metaConvert/converterUtils.js
  src/firefly/js/visualize/saga/DataProductsWatcher.js
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
  src/firefly/js/visualize/ui/MultiProductViewer.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Labels: UI, enhancement

#958 FIREFLY-526 update the fill color for round-up tiles when the color changes
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/visualize/draw/MocObj.js
Labels: UI, bug

#957 Firefly-529: Fixed: Color Picker now update when user changes a value
  src/firefly/js/ui/ColorPicker.jsx
Labels: UI, bug

#959 FIREFLY-502: table filter text comparison is no longer case insensitive
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
Labels: Table
