Repository Caltech-IPAC/firefly, pull requests merged in 2020-12, with the labels that each got.

#1042 Firefly-677: service descriptors support
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysisReport.java
  src/firefly/java/edu/caltech/ipac/firefly/data/FileInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/java/edu/caltech/ipac/firefly/server/rpc/ResolveServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileDownload.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/FileRetriever.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/URLFileRetriever.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/FFEntryPoint.js
  src/firefly/js/api/webApiCommands/LcWebApiCommands.js
  src/firefly/js/charts/dataTypes/FireflyGenericData.js
  src/firefly/js/data/FileAnalysis.js
  src/firefly/js/metaConvert/DataLinkProcessor.js
  src/firefly/js/metaConvert/DataProductsCntlr.js
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/DataProductsType.js
  src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
  src/firefly/js/metaConvert/ObsCoreConverter.js
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/metaConvert/ServDescConverter.js
  src/firefly/js/metaConvert/converterUtils.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/util/WebUtil.js
  src/firefly/js/util/fetch.js
  src/firefly/js/visualize/HiPSUtil.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/PlotState.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/iv/HiPSRenderer.js
  src/firefly/js/visualize/iv/HiPSSingleTileRender.js
  src/firefly/js/visualize/iv/HiPSTileCache.js
  src/firefly/js/visualize/iv/HiPSTileDrawer.js
  src/firefly/js/visualize/iv/HipsColor.js
  src/firefly/js/visualize/iv/ImageProcessor.js
  src/firefly/js/visualize/iv/ImageRender.jsx
  src/firefly/js/visualize/rawData/GpuJsConfig.js
  src/firefly/js/visualize/rawData/RawDataOps.js
  src/firefly/js/visualize/rawData/RawImageTilesGPU.js
  src/firefly/js/visualize/rawData/rawAlgorithm/ColorTable.js
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/task/PlotChangeTask.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/task/WcsMatchTask.js
  src/firefly/js/visualize/task/ZoomTask.js
  src/firefly/js/visualize/ui/ActivateMenu.jsx
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/MagnifiedView.jsx
  src/firefly/js/visualize/ui/MultiProductViewer.jsx
  src/firefly/js/visualize/ui/ThumbnailView.jsx
  src/firefly/js/visualize/ui/VisToolbarView.jsx
Labels: Infrastructure, UI, enhancement

#1045 Migrate BasicUI to a functional component
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
Labels: UI

#1043 Firefly-688: Blank Hips
  src/firefly/html/test/images/blank_coverage.png
  src/firefly/html/test/template.html
  src/firefly/html/test/template_loader.js
  src/firefly/html/test/test-coverage.html
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterList.java
  src/firefly/js/data/MetaConst.js
  src/firefly/js/drawingLayers/ImageRoot.js
  src/firefly/js/drawingLayers/MarkerTool.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/util/Color.js
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/HiPSListUtil.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/iv/HiPSRenderer.js
  src/firefly/js/visualize/iv/HiPSTileDrawer.js
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/saga/MouseReadoutWatch.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/ui/DrawLayerItemView.jsx
  src/firefly/js/visualize/ui/VisToolbarView.jsx
Labels: Image, enhancement
