Repository Caltech-IPAC/firefly, pull requests merged in 2020-08, with the labels that each got.

#1004 irsa-3638:The analyzer for "GREAT" instrument image does not have the image tab
  src/firefly/js/metaConvert/PartAnalyzer.js
Labels: bug

#1006 firefly-617: fixed data products viewer showing the File Content dropdown twice
  src/firefly/js/visualize/ui/ImageMetaDataToolbar.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/MultiProductViewer.jsx
Labels: bug

#1007 IRSA-2624:FIFI-LS Level 3 "wavelength_resampled" cube fails to be cropped (reported by SMO)
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/CropFile.java
  src/firefly/js/visualize/draw/ShapeDataObj.js
Labels: bug

#1008 FIREFLY-629:FIFI-LS: Image button shouldn't be present in HDU table type
  src/firefly/js/metaConvert/PartAnalyzer.js
Labels: bug

#1009 FIREFLY-631: fixing spectra and other instrument data product viewer related issues
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/Sofia1DSpectraExtractor.java
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaFitsConverterUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaSpectraModel.java
  src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java
Labels: bug

#1005 FIREFLY-595: Handle cell with long entries
  buildScript/tasks.gincl
  buildScript/webpack.config.js
  package.json
  src/firefly/js/tables/reducer/TableUiReducer.js
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  yarn.lock
Labels: Table, UI, enhancement

#999 TAP UI: Enhance schema browser with qualified name column
  src/firefly/js/ui/tap/AdvancedADQL.jsx
Labels: UI

#1010 firefly-632:More issues found after fixing FIREFLY-629 and 631
  src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java
  src/firefly/js/metaConvert/PartAnalyzer.js
Labels: bug

#1013 FIREFLY-274: fix the disappearing of DS9 region
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/draw/ShapeDataObj.js
Labels: bug
