Repository Caltech-IPAC/firefly, pull requests merged in 2020-05, with the labels that each got.

#967 Firefly-544: Fixed: now we can add a table to a report
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysisReport.java
  src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/Demo1Analyzer.java
  src/firefly/js/data/FileAnalysis.js
  src/firefly/js/metaConvert/PartAnalyzer.js
Labels: Infrastructure, bug

#965 Firefly-527: Web API Infrastructure
  src/firefly/html/slate.html
  src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/CommandService.java
  src/firefly/js/FFEntryPoint.js
  src/firefly/js/Firefly.js
  src/firefly/js/api/WebApi.js
  src/firefly/js/api/webApiCommands/ImageCommands.js
  src/firefly/js/api/webApiCommands/TableCommands.js
  src/firefly/js/api/webApiCommands/TapCommands.js
  src/firefly/js/api/webApiCommands/ViewerWebApiCommands.js
  src/firefly/js/core/History.js
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/core/ReduxFlux.js
  src/firefly/js/fireflyJSLib.js
  src/firefly/js/rpc/CoreServices.js
  src/firefly/js/templates/fireflyslate/FireflySlate.jsx
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/hydra/HydraViewer.jsx
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/ui/CatalogSearchMethodType.jsx
  src/firefly/js/ui/CompleteButton.jsx
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/FormPanel.jsx
  src/firefly/js/ui/PopupUtil.jsx
  src/firefly/js/ui/SearchPanel.jsx
  src/firefly/js/ui/WebApiHelpInfoPage.css
  src/firefly/js/ui/WebApiHelpInfoPage.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/WebPlotRequest.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Labels: API, enhancement

#968 irsa-2673:IRSAViewer can't get full SDSS images?
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/ServiceRetriever.java
  src/firefly/java/edu/caltech/ipac/visualize/net/SloanDssImageParams.java
Labels: bug

#964 IRSA-2651:overlays keep reappearing
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/visualize/DrawLayerCntlr.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/RelatedDataUtil.js
  src/firefly/js/visualize/reducer/HandlePlotCreation.js
  src/firefly/js/visualize/region/RegionTask.js
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
Labels: bug

#969 Firefly-547: clean up docker
  docker/base/Dockerfile
  docker/base/cleanup.sh
  docker/base/launchTomcat.sh
  docker/base/sendLogsToConsole.sh
  docker/base/setenv.sh
  docker/base/setupFireflyExample.sh
  docker/base/setupSharedCacheJars.sh
  docker/base/start-examples.txt
Labels: Infrastructure

#970 Firefly-552: Fixed: Jupyter lab start is broken.
  src/firefly/js/Firefly.js
  src/firefly/js/api/ApiUtil.js
  src/firefly/js/templates/fireflyslate/FireflySlate.jsx
  src/firefly/js/templates/fireflyslate/FireflySlateManager.js
  src/firefly/js/templates/fireflyslate/GridLayoutPanel.jsx
  src/firefly/js/visualize/MultiViewCntlr.js
  src/firefly/js/visualize/ui/MultiProductViewer.jsx
Labels: bug

#971 irsa-3526-sending to finderchart from gator is broken
  src/firefly/js/util/WebUtil.js
Labels: bug

#972 Firefly-548: improve click by click readout copying
  src/firefly/html/images/12x12_clipboard-checked.png
  src/firefly/html/images/12x12_clipboard.png
  src/firefly/js/drawingLayers/Catalog.js
  src/firefly/js/drawingLayers/SearchTarget.js
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/util/PositionParser.js
  src/firefly/js/visualize/DrawLayerCntlr.js
  src/firefly/js/visualize/draw/DrawLayer.js
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/ui/ApiExpandedDisplay.jsx
  src/firefly/js/visualize/ui/ApiFullImageDisplay.jsx
  src/firefly/js/visualize/ui/DrawLayerPanel.jsx
  src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
  src/firefly/js/visualize/ui/HiPSMouseReadout.jsx
  src/firefly/js/visualize/ui/MagnifiedView.jsx
  src/firefly/js/visualize/ui/MouseReadout.css
  src/firefly/js/visualize/ui/MouseReadout.jsx
  src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
  src/firefly/js/visualize/ui/PopupMouseReadout.jsx
  src/firefly/js/visualize/ui/ThumbnailView.jsx
  src/firefly/js/visualize/ui/VisHeaderView.jsx
Labels: UI, bug

#977 Firefly-561: fix small layout issues
  src/firefly/js/visualize/saga/MouseReadoutWatch.js
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/MouseReadout.css
  src/firefly/js/visualize/ui/MouseReadout.jsx
  src/firefly/js/visualize/ui/VisHeaderView.jsx
Labels: bug

#978 Firefly-562: change some components to be functional and optimize rendering
  src/firefly/html/test/tests-main.html
  src/firefly/js/core/ExternalAccessCntlr.js
  src/firefly/js/core/ExternalAccessUtils.js
  src/firefly/js/core/ReduxFlux.js
  src/firefly/js/core/messaging/ExternalAccessWatcher.js
  src/firefly/js/drawingLayers/Artifact.js
  src/firefly/js/drawingLayers/Catalog.js
  src/firefly/js/drawingLayers/ImageLineBasedFootprint.js
  src/firefly/js/drawingLayers/RegionPlot.js
  src/firefly/js/fieldGroup/FieldGroupCntlr.js
  src/firefly/js/rpc/PlotServicesJson.js
  src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx
  src/firefly/js/ui/DialogRootContainer.jsx
  src/firefly/js/ui/DropDownToolbarButton.jsx
  src/firefly/js/ui/PopupPanel.jsx
  src/firefly/js/ui/PopupPanelHelper.js
  src/firefly/js/ui/PopupStoreConnection.jsx
  src/firefly/js/ui/SimpleComponent.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/visualize/ChangePrime.js
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/WebPlotRequest.js
  src/firefly/js/visualize/draw/Drawer.js
  src/firefly/js/visualize/draw/SimpleCanvas.jsx
  src/firefly/js/visualize/iv/EventLayer.jsx
  src/firefly/js/visualize/iv/HiPSRenderer.js
  src/firefly/js/visualize/iv/ImageExpandedMode.jsx
  src/firefly/js/visualize/iv/ImageViewer.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/iv/ImageViewerStatus.jsx
  src/firefly/js/visualize/iv/PlotTitle.jsx
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/region/RegionFileUploadView.jsx
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/saga/ImagePlotter.js
  src/firefly/js/visualize/task/ImageOverlayTask.js
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/task/WcsMatchTask.js
  src/firefly/js/visualize/task/ZoomTask.js
  src/firefly/js/visualize/ui/ApiExpandedDisplay.jsx
  src/firefly/js/visualize/ui/ApiFullImageDisplay.jsx
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
  src/firefly/js/visualize/ui/CtxToolbarFunctions.js
  src/firefly/js/visualize/ui/DefaultApiReadout.jsx
  src/firefly/js/visualize/ui/DrawLayerPanel.jsx
  src/firefly/js/visualize/ui/ImageCenterDropDown.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/MatchLockDropDown.jsx
  src/firefly/js/visualize/ui/MultiProductViewer.jsx
  src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
  src/firefly/js/visualize/ui/ThumbnailView.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
  src/firefly/js/visualize/ui/VisHeader.jsx
  src/firefly/js/visualize/ui/VisInlineToolbarView.jsx
  src/firefly/js/visualize/ui/VisToolbar.jsx
  src/firefly/js/visualize/ui/VisToolbarView.jsx
Labels: Infrastructure
