Repository Caltech-IPAC/firefly, pull requests merged in 2020-10, with the labels that each got.

#1017 Firefly 656 bitpix 64 support
  src/firefly/java/edu/caltech/ipac/visualize/plot/PixelValue.java
  src/firefly/js/visualize/saga/MouseReadoutWatch.js
  src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
Labels: enhancement

#1025 irsa-3721:original HDU view names
  src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java
  src/firefly/java/edu/caltech/ipac/util/FitsHDUUtil.java
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/metaConvert/converterUtils.js
Labels: bug

#1029 Update branch descriptions in master README file
  README.md
Labels: documentation

#1028 Null Check in VOAnalyzer.applyTokenSub function
  src/firefly/js/util/VOAnalyzer.js
Labels: bug

#1031 Firefly 667 Firefly related changes needed for irsakubernetes deployment
  config/web.xml
  src/firefly/html/test/tests-table.html
  src/firefly/java/edu/caltech/ipac/firefly/server/RequestAgent.java
  src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HealthCheck.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
  src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/tables/ui/TableRenderer.js
Labels: Infrastructure

#1034 FIREFLY-670: Table fail to render cell value as HTML when FmtDisp is used
  docs/new-release-procedure.md
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/tables/ui/TableRenderer.js
Labels: bug

#1037 Irsa-3771: coverage bug
  src/firefly/js/core/ComponentCntlr.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
Labels: bug

#1038 Simplify Firefly dockerfile
  config/app.config
  docker/base/Dockerfile
  docker/base/customize-firefly.txt
  docker/base/launchTomcat.sh
  docker/base/setupFireflyExample.sh
  docker/base/start-examples.txt
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
  src/firefly/java/edu/caltech/ipac/util/FileUtil.java
Labels: Infrastructure, bug, documentation
