Repository Caltech-IPAC/firefly, pull requests merged in 2020-09, with the labels that each got.

#1011 Firefly 618 fix value array string
  src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/ui/PopupPanel.jsx
Labels: bug, enhancement

#1014 firefly-279:Update 3-color image labeled incorrectly
  src/firefly/js/visualize/reducer/PlotTitle.js
Labels: enhancement

#1012 FIREFLY-635: Docker based development environment
  .gitignore
  buildScript/dep-init.gincl
  buildScript/global.gincl
  buildScript/tasks.gincl
  buildScript/webpack.config.js
  docker-compose.yml
  docker-sync.yml
  docker/base/Dockerfile
  docker/base/launchTomcat.sh
  docker/builder/Dockerfile
  docker/builder/README.md
  docs/onlinehelp.md
  src/firefly/package.json
Labels: Infrastructure

#1018 irsa-3696:BOLOCAM labels
  src/firefly/java/edu/caltech/ipac/firefly/resources/irsa-image-master-table.csv
Labels: enhancement

#1019 IRSA-3708:SOFIA HDU menu: "show as or image"
  src/firefly/js/metaConvert/PartAnalyzer.js
Labels: bug

#1021 IRSA-3724:GREAT level 4 file contents menu
  src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java
  src/firefly/js/metaConvert/PartAnalyzer.js
Labels: enhancement

#1020 Firefly-549: Fixed Crop and context toolbar not going away.
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/task/PlotChangeTask.js
  src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx
Labels: UI, bug

#1023 IRSA-2986-3690-3675: Email related issues
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/BackgroundInfoCacher.java
  src/firefly/js/api/ApiViewer.js
  src/firefly/js/charts/ChartsCntlr.js
  src/firefly/js/charts/PlotlyConfig.js
  src/firefly/js/charts/dataTypes/FireflyHistogram.js
  src/firefly/js/charts/ui/PlotlyWrapper.jsx
  src/firefly/js/core/background/BackgroundMonitor.jsx
  src/firefly/js/drawingLayers/Artifact.js
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/fieldGroup/FieldGroupUtils.js
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/templates/lightcurve/LcConverterFactory.js
  src/firefly/js/templates/lightcurve/LcManager.js
  src/firefly/js/templates/lightcurve/LcResult.jsx
  src/firefly/js/ui/DownloadDialog.jsx
  src/firefly/js/ui/SuggestBoxInputField.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/util/Logger.js
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/ZoomUtil.js
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/region/RegionFactory.js
  src/firefly/js/visualize/region/RegionTask.js
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/saga/ImagePlotter.js
  src/firefly/js/visualize/task/ImageOverlayTask.js
  src/firefly/js/visualize/task/LSSTFootprintTask.js
  src/firefly/js/visualize/task/PlotChangeTask.js
  src/firefly/js/visualize/task/ZoomTask.js
  src/firefly/js/visualize/ui/CtxToolbarFunctions.js
  src/firefly/js/visualize/ui/FitsHeaderView.jsx
  src/firefly/js/visualize/ui/VisInlineToolbarView.jsx
Labels: bug

#1022 FIREFLY-661: replace DataLine generic column name with title HDU
  src/firefly/js/metaConvert/PartAnalyzer.js
Labels: UI, enhancement

#1026 Correct typo in 2020.2.0 release tag.
  docs/release-notes.md
Labels: documentation

#1024 irsa-3276:FIFI-LS level 3 file contents menu
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaFitsConverterUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java
  src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
  src/firefly/js/metaConvert/PartAnalyzer.js
Labels: bug
