Repository Caltech-IPAC/firefly, pull requests merged in 2020-04, with the labels that each got.

#954 FIREFLY-522:Clean up wavelength unit test in the java side
  src/firefly/test/edu/caltech/ipac/visualize/plot/FitsReadTest.java
Labels: testing

#961 FIREFLY-521: add RequireWebSocketUptime
  buildScript/loadScript.js
  src/firefly/html/css/global.css
  src/firefly/html/demo/table-api.html
  src/firefly/html/firefly-dev.html
  src/firefly/html/firefly.html
  src/firefly/html/slate.html
  src/firefly/html/ts.html
  src/firefly/js/Firefly.js
  src/firefly/js/api/ApiUtil.js
  src/firefly/js/api/ApiViewer.js
  src/firefly/js/charts/ChartsCntlr.js
  src/firefly/js/charts/ui/PlotlyWrapper.jsx
  src/firefly/js/core/AppDataCntlr.js
  src/firefly/js/core/JsonUtils.js
  src/firefly/js/core/MasterSaga.js
  src/firefly/js/core/ReduxFlux.js
  src/firefly/js/core/messaging/WebSocketClient.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/ui/LostConnection.jsx
  src/firefly/js/util/Logger.js
  src/firefly/js/util/WebUtil.js
Labels: API, Infrastructure

#951 IRSA-2590-SOFIA FIFI-LS: missing information when displaying Level 3 from spectral images
  src/firefly/js/visualize/projection/Wavelength.js
  src/firefly/js/visualize/projection/WavelengthHeaderParser.js
  src/firefly/js/visualize/projection/__tests__/Wavelength-test.js
Labels: bug, enhancement

#963 FIREFLY-533: Change tri-view layout
  src/firefly/js/templates/fireflyviewer/ResultsPanel.jsx
Labels: UI

#960 Firefly-463: Add infrastructure to further process file FileAnalysis results
  src/firefly/html/test/tests-viewer.html
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysisReport.java
  src/firefly/java/edu/caltech/ipac/firefly/data/table/MetaConst.java
  src/firefly/java/edu/caltech/ipac/firefly/server/SrvParam.java
  src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/DataProductAnalyzer.java
  src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/DataProductAnalyzerFactory.java
  src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/DataProductAnalyzerImpl.java
  src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/Demo1Analyzer.java
  src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/events/WebsocketConnector.java
  src/firefly/java/edu/caltech/ipac/firefly/server/rpc/ResolveServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
  src/firefly/java/edu/caltech/ipac/table/io/DsvTableIO.java
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
  src/firefly/java/edu/caltech/ipac/table/io/IpacTableReader.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/java/edu/caltech/ipac/util/FitsHDUUtil.java
  src/firefly/js/Firefly.js
  src/firefly/js/data/FileAnalysis.js
  src/firefly/js/data/MetaConst.js
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/DataProductsType.js
  src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/metaConvert/converterUtils.js
  src/firefly/js/rpc/CoreServices.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/templates/lightcurve/LcPhaseTable.js
  src/firefly/js/ui/FileUpload.jsx
  src/firefly/js/ui/FitsDownloadDialog.jsx
  src/firefly/js/ui/WorkspaceViewer.jsx
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/WebPlotRequest.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/test/edu/caltech/ipac/firefly/core/FileAnalysisTest.java
  src/firefly/test/edu/caltech/ipac/table/VoTableReaderTest.java
Labels: Infrastructure, enhancement

#966 FIREFLY-495-sofia-expanded-table
  package.json
  src/firefly/html/demo/table-api.html
  src/firefly/js/core/background/BgMaskPanel.jsx
  src/firefly/js/metaConvert/converterUtils.js
  src/firefly/js/rpc/SearchServicesJson.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/tables/reducer/TableDataReducer.js
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablesContainer.jsx
  src/firefly/js/ui/PagingBar.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/util/Logger.js
  src/firefly/js/util/WebUtil.js
  yarn.lock
Labels: UI, bug
