Repository Caltech-IPAC/firefly, pull requests merged in 2020-07, with the labels that each got.

#993 FIREFLY-183_scatter_plot_and_histogram_should_not_referesh_when_table…
  src/firefly/js/charts/ChartUtil.js
Labels: Charts

#996 Firefly-584: set default color table to reverse grayscale and give app option and option to change it
  src/firefly/html/firefly-dev.html
  src/firefly/js/Firefly.js
  src/firefly/js/metaConvert/converterUtils.js
  src/firefly/js/visualize/WebPlotRequest.js
Labels: UI, enhancement

#986 firefly-590:IRSA Viewer: return to defaults doesn't change color table back
  src/firefly/js/visualize/task/PlotAdminTask.js
  src/firefly/js/visualize/task/PlotChangeTask.js
Labels: bug

#975 IRSA-3476_add_preview_of_pngs_to_data_tab
  src/firefly/js/data/MetaConst.js
  src/firefly/js/visualize/ui/PngViewer.jsx
Labels: enhancement

#990 Correct markup in release notes
  docs/release-notes.md
Labels: documentation

#998 Firefly-585: fix download
  package.json
  src/firefly/js/charts/ui/PlotlyWrapper.jsx
  src/firefly/js/ui/FitsDownloadDialog.jsx
  src/firefly/js/ui/SimpleComponent.jsx
  src/firefly/js/util/WebUtil.js
  yarn.lock
Labels: bug

#1000 Firefly-505: added support for a loading message
  package.json
  src/firefly/html/test/tests-viewer.html
  src/firefly/js/FFEntryPoint.js
  src/firefly/js/api/ApiViewer.js
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/core/core-typedefs.jsdoc
  src/firefly/js/templates/fireflyslate/FireflySlate.jsx
  src/firefly/js/templates/fireflyslate/FireflySlateManager.js
  src/firefly/js/templates/fireflyslate/GridLayoutPanel.jsx
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/ui/AppInitLoadingMessage.jsx
  src/firefly/js/visualize/MultiViewCntlr.js
  yarn.lock
Labels: API

#997 FIREFLY-612:weird lag in chrome/safari layers popup
  src/firefly/js/visualize/ui/DrawLayerItemView.jsx
Labels: bug

#1003 irsa-2716:SOFIA GREAT: Level 4 .fits files can be visualized
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaFitsConverterUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaSpectraModel.java
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/VOSpectraModel.java
  src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
Labels: enhancement
