Repository Caltech-IPAC/firefly, pull requests merged in 2021-05, with the labels that each got.

#1086 FIREFLY-722: helpid to point to location instead
  src/firefly/js/ui/tap/TableSearchMethods.jsx
Labels: bug

#1089 Fix ADQL query generation
  src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
  src/firefly/js/ui/tap/TableColumnsConstraints.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
Labels: bug

#1080 Irsa 3871 display plane with value and unit in the cube
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/projection/Wavelength.js
  src/firefly/js/visualize/projection/WavelengthHeaderParser.js
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Labels: enhancement

#1093 FIREFLY-723: adding a pre message above Title for SOFIA/Spitzer need
  src/firefly/js/ui/DownloadDialog.jsx
Labels: UI

#1077 IRSA-3498: update help anchors
  src/firefly/js/tables/ui/TableSave.jsx
  src/firefly/js/ui/FitsDownloadDialog.jsx
  src/firefly/js/ui/FitsRotationDialog.jsx
  src/firefly/js/ui/HiPSSurveyListDisplay.jsx
  src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
  src/firefly/js/visualize/ui/ExtraIpacSearches.jsx
  src/firefly/js/visualize/ui/FitsHeaderView.jsx
  src/firefly/js/visualize/ui/HiPSPropertyView.jsx
  src/firefly/js/visualize/ui/ImageStatsPopup.jsx
  src/firefly/js/visualize/ui/VisToolbarView.jsx
Labels: documentation

#1070 Firefly 708 remove selected images from viewer
  src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
Labels: UI
