Repository Caltech-IPAC/firefly, pull requests merged in 2021-12, with the labels that each got.

#1152 Firefly-853: Create dropdown to add MOC layers
  src/firefly/html/test/test-hips-mocs.html
  src/firefly/java/edu/caltech/ipac/firefly/data/HttpResultInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/data/table/MetaConst.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HiPSRetrieve.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterList.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterListEntry.java
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
  src/firefly/java/edu/caltech/ipac/util/download/FailedRequestException.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/FFEntryPoint.js
  src/firefly/js/data/MetaConst.js
  src/firefly/js/data/ServerParams.js
  src/firefly/js/drawingLayers/CatalogUI.jsx
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/ui/FileUploadDropdown.jsx
  src/firefly/js/ui/HiPSImageSelect.jsx
  src/firefly/js/ui/MultiSearchPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/visualize/HiPSListUtil.js
  src/firefly/js/visualize/HiPSMocUtil.js
  src/firefly/js/visualize/draw/MocObj.js
  src/firefly/js/visualize/iv/PlotTitle.css
  src/firefly/js/visualize/iv/PlotTitle.jsx
  src/firefly/js/visualize/saga/MOCWatcher.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.css
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Labels: bug, enhancement, multi-ticket

#1153 Firefly-675: Fixed: incorrect MOC drawing with different coordinate system
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/visualize/HiPSUtil.js
  src/firefly/js/visualize/draw/MocObj.js
Labels: bug

#1151 FIREFLY-872: display job information in background monitor or in mask panel if not backgrounded.
  docker/base/sendLogsToConsole.sh
  src/firefly/html/css/global.css
  src/firefly/java/edu/caltech/ipac/firefly/api/Async.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/SrvParam.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/BaseGator.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/GatorDD.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/GatorQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/NedSearch.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/Query2MassSIA.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryByConeSearchURL.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryVOTABLE.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncSearchProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/js/core/background/BackgroundCntlr.js
  src/firefly/js/core/background/BackgroundMonitor.css
  src/firefly/js/core/background/BackgroundMonitor.jsx
  src/firefly/js/core/background/BackgroundState.js
  src/firefly/js/core/background/BackgroundStatus.js
  src/firefly/js/core/background/BackgroundUtil.js
  src/firefly/js/core/background/BgMaskPanel.jsx
  src/firefly/js/core/background/JobInfo.jsx
  src/firefly/js/rpc/SearchServicesJson.js
  src/firefly/js/tables/TableRequestUtil.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/templates/lightcurve/LcConverterFactory.js
  src/firefly/js/templates/lightcurve/LcPhaseTable.js
  src/firefly/js/templates/lightcurve/LcResult.jsx
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/ui/DownloadDialog.jsx
  src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
  src/firefly/js/visualize/ui/MouseReadout.jsx
Labels: UI, Infrastructure

#1155 IRSA-4355: Fix Firefly common IBE processing for multi-position search
  src/firefly/java/edu/caltech/ipac/astro/ibe/BaseIbeDataSource.java
  src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/AtlasIbeDataSource.java
  src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/PtfIbeDataSource.java
  src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/TwoMassIbeDataSource.java
  src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java
  src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/ZtfIbeDataSource.java
Labels: bug

#1154 FIREFLY-855: Improve the firefly tab bar to handle large number of tabs
  src/firefly/html/css/global.css
  src/firefly/js/tables/FilterInfo.js
  src/firefly/js/tables/TableConnector.js
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/tables/ui/TablesContainer.jsx
  src/firefly/js/ui/DialogRootContainer.jsx
  src/firefly/js/ui/panel/TabPanel.css
  src/firefly/js/ui/panel/TabPanel.jsx
Labels: UI

#1156 Firefly-886: add user agent based on tag to firefly network calls
  buildScript/global.gincl
  buildScript/tasks.gincl
  config/common.prop
  src/firefly/java/edu/caltech/ipac/firefly/data/Version.java
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/BaseHttpServlet.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/VersionUtil.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/ui/DropDownContainer.jsx
Labels: Infrastructure

#1157 FIREFLY-891-895: ZTF tab and table bugs
  src/firefly/js/ui/panel/TabPanel.css
  src/firefly/js/ui/panel/TabPanel.jsx
Labels: bug, multi-ticket

#1158 FIREFLY-888_CORS: Allow CORS access to Content-Disposition response header
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/BaseHttpServlet.java
Labels: bug

#1160 FIREFLY-900-901: ZTF download related fixes
  src/firefly/js/core/background/BackgroundMonitor.css
  src/firefly/js/core/background/BackgroundMonitor.jsx
  src/firefly/js/core/background/BackgroundUtil.js
  src/firefly/js/rpc/SearchServicesJson.js
  src/firefly/js/ui/CheckboxGroupInputField.jsx
  src/firefly/js/ui/DownloadDialog.jsx
Labels: bug, multi-ticket

#1162 firefly-914: clean up of firefly/js/visualize
  src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotRequest.java
  src/firefly/js/api/ApiViewer.js
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/data/ServerRequest.js
  src/firefly/js/drawingLayers/SelectedShape.js
  src/firefly/js/metaConvert/ImageDataProductsUtil.js
  src/firefly/js/metaConvert/converterUtils.js
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/templates/hydra/HydraViewer.jsx
  src/firefly/js/templates/hydra/SampleHydra.jsx
  src/firefly/js/ui/FitsDownloadDialog.jsx
  src/firefly/js/visualize/Band.js
  src/firefly/js/visualize/BandState.js
  src/firefly/js/visualize/ChangePrime.js
  src/firefly/js/visualize/CoordSys.js
  src/firefly/js/visualize/CoordUtil.js
  src/firefly/js/visualize/CsysConverter.js
  src/firefly/js/visualize/FitsHeaderUtil.js
  src/firefly/js/visualize/HiPSListUtil.js
  src/firefly/js/visualize/HiPSMocUtil.js
  src/firefly/js/visualize/HiPSUtil.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/MultiViewCntlr.js
  src/firefly/js/visualize/PlotGroup.js
  src/firefly/js/visualize/PlotState.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/Point.js
  src/firefly/js/visualize/RangeValues.js
  src/firefly/js/visualize/RelatedDataUtil.js
  src/firefly/js/visualize/RequestType.js
  src/firefly/js/visualize/VisMouseSync.js
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/WebPlotRequest.js
  src/firefly/js/visualize/WorkspaceCntlr.js
  src/firefly/js/visualize/ZoomType.js
  src/firefly/js/visualize/ZoomUtil.js
  src/firefly/js/visualize/draw/DrawOp.js
  src/firefly/js/visualize/iv/ImageExpandedMode.jsx
  src/firefly/js/visualize/rawData/RawFloatData.js
  src/firefly/js/visualize/reducer/HandlePlotAdmin.js
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/task/ImageOverlayTask.js
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/task/ZoomTask.js
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
Labels: documentation
