Repository Caltech-IPAC/firefly, pull requests merged in 2021-02, with the labels that each got.

#1054 Firefly 693 ts phase precision too low
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/templates/lightcurve/LcPeriodPlotly.jsx
  src/firefly/js/templates/lightcurve/LcPhaseTable.js
Labels: bug

#1056 FIREFLY-707: coordinate transformation defined by PCi_j is not applied
  src/firefly/js/visualize/projection/ProjectionHeaderParser.js
Labels: bug

#1057 Firefly-695, Firefly-696: fixed two grid issue
  src/firefly/js/drawingLayers/WebGrid.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/ui/ApiExpandedDisplay.jsx
Labels: bug

#1055 Firefly-706: TAP Panel UI cleanup
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/Firefly.js
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/InputAreaFieldView.jsx
  src/firefly/js/ui/RadioGroupInputFieldView.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/Select.jsx
  src/firefly/js/ui/tap/TableColumnsConstraints.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.css
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
Labels: UI, enhancement

#1058 Firefly-567: added ecliptic j2000 readout
  src/firefly/js/drawingLayers/WebGridUI.jsx
  src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx
  src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
Labels: enhancement

#1059 Fixed Multiple tickets and Upload Panel improvements
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysisReport.java
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
  src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/WebPlotResultSerializer.java
  src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotResult.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/java/edu/caltech/ipac/visualize/draw/ColorDisplay.java
  src/firefly/java/edu/caltech/ipac/visualize/draw/HistogramDisplay.java
  src/firefly/js/Firefly.js
  src/firefly/js/data/FileAnalysis.js
  src/firefly/js/data/ServerParams.js
  src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
  src/firefly/js/rpc/PlotServicesJson.js
  src/firefly/js/ui/CompleteButton.jsx
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/MultiSearchPanel.jsx
  src/firefly/js/ui/PopupUtil.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/TableColumnsConstraints.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/WebPlotResult.js
  src/firefly/js/visualize/iv/PlotTitle.css
  src/firefly/js/visualize/iv/PlotTitle.jsx
  src/firefly/js/visualize/rawData/ManageRawDataThread.js
  src/firefly/js/visualize/rawData/RawFloatData.js
  src/firefly/js/visualize/rawData/rawAlgorithm/ColorTable.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/ui/ColorBandPanel.jsx
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.css
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/VisToolbar.jsx
Labels: bug, enhancement, multi-ticket

#1060 Firefly-685: set the starting the cube plane
  package.json
  src/firefly/html/test/index.html
  src/firefly/html/test/test-image.html
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
  src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
  src/firefly/js/data/ServerParams.js
  src/firefly/js/fieldGroup/FieldGroupUtils.js
  src/firefly/js/metaConvert/ImageDataProductsUtil.js
  src/firefly/js/rpc/PlotServicesJson.js
  src/firefly/js/ui/CheckboxGroupInputField.jsx
  src/firefly/js/ui/ExampleDialog.jsx
  src/firefly/js/ui/FileUploadDropdown.jsx
  src/firefly/js/ui/HiPSImageSelect.jsx
  src/firefly/js/ui/SimpleComponent.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/visualize/PlotAttribute.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/draw/DrawerComponent.jsx
  src/firefly/js/visualize/reducer/HandlePlotCreation.js
  src/firefly/js/visualize/region/RegionFileUploadView.jsx
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/ImageStatsPopup.jsx
  yarn.lock
Labels: Infrastructure, enhancement

#1051 FIREFLY-686: Phase 1, first draft
  src/firefly/html/demo/ffapi-tap-test.html
  src/firefly/html/test/images/spectrumDM.jpg
  src/firefly/html/test/index.html
  src/firefly/html/test/tests-chart.html
  src/firefly/html/test/tests-main.html
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/ExtractSpectraSample.java
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/Sofia1DSpectraExtractor.java
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaFitsConverterUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaSpectraModel.java
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/VOSpectraModel.java
  src/firefly/java/edu/caltech/ipac/table/GroupInfo.java
  src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
  src/firefly/java/edu/caltech/ipac/table/TableMeta.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/java/edu/caltech/ipac/table/io/DataGroupStarTable.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableWriter.java
  src/firefly/js/api/ApiHighlevelBuild.js
  src/firefly/js/charts/ChartUtil.js
  src/firefly/js/charts/ChartsCntlr.js
  src/firefly/js/charts/dataTypes/FireflySpectrum.js
  src/firefly/js/charts/ui/ChartSelectPanel.jsx
  src/firefly/js/charts/ui/options/Errors.jsx
  src/firefly/js/charts/ui/options/SpectrumOptions.jsx
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/util/VOAnalyzer.js
Labels: API, Charts, enhancement
