Repository Caltech-IPAC/firefly, pull requests merged in 2021-08, with the labels that each got.

#1118 Default Spatial Target with proper Errors validation
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
Labels: bug

#1119 DM-30780: Fix ivoa.ObsCore detection
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
Labels: enhancement

#1121 FIREFLY-732: Firefly support for long 64 bits integer
  package.json
  src/firefly/html/test/images/tbl_format1.png
  src/firefly/html/test/tests-table.html
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
  src/firefly/js/Firefly.js
  src/firefly/js/charts/ChartUtil.js
  src/firefly/js/charts/dataTypes/FireflyGenericData.js
  src/firefly/js/charts/dataTypes/FireflyHeatmap.js
  src/firefly/js/charts/dataTypes/FireflyHistogram.js
  src/firefly/js/core/JsonUtils.js
  src/firefly/js/externalSource/__tests__/sprintf-test.js
  src/firefly/js/externalSource/sprintf.js
  yarn.lock
Labels: Infrastructure
