Repository Caltech-IPAC/firefly, pull requests merged in 2021-01, with the labels that each got.

#1047 IRSA-3846: fixes: "no coverage available bug"
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
Labels: bug

#1048 IRSA-3851: ${filename} appears in table title
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UserCatalogQuery.java
  src/firefly/js/tables/TableRequestUtil.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/tables/reducer/TableResultsReducer.js
  src/firefly/js/tables/ui/TableSave.jsx
  src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
  src/firefly/test/edu/caltech/ipac/firefly/core/FileAnalysisTest.java
Labels: bug, multi-ticket

#1049 Fix props argument. Fix dangling 's'
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
Labels: bug

#1050 ADQL editor fixes when service url changes
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
Labels: bug

#1052 Firefly-689: Multi search panel - TAP now available
  src/firefly/html/firefly-dev.html
  src/firefly/html/images/popout-arrow_12x12.png
  src/firefly/js/Firefly.js
  src/firefly/js/api/webApiCommands/TapCommands.js
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/tables/ui/TablesContainer.jsx
  src/firefly/js/templates/fireflyslate/FireflySlate.jsx
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/ui/Banner.jsx
  src/firefly/js/ui/CompleteButton.jsx
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/FileUploadDropdown.jsx
  src/firefly/js/ui/MultiSearchPanel.jsx
  src/firefly/js/ui/NedSearchPanel.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/UserInfo.jsx
  src/firefly/js/ui/VoSearchPanel.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/ui/tap/Select.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/rawData/RawImageTilesGPU.js
  src/firefly/js/visualize/task/PlotChangeTask.js
  src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
  src/firefly/js/visualize/ui/CatalogSelectViewPanel.css
  src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
  src/firefly/js/visualize/ui/CatalogTableListField.css
  src/firefly/js/visualize/ui/CatalogTableListField.jsx
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/ExtraIpacSearches.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.css
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
Labels: Infrastructure
