Repository Caltech-IPAC/firefly, pull requests merged in 2021-04, with the labels that each got.

#1071 IRSA-3625: HERON dataset added, need IBE to be fixed though
  src/firefly/java/edu/caltech/ipac/firefly/resources/irsa-image-master-table.csv
Labels: UI

#1069 Firefly: multiple tickets: Firefly-678, Firefly-380, Firefly-727, Firefly-731
  src/firefly/js/Firefly.js
  src/firefly/js/api/ApiUtilImage.jsx
  src/firefly/js/core/ExternalAccessCntlr.js
  src/firefly/js/data/form/PositionFieldDef.js
  src/firefly/js/drawingLayers/Catalog.js
  src/firefly/js/drawingLayers/SearchTarget.js
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/ui/ToolbarButton.css
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/ZoomOptionsPopup.jsx
  src/firefly/js/util/fetch.js
  src/firefly/js/visualize/CoordSys.js
  src/firefly/js/visualize/CoordUtil.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/Point.js
  src/firefly/js/visualize/ZoomUtil.js
  src/firefly/js/visualize/iv/EventLayer.jsx
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/task/PlotChangeTask.js
  src/firefly/js/visualize/task/ZoomTask.js
  src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
  src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Labels: Image, UI, bug, enhancement, multi-ticket

#1074 Firefly-738: Add parsing wise and 2mass type id entries
  src/firefly/js/data/form/PositionFieldDef.js
  src/firefly/js/drawingLayers/ActiveTarget.js
  src/firefly/js/ui/NaifidPanelWorker.js
  src/firefly/js/ui/PositionFieldDef.js
  src/firefly/js/ui/SearchSummary.jsx
  src/firefly/js/ui/TargetFeedback.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/TargetPanelWorker.js
  src/firefly/js/util/MathUtil.js
  src/firefly/js/util/PositionParser.js
  src/firefly/js/visualize/CoordUtil.js
  src/firefly/js/visualize/Point.js
  src/firefly/js/visualize/ui/WorldPtFormat.jsx
  yarn.lock
Labels: UI, enhancement

#1075 Firefly-742: fixes issue calling NED with a '+'
  src/firefly/java/edu/caltech/ipac/astro/net/NedNameResolver.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
Labels: bug

#1079 FIREFLY-691: Create the capability to view spectra and SEDs (Phase 1)
  src/firefly/html/demo/plotly-concepts.html
  src/firefly/html/plotly-1.49.4.min.js
  src/firefly/html/plotly-1.58.4.min.js
  src/firefly/html/test/tests-chart.html
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/DecimationProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/HistogramProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/StatisticsProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SubQueryProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/TableFunctionProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
  src/firefly/js/charts/ChartUtil.js
  src/firefly/js/charts/ChartsCntlr.js
  src/firefly/js/charts/PlotlyConfig.js
  src/firefly/js/charts/dataTypes/FireflyGenericData.js
  src/firefly/js/charts/dataTypes/FireflyHeatmap.js
  src/firefly/js/charts/dataTypes/FireflySpectrum.js
  src/firefly/js/charts/ui/ChartPanel.jsx
  src/firefly/js/charts/ui/ChartSelectPanel.jsx
  src/firefly/js/charts/ui/ColumnOrExpression.jsx
  src/firefly/js/charts/ui/HistogramOptions.jsx
  src/firefly/js/charts/ui/PlotlyChartArea.jsx
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
  src/firefly/js/charts/ui/options/BasicOptions.jsx
  src/firefly/js/charts/ui/options/Errors.jsx
  src/firefly/js/charts/ui/options/FireflyHistogramOptions.jsx
  src/firefly/js/charts/ui/options/HeatmapOptions.jsx
  src/firefly/js/charts/ui/options/NewTracePanel.jsx
  src/firefly/js/charts/ui/options/PlotlyHistogramOptions.jsx
  src/firefly/js/charts/ui/options/ScatterOptions.jsx
  src/firefly/js/charts/ui/options/SpectrumOptions.jsx
  src/firefly/js/tables/TableRequestUtil.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/ui/ChartSelectDropdown.jsx
  src/firefly/js/ui/FieldGroup.jsx
  src/firefly/js/ui/InputFieldView.css
  src/firefly/js/ui/InputFieldView.jsx
  src/firefly/js/util/VOAnalyzer.js
Labels: API, Charts, UI, enhancement, multi-ticket

#1076 Firefly-737: add parameter to set sleep time for cleanup
  docker/base/Dockerfile
  docker/base/cleanup.sh
  docker/base/launchTomcat.sh
  src/firefly/js/Firefly.js
Labels: Infrastructure

#1073 Add ObsCore support
  src/firefly/html/firefly-dev.html
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/ui/CatalogSearchMethodType.jsx
  src/firefly/js/ui/CheckboxGroupInputField.jsx
  src/firefly/js/ui/ListBoxInputField.jsx
  src/firefly/js/ui/SuggestBoxInputField.jsx
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/util/Validate.js
Labels: UI, enhancement

#1081 FIREFLY-643: Resizing a column to zero makes it disappear forever
  src/firefly/js/tables/TableConnector.js
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/FilterEditor.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
  src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
Labels: Table, bug

#1082 IRSA-4042,FIREFLY-761,FIREFLY-765: Chart multi-trace related change requests
  docs/new-release-procedure.md
  src/firefly/js/charts/ui/ChartPanel.css
  src/firefly/js/charts/ui/PlotlyWrapper.jsx
  src/firefly/js/charts/ui/options/BasicOptions.jsx
  src/firefly/js/charts/ui/options/ScatterOptions.jsx
  src/firefly/js/charts/ui/options/SpectrumOptions.jsx
  src/firefly/js/ui/ColorPicker.jsx
Labels: Charts

#1083 implement firefly-762, firefly-764, irsa-4046
  src/firefly/js/charts/ui/options/BasicOptions.jsx
  src/firefly/js/ui/ColorPicker.jsx
  src/firefly/js/ui/FileUploadDropdown.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Labels: Charts, UI, bug

#1085 Fixes to MarkDown formatting in several help files
  docs/fftools-api-code-examples.md
  docs/fftools-api-overview.md
  docs/firefly-python-wrapper.md
  docs/fits-plotting-parameters.md
Labels: documentation
