Repository Caltech-IPAC/firefly, pull requests merged in 2021-07, with the labels that each got.

#1104 FIREFLY-805: Filter does not work on boolean type column
  src/firefly/js/tables/FilterInfo.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/__tests__/TableUtil-test.js
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/ui/FieldGroupConnector.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/util/__tests__/Expression-test.js
Labels: Table

#1108 FIREFLY-805: Filter does not work on boolean type column
  src/firefly/js/tables/FilterInfo.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/__tests__/TableUtil-test.js
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/util/__tests__/Expression-test.js
Labels: Table

#1106 Firefly-810: Fixed mask not loading correctly when zooming
  docs/release-notes.md
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/DirectStretchUtils.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterList.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/ImageData.java
  src/firefly/js/data/ServerParams.js
  src/firefly/js/util/Color.js
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/RelatedDataUtil.js
  src/firefly/js/visualize/rawData/ManageRawDataThread.js
  src/firefly/js/visualize/rawData/RawDataCommon.js
  src/firefly/js/visualize/rawData/RawDataOps.js
  src/firefly/js/visualize/rawData/RawDataThreadActionCreators.js
  src/firefly/js/visualize/rawData/RawFloatData.js
  src/firefly/js/visualize/rawData/RawImageTilesGPU.js
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/task/ImageOverlayTask.js
  src/firefly/js/visualize/task/PlotChangeTask.js
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
Labels: bug, multi-ticket

#1107 FIREFLY-800:Make image search sections scroll all together
  src/firefly/js/ui/ImageSelect.css
  src/firefly/js/ui/ImageSelect.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Labels: UI

#1109 Firefly-823: Implement the file saving standard
  src/firefly/js/charts/ui/PlotlySaveDialog.jsx
  src/firefly/js/charts/ui/PlotlyWrapper.jsx
  src/firefly/js/drawingLayers/ComputeWebGridData.js
  src/firefly/js/tables/ui/TableSave.jsx
  src/firefly/js/ui/FitsDownloadDialog.jsx
  src/firefly/js/util/WebUtil.js
  src/firefly/js/util/fetch.js
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/task/PlotHipsTask.js
Labels: UI, enhancement

#1110 FIREFLY-822: table link going to the wrong url
  src/firefly/html/demo/ffapi-coverage-test.html
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterList.java
  src/firefly/js/ui/HiPSImageSelect.jsx
  src/firefly/js/ui/HiPSSurveyListDisplay.jsx
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/visualize/HiPSListUtil.js
  src/firefly/js/visualize/ui/ImageSearchPanelV2.css
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Labels: Table, bug

#1112 Firefly-827: add example for TargetPanel and Tap Panel to appOptions
  src/firefly/html/firefly-dev.html
  src/firefly/js/Firefly.js
  src/firefly/js/ui/TargetFeedback.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
Labels: enhancement

#1113 Firefly-828: download feedback not working
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/ServiceRetriever.java
  src/firefly/java/edu/caltech/ipac/util/FileUtil.java
  src/firefly/java/edu/caltech/ipac/util/download/BaseNetParams.java
  src/firefly/java/edu/caltech/ipac/util/download/Downloader.java
  src/firefly/java/edu/caltech/ipac/visualize/net/AtlasImageParams.java
  src/firefly/java/edu/caltech/ipac/visualize/net/DssImageGetter.java
  src/firefly/java/edu/caltech/ipac/visualize/net/DssImageParams.java
  src/firefly/java/edu/caltech/ipac/visualize/net/IbeImageGetter.java
  src/firefly/java/edu/caltech/ipac/visualize/net/ImageServiceParams.java
  src/firefly/java/edu/caltech/ipac/visualize/net/PtfImageParams.java
  src/firefly/java/edu/caltech/ipac/visualize/net/SloanDssImageGetter.java
  src/firefly/java/edu/caltech/ipac/visualize/net/SloanDssImageParams.java
  src/firefly/java/edu/caltech/ipac/visualize/net/TwoMassImageParams.java
  src/firefly/java/edu/caltech/ipac/visualize/net/WiseImageParams.java
  src/firefly/java/edu/caltech/ipac/visualize/net/ZtfImageParams.java
  src/firefly/js/ui/FileUpload.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Labels: bug

#1115 FIREFLY-829: Input fields inside a table is not being re-rendered correctly
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/ui/HiPSImageSelect.jsx
  src/firefly/js/ui/ImageSelect.css
  src/firefly/js/ui/tap/TableColumnsConstraints.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.css
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Labels: Table, UI, bug

#1116 Firefly-825: fixed clear not working with current file
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Labels: bug
