Repository Caltech-IPAC/firefly, pull requests merged in 2021-11, with the labels that each got.

#1148 FIREFLY-876: add multi-position search into the common ibe search processor
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryIBE.java
Labels: enhancement

#1145 Firefly-866: small tweeks and many bug fixes
  package.json
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/data/table/MetaConst.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ExtractFromImage.java
  src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
  src/firefly/java/edu/caltech/ipac/table/io/IpacTableReader.java
  src/firefly/java/edu/caltech/ipac/table/io/SpectrumMetaInspector.java
  src/firefly/js/data/MetaConst.js
  src/firefly/js/data/ServerParams.js
  src/firefly/js/drawingLayers/ExtractLineTool.js
  src/firefly/js/drawingLayers/ExtractPointsTool.js
  src/firefly/js/drawingLayers/SearchTarget.js
  src/firefly/js/metaConvert/DataProductsCntlr.js
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/ImageDataProductsUtil.js
  src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/metaConvert/converterUtils.js
  src/firefly/js/rpc/PlotServicesJson.js
  src/firefly/js/templates/fireflyslate/GridLayoutPanel.jsx
  src/firefly/js/ui/CheckboxGroupInputField.jsx
  src/firefly/js/ui/ModalDialog.css
  src/firefly/js/ui/PopupPanel.jsx
  src/firefly/js/ui/PopupUtil.jsx
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
  src/firefly/js/visualize/ui/ExtractionWatchers.js
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/MetaDataMultiProductViewer.jsx
  src/firefly/js/visualize/ui/MultProductViewerContainer.jsx
  src/firefly/js/visualize/ui/MultiProductViewer.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
  yarn.lock
Labels: bug, enhancement, multi-ticket

#1150 Firefly-858: Sticky flipping and north up
  src/firefly/js/drawingLayers/NorthUpCompass.js
  src/firefly/js/metaConvert/ImageDataProductsUtil.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/PlotGroup.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/iv/ImageTileDrawer.js
  src/firefly/js/visualize/iv/PlotTitle.css
  src/firefly/js/visualize/iv/PlotTitle.jsx
  src/firefly/js/visualize/reducer/HandlePlotAdmin.js
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/reducer/HandlePlotCreation.js
  src/firefly/js/visualize/reducer/PlotView.js
Labels: bug

#1149 Firefly-841: UI improvements
  src/firefly/js/drawingLayers/ExtractLineTool.js
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
  src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx
  src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
Labels: enhancement
