Repository Caltech-IPAC/firefly, pull requests merged in 2021-06, with the labels that each got.

#1096 IRSA-4111: Finderchart access from NED stopped working
  src/firefly/java/edu/caltech/ipac/firefly/server/RequestAgent.java
Labels: API

#1098 Firefly-793: fix mouse wheel / trackpad zoom performance problem
  src/firefly/js/drawingLayers/CatalogUI.jsx
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/PlotTransformUtils.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/draw/CanvasWrapper.jsx
  src/firefly/js/visualize/iv/EventLayer.jsx
  src/firefly/js/visualize/iv/ImageViewer.jsx
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/task/ZoomTask.js
Labels: bug

#1092 DM-30073: Handle redirects when retrieving TAP errors
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
Labels: Infrastructure, bug

#1103 Firefly-803: fixes mouse wheel/trackpad zoom and Simbad name lookup bug
  src/firefly/java/edu/caltech/ipac/astro/net/SimbadNameResolver.java
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/task/ZoomTask.js
Labels: bug

#1101 Improve nested error handling in retrieval of TAP error documents
  docs/release-notes.md
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
Labels: bug
