Repository Caltech-IPAC/firefly, pull requests merged in 2022-04, with the labels that each got.

#1204 FIREFLY-976: TablePanel failed to pickup new changes when tbl_ui_id changes
  src/firefly/js/charts/ui/ChartSelectPanel.jsx
  src/firefly/js/charts/ui/options/BasicOptions.jsx
  src/firefly/js/charts/ui/options/Errors.jsx
  src/firefly/js/charts/ui/options/FireflyHistogramOptions.jsx
  src/firefly/js/charts/ui/options/HeatmapOptions.jsx
  src/firefly/js/charts/ui/options/PlotlyHistogramOptions.jsx
  src/firefly/js/charts/ui/options/ScatterOptions.jsx
  src/firefly/js/charts/ui/options/SpectrumOptions.jsx
  src/firefly/js/core/background/BackgroundMonitor.jsx
  src/firefly/js/core/background/BgMaskPanel.jsx
  src/firefly/js/core/background/BgMonitorButton.jsx
  src/firefly/js/core/background/JobInfo.jsx
  src/firefly/js/tables/ui/FilterEditor.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/tables/ui/TablesContainer.jsx
  src/firefly/js/templates/fireflyslate/FireflySlate.jsx
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/ui/Banner.jsx
  src/firefly/js/ui/DownloadDialog.jsx
  src/firefly/js/ui/FitsRotationDialog.jsx
  src/firefly/js/ui/HiPSImageSelect.jsx
  src/firefly/js/ui/ImageSelect.jsx
  src/firefly/js/ui/PagingBar.jsx
  src/firefly/js/ui/SimpleComponent.jsx
  src/firefly/js/ui/WorkspaceSelectPane.jsx
  src/firefly/js/ui/ZoomOptionsPopup.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/visualize/draw/DrawerComponent.jsx
  src/firefly/js/visualize/iv/ImageExpandedMode.jsx
  src/firefly/js/visualize/iv/ImageViewer.jsx
  src/firefly/js/visualize/ui/ColorDialog.jsx
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
  src/firefly/js/visualize/ui/DrawLayerPanel.jsx
  src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/MultiProductViewer.jsx
  src/firefly/js/visualize/ui/PngViewer.jsx
  src/firefly/js/visualize/ui/StretchDropDownView.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
Labels: bug

#1206 Firefly 978 big table performance
  config/app.config
  config/common.prop
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/HsqlDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/Logger.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/StopWatch.java
  src/firefly/java/edu/caltech/ipac/firefly/tools/FitsHeaderTool.java
  src/firefly/java/edu/caltech/ipac/table/DataGroup.java
  src/firefly/java/edu/caltech/ipac/table/DataObject.java
  src/firefly/java/edu/caltech/ipac/table/IpacTableDef.java
  src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
  src/firefly/java/edu/caltech/ipac/table/PrimitiveList.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/java/edu/caltech/ipac/table/io/DsvTableIO.java
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
  src/firefly/java/edu/caltech/ipac/table/io/IpacTableReader.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/java/edu/caltech/ipac/util/cache/CacheManager.java
  src/firefly/test/edu/caltech/ipac/firefly/ConfigTest.java
  src/firefly/test/edu/caltech/ipac/firefly/TestUtil.java
  src/firefly/test/edu/caltech/ipac/firefly/core/FileAnalysisTest.java
  src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/DataGroupReadTest.java
  src/firefly/test/edu/caltech/ipac/table/VoTableReaderTest.java
Labels: enhancement, Table

#1207 Firefly-968: Support HiPS Aitoff projection
  src/firefly/html/test/images/triview-loaded-image.png
  src/firefly/html/test/test-hips-mocs.html
  src/firefly/html/test/tests-viewer.html
  src/firefly/js/drawingLayers/ComputeWebGridData.js
  src/firefly/js/drawingLayers/HiPSGrid.js
  src/firefly/js/drawingLayers/WebGrid.js
  src/firefly/js/externalSource/aladinProj/AladinProjections.js
  src/firefly/js/externalSource/aladinProj/HealpixIndex.js
  src/firefly/js/ui/HiPSImageSelect.jsx
  src/firefly/js/visualize/CsysConverter.js
  src/firefly/js/visualize/HiPSUtil.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/VisMouseSync.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/WebPlotRequest.js
  src/firefly/js/visualize/ZoomUtil.js
  src/firefly/js/visualize/draw/Drawer.js
  src/firefly/js/visualize/draw/DrawingDef.js
  src/firefly/js/visualize/draw/MocObj.js
  src/firefly/js/visualize/draw/PointDataObj.js
  src/firefly/js/visualize/draw/ShapeDataObj.js
  src/firefly/js/visualize/iv/HiPSCellFinder.js
  src/firefly/js/visualize/iv/HiPSRenderer.js
  src/firefly/js/visualize/iv/HiPSSingleTileRender.js
  src/firefly/js/visualize/iv/HiPSTileCache.js
  src/firefly/js/visualize/iv/HiPSTileDrawer.js
  src/firefly/js/visualize/iv/TileDrawHelper.jsx
  src/firefly/js/visualize/projection/Projection.js
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/saga/MouseReadoutWatch.js
  src/firefly/js/visualize/task/ActivePlottingTask.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Labels: enhancement, HiPS

#1208 IRSA-4562: finderchart API broken
  docker/launchTomcat.sh
Labels: Infrastructure

#1212 FIREFLY-756: A string filter bug
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/js/ui/SimpleComponent.jsx
Labels: bug

#1213 FIREFLY-971: showFilters defaults to true for all tables except client tables
  docs/firefly-api-overview.md
  src/firefly/html/demo/table-api.html
  src/firefly/js/api/ApiHighlevelBuild.js
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
Labels: enhancement

#1215 Firefly-985: make sure Wavelength TAB tables are read correctly
  src/firefly/java/edu/caltech/ipac/firefly/data/RelatedData.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/Logger.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/CtxControl.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/DirectStretchUtils.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/SpectralCubeEval.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/iv/EventLayer.jsx
  src/firefly/js/visualize/projection/Wavelength.js
  src/firefly/js/visualize/projection/WavelengthHeaderParser.js
  src/firefly/js/visualize/task/ImageOverlayTask.js
  src/firefly/js/visualize/task/PlotImageTask.js
Labels: bug, Image
