Repository Caltech-IPAC/firefly, pull requests merged in 2022-12, with the labels that each got.

#1292 Firefly-1120: Convert NaifidPanel to functional component and cleanup
  src/firefly/js/ui/NaifidPanel.jsx
Labels: enhancement

#1286 firefly-1115: cleanup tap panel
  src/firefly/js/fieldGroup/FieldGroupCntlr.js
  src/firefly/js/fieldGroup/FieldGroupUtils.js
  src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
  src/firefly/js/ui/DateTimePickerField.jsx
  src/firefly/js/ui/FieldGroup.jsx
  src/firefly/js/ui/FieldGroupConnector.jsx
  src/firefly/js/ui/SimpleComponent.jsx
  src/firefly/js/ui/TimePanel.jsx
  src/firefly/js/ui/TimeUIUtil.js
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/Constraints.js
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableColumnsConstraints.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/ui/tap/TemportalSearch.jsx
  src/firefly/js/ui/tap/TimeRangePanel.jsx
  src/firefly/js/ui/tap/WavelengthPanel.jsx
  src/firefly/js/visualize/Point.js
Labels: UI

#1294 Firefly-1124 hips tabs
  src/firefly/js/ui/FileUploadProcessor.jsx
  src/firefly/js/ui/HiPSImageSelect.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Labels: UI

#1295 FIREFLY-1116: Echo version information to console log and /admin/status panel
  src/firefly/java/edu/caltech/ipac/firefly/data/Version.java
  src/firefly/java/edu/caltech/ipac/firefly/server/Counters.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/VersionUtil.java
Labels: Infrastructure, build

#1302 Firefly-1109: Updates to Click to Action
  src/firefly/js/FFEntryPoint.js
  src/firefly/js/Firefly.js
  src/firefly/js/core/ClickToAction.js
  src/firefly/js/drawingLayers/ImageOutline.js
  src/firefly/js/drawingLayers/SearchSelectTool.js
  src/firefly/js/ui/ActionsDropDownButton.jsx
  src/firefly/js/ui/CatalogSearchMethodType.jsx
  src/firefly/js/ui/DefaultSearchActions.js
  src/firefly/js/ui/ToolbarButton.css
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/visualize/SearchRefinementTool.jsx
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: bug, enhancement, UI

#1298 Firefly-993: Create a Datalink driven search form
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/js/FFEntryPoint.js
  src/firefly/js/Firefly.js
  src/firefly/js/api/webApiCommands/DatalinkUICommands.js
  src/firefly/js/api/webApiCommands/ViewerWebApiCommands.js
  src/firefly/js/data/FileAnalysis.js
  src/firefly/js/data/MetaConst.js
  src/firefly/js/data/ServerParams.js
  src/firefly/js/rpc/CoreServices.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/FileUploadProcessor.jsx
  src/firefly/js/ui/TestQueriesPanel.jsx
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicDef.js
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/iv/PlotTitle.css
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/saga/DatalinkUIWatcher.js
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
  src/firefly/js/visualize/ui/MultiProductViewer.jsx
  src/firefly/js/visualize/ui/ServiceDescriptorPanel.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: enhancement, UI

#1299 FIREFLY-1024: Pinning charts from extraction dialog
  src/firefly/js/charts/ChartUtil.js
  src/firefly/js/charts/ui/ChartsContainer.jsx
  src/firefly/js/charts/ui/PinnedChartPanel.jsx
  src/firefly/js/charts/ui/PlotlyChartArea.jsx
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
Labels: enhancement, Charts
