Repository Caltech-IPAC/firefly, pull requests merged in 2022-06, with the labels that each got.

#1224 [FIREFLY-989] WAVE-TAB: The algorithm is producing incorrect results
  src/firefly/js/visualize/projection/Wavelength.js
  src/firefly/js/visualize/projection/WavelengthHeaderParser.js
  src/firefly/js/visualize/projection/__tests__/WaveTab-test.js
  src/firefly/js/visualize/projection/__tests__/Wavelength-test.js
Labels: bug

#1226 firefly-997: added features and bug fixed to dynamic field generation
  src/firefly/js/drawingLayers/SearchSelectTool.js
  src/firefly/js/drawingLayers/SelectArea.js
  src/firefly/js/fieldGroup/FieldGroupUtils.js
  src/firefly/js/ui/CatalogSearchMethodType.jsx
  src/firefly/js/ui/DynamicUISearchPanel.jsx
  src/firefly/js/ui/FieldGroupConnector.jsx
  src/firefly/js/ui/IbeSpacialType.jsx
  src/firefly/js/ui/InputAreaFieldView.jsx
  src/firefly/js/ui/ListBoxInputField.jsx
  src/firefly/js/ui/SimpleComponent.jsx
  src/firefly/js/ui/SizeInputField.jsx
  src/firefly/js/ui/TargetFeedback.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/TestQueriesPanel.jsx
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicDef.js
  src/firefly/js/ui/dynamic/DynamicUI.css
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/PlotAttribute.js
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/iv/EventLayer.jsx
  src/firefly/js/visualize/ui/ActivateMenu.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/test/edu/caltech/ipac/visualize/plot/ImageHeaderTest.java
Labels: enhancement, UI

#1227 Firefly-995: support defining then passing firefly options from server to client
  docker-compose.yml
  docker/README.md
  docker/launchTomcat.sh
  docker/start-examples.txt
  firefly-docker.env
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/js/Firefly.js
  src/firefly/js/core/AppDataCntlr.js
  src/firefly/js/core/JsonUtils.js
  src/firefly/js/data/ServerParams.js
  src/firefly/js/rpc/CoreServices.js
  src/firefly/js/ui/CatalogSearchMethodType.jsx
  src/firefly/js/ui/InputAreaFieldView.jsx
  src/firefly/js/ui/PopupPanel.jsx
  src/firefly/js/ui/PopupPanelHelper.js
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TapKnownServices.js
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
Labels: enhancement

#1231 FIREFLY-599_1002: Multi tickets changes
  config/web.xml
  docker/launchTomcat.sh
  firefly-docker.env
  src/firefly/js/ui/Banner.css
  src/firefly/js/ui/Banner.jsx
Labels: UI, build, multi-ticket

#1229 FIREFLY-994: Create chart view that support multiple charts from different tables
  docker/java.security.override
  docker/launchTomcat.sh
  src/firefly/html/css/global.css
  src/firefly/html/firefly.html
  src/firefly/js/Firefly.js
  src/firefly/js/charts/ChartUtil.js
  src/firefly/js/charts/ChartsCntlr.js
  src/firefly/js/charts/ui/ChartPanel.css
  src/firefly/js/charts/ui/ChartPanel.jsx
  src/firefly/js/charts/ui/ChartSelectPanel.jsx
  src/firefly/js/charts/ui/ChartWorkArea.jsx
  src/firefly/js/charts/ui/ChartsContainer.jsx
  src/firefly/js/charts/ui/MultiChartToolbar.jsx
  src/firefly/js/charts/ui/MultiChartViewer.jsx
  src/firefly/js/charts/ui/PlotlyChartArea.jsx
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/ui/TextButton.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/visualize/ui/MultiProductViewer.jsx
Labels: enhancement, Charts
