Repository Caltech-IPAC/firefly, pull requests merged in 2022-11, with the labels that each got.

#1283 FIREFLY-1042: Implement derived columns in tables
  docker/Dockerfile
  src/firefly/html/css/global.css
  src/firefly/html/images/insert-col-right-24-24.png
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/JsonDataProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
  src/firefly/java/edu/caltech/ipac/table/DataType.java
  src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
  src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
  src/firefly/java/edu/caltech/ipac/table/TableMeta.java
  src/firefly/java/edu/caltech/ipac/table/io/IpacTableWriter.java
  src/firefly/java/edu/caltech/ipac/util/StringUtils.java
  src/firefly/js/charts/ui/ColumnOrExpression.jsx
  src/firefly/js/data/ServerParams.js
  src/firefly/js/rpc/SearchServicesJson.js
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/tables/ui/AddColumn.jsx
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/FilterEditor.jsx
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/ui/InputFieldLabel.jsx
  src/firefly/js/ui/InputFieldView.jsx
  src/firefly/js/ui/PopupUtil.jsx
  src/firefly/js/ui/SuggestBoxInputField.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/util/Validate.js
  src/firefly/test/edu/caltech/ipac/table/EmbeddedDbUtilTest.java
Labels: enhancement, Table

#1287 FIREFLY-1091: changed layers popup text to be consistent
  src/firefly/js/drawingLayers/ImageRoot.js
Labels: UI

#1285 FIREFLY-1113: Converted CollapsiblePanel to functional component
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/ui/panel/CollapsiblePanel.css
  src/firefly/js/ui/panel/CollapsiblePanel.jsx
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
Labels: UI

#1288 Firefly 1119: Converted RangeSliderView to functional component
  src/firefly/js/templates/lightcurve/LcPeriodPlotly.jsx
  src/firefly/js/ui/FitsRotationDialog.jsx
  src/firefly/js/ui/RangeSlider.jsx
  src/firefly/js/ui/RangeSliderView.jsx
  src/firefly/js/visualize/ui/ColorBandPanel.jsx
  src/firefly/js/visualize/ui/ColorRGBHuePreservingPanel.jsx
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
Labels: enhancement
