Repository Caltech-IPAC/firefly, pull requests merged in 2022-05, with the labels that each got.

#1217 Firefly-980: support HiPS based target selection
  src/firefly/html/images/20x20_click.png
  src/firefly/js/Firefly.js
  src/firefly/js/api/ApiBuild.js
  src/firefly/js/core/BootstrapRegistry.js
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/drawingLayers/SearchSelectTool.js
  src/firefly/js/fieldGroup/FieldGroupCntlr.js
  src/firefly/js/ui/ExampleDialog.jsx
  src/firefly/js/ui/ListBoxInputField.jsx
  src/firefly/js/ui/Menu.css
  src/firefly/js/ui/SimpleComponent.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/visualize/CsysConverter.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/MenuItemKeys.js
  src/firefly/js/visualize/MultiViewCntlr.js
  src/firefly/js/visualize/PlotAttribute.js
  src/firefly/js/visualize/PlotCompleteMonitor.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/WebPlotRequest.js
  src/firefly/js/visualize/draw/ShapeDataObj.js
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/projection/WavelengthHeaderParser.js
  src/firefly/js/visualize/projection/__tests__/Wavelength-test.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/saga/ImagePlotter.js
  src/firefly/js/visualize/task/CreateTaskUtil.js
  src/firefly/js/visualize/task/ImageOverlayTask.js
  src/firefly/js/visualize/task/PlotChangeTask.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/task/WcsMatchTask.js
  src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
  src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
  src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
Labels: UI, HiPS

#1218 Firefly-992: Improve status page, improve the following
  __jest__/InitTest.js
  src/firefly/java/edu/caltech/ipac/firefly/messaging/Messenger.java
  src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventQueue.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
  src/firefly/js/visualize/PlotCompleteMonitor.js
Labels: Infrastructure

#1219 Firefly 494 478 787 812 table related
  src/firefly/js/Firefly.js
  src/firefly/js/api/webApiCommands/TableCommands.js
  src/firefly/js/metaConvert/converterUtils.js
  src/firefly/js/tables/TableRequestUtil.js
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/FilterEditor.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
Labels: bug

#1220 FIREFLY-663: Fail to load votable with datatype 'char' without 'array…
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/js/tables/TableUtil.js
Labels: bug

#1221 FIREFLY-739_665: table cell rendering related
  src/firefly/js/tables/ui/TableRenderer.js
Labels: UI, multi-ticket

#1223 Firefly-981: UI generation and other task
  config/ehcache.xml
  src/firefly/java/edu/caltech/ipac/astro/net/TargetNetwork.java
  src/firefly/java/edu/caltech/ipac/firefly/data/HasSizeOf.java
  src/firefly/java/edu/caltech/ipac/firefly/data/RelatedData.java
  src/firefly/java/edu/caltech/ipac/firefly/server/Counters.java
  src/firefly/java/edu/caltech/ipac/firefly/server/cache/EhcacheProvider.java
  src/firefly/java/edu/caltech/ipac/firefly/server/cache/ObjectSizeEngineWrapper.java
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServiceInput.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/CtxControl.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/DirectStretchUtils.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/FitsCacher.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/ImagePlotCreator.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/FitsDataEval.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/FitsEvaluation.java
  src/firefly/java/edu/caltech/ipac/table/DataType.java
  src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
  src/firefly/java/edu/caltech/ipac/table/TableMeta.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/java/edu/caltech/ipac/util/cache/Cache.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/Histogram.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/RangeValues.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsRead.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/ImageStretch.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/ImageStretchUtil.java
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/drawingLayers/SearchSelectTool.js
  src/firefly/js/fieldGroup/FieldGroupUtils.js
  src/firefly/js/metaConvert/DataLinkProcessor.js
  src/firefly/js/metaConvert/DataProductsCntlr.js
  src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
  src/firefly/js/ui/DynamicUI.css
  src/firefly/js/ui/DynamicUISearchPanel.jsx
  src/firefly/js/ui/FieldGroupConnector.jsx
  src/firefly/js/ui/SimpleComponent.jsx
  src/firefly/js/ui/SizeInputField.jsx
  src/firefly/js/ui/TestQueriesPanel.jsx
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/PlotCompleteMonitor.js
  src/firefly/js/visualize/RangeValues.js
  src/firefly/js/visualize/iv/EventLayer.jsx
  src/firefly/js/visualize/rawData/rawAlgorithm/unused/Histogram.js
  src/firefly/js/visualize/rawData/rawAlgorithm/unused/ImageMask.js
  src/firefly/js/visualize/rawData/rawAlgorithm/unused/RGBIntensity.js
  src/firefly/js/visualize/rawData/rawAlgorithm/unused/RawFloatData.js
  src/firefly/js/visualize/rawData/rawAlgorithm/unused/Stretch.js
  src/firefly/js/visualize/rawData/rawAlgorithm/unused/StretchUtil.js
  src/firefly/js/visualize/rawData/rawAlgorithm/unused/Zscale.js
  src/firefly/js/visualize/ui/ActivateMenu.jsx
  src/firefly/js/visualize/ui/MultiProductViewer.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/test/edu/caltech/ipac/visualize/plot/ImageHeaderTest.java
  src/firefly/test/edu/caltech/ipac/visualize/plot/projection/ProjectionTest.java
Labels: enhancement, UI, Infrastructure
