Repository Caltech-IPAC/firefly, pull requests merged in 2022-08, with the labels that each got.

#1248 Firefly-1045: Fixed several bugs
  firefly-docker.env
  src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HiPSRetrieve.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/Firefly.js
  src/firefly/js/api/webApiCommands/TapCommands.js
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/ImageDataProductsUtil.js
  src/firefly/js/metaConvert/ObsCoreConverter.js
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/ui/PopupPanelHelper.js
  src/firefly/js/ui/SizeInputField.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/visualize/HiPSMocUtil.js
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/PlotGroup.js
  src/firefly/js/visualize/RangeValues.js
  src/firefly/js/visualize/WebPlotRequest.js
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/ui/DrawLayerPanel.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/FitsHeaderView.jsx
  src/firefly/js/visualize/ui/PlotInfoPopup.js
  src/firefly/js/visualize/ui/StretchDropDownView.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
Labels: bug, UI, Infrastructure, multi-ticket

#1250 FIREFLY-1049: Table: Filter by selected row returned more than it should
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
Labels: bug

#1251 Firefly 1046: Add additional tests to StringUtilsTest.java and TableUtil-test.js
  src/firefly/js/tables/__tests__/TableUtil-test.js
  src/firefly/test/edu/caltech/ipac/util/StringUtilsTest.java
Labels: testing

#1253 FIREFLY-1047: add radians and degrees into the list of supported functions used by chart
  src/firefly/js/charts/ui/ColumnOrExpression.jsx
  src/firefly/js/util/expr/Parser.js
Labels: enhancement, Charts

#1252 Firefly 1050 Converting class based to functional components
  src/firefly/js/ui/DateTimePickerField.jsx
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/ui/TimePanel.jsx
Labels: UI

#1256 Docs: development process
  docs/development-process.md
  docs/tags-and-branches.md
Labels: documentation

#1255 IRSA-4756 fix source id searches
  src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java
  src/firefly/js/visualize/ui/ColorBandChooserPopup.jsx
Labels: bug

#1260 Firefly-1067: added imageSize as a new ReservedParam
  src/firefly/js/api/WebApi.js
Labels: API

#1259 Firefly 1056 Coordinates validation for latitude and longitude
  src/firefly/js/util/PositionParser.js
Labels: bug, UI
