Repository Caltech-IPAC/firefly, pull requests merged in 2022-01, with the labels that each got.

#1165 Firefly-915: redo the versioning
  buildScript/global.gincl
  buildScript/tasks.gincl
  config/app.config
  config/common.prop
  docs/new-release-procedure.md
  docs/pre-release-procedure.md
  docs/tags-and-branches.md
  src/firefly/java/edu/caltech/ipac/firefly/data/Version.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/VersionUtil.java
  src/firefly/js/Firefly.js
  src/firefly/js/core/core-typedefs.jsdoc
  src/firefly/js/ui/Banner.jsx
  src/firefly/js/ui/DropDownContainer.css
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/VersionInfo.css
  src/firefly/js/ui/VersionInfo.jsx
Labels: UI, Infrastructure

#1166 Firefly-917: update as many packages as possible in package.json
  .eslintrc
  buildScript/tasks.gincl
  buildScript/webpack.config.js
  package-json-doc.md
  package.json
  src/firefly/js/core/background/PackageProgress.js
  src/firefly/js/drawingLayers/FootprintToolUI.jsx
  src/firefly/js/ui/DateTimePickerField.jsx
  src/firefly/js/ui/PointShapeSizePicker.jsx
  src/firefly/js/ui/SizeInputField.jsx
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/util/BrowserInfo.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/draw/ShapeDataObj.js
  src/firefly/js/visualize/draw/ShapeToRegion.js
  src/firefly/js/visualize/region/RegionFactory.js
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
  src/firefly/package.json
  src/firefly/webpack.config.js
  yarn.lock
Labels: Infrastructure

#1167 replace the old docker dev environment with something simple
  buildScript/tasks.gincl
  docker-compose.yml
  docker/Dockerfile
  docker/Dockerfile.dockerignore
  docker/Dockerfile.orig
  docker/README.md
  docker/base/.gitignore
  docker/base/tomcat-users.xml
  docker/builder/Dockerfile
  docker/builder/README.md
  docker/cleanup.sh
  docker/context.xml
  docker/customize-firefly.txt
  docker/k8s/dashboard-users.yaml
  docker/k8s/firefly.yaml
  docker/k8s/kubernetes_setup.md
  docker/k8s/misc/busybox.yaml
  docker/k8s/nginx-controller.yaml
  docker/k8s/nginx-svc.yaml
  docker/launchTomcat.sh
  docker/local.xml
  docker/proxy-dev/Dockerfile
  docker/proxy-dev/build.gradle
  docker/proxy-dev/others/openid.conf
  docker/proxy-dev/others/proxy.conf
  docker/proxy-dev/others/site.conf
  docker/proxy-dev/proxyctl.sh
  docker/proxy/Dockerfile
  docker/proxy/build.gradle
  docker/proxy/others/default.conf.in
  docker/proxy/others/init_letsencrypt.sh
  docker/proxy/others/proxy.conf
  docker/proxy/proxyctl.sh
  docker/sendLogsToConsole.sh
  docker/setupFireflyExample.sh
  docker/start-examples.txt
  docker/tomcat-users.xml
  package.json
  yarn.lock
Labels: build

#1168 replace the old docker dev environment with something simple
  .gitignore
  buildScript/gwt_webapp.gincl
  buildScript/utils.gincl
  docker/Dockerfile
  docker/Dockerfile.dockerignore
  docker/README.md
  docker/cleanup.sh
  docker/context.xml
  docker/customize-firefly.txt
  docker/java.security.override
  docker/launchTomcat.sh
  docker/local.xml
  docker/sendLogsToConsole.sh
  docker/setupFireflyExample.sh
  docker/start-examples.txt
  docker/tomcat-users.xml
  package.json
Labels: build

#1171 Firefly-916: fixed: API adding to DOM before page load
  src/firefly/js/Firefly.js
Labels: bug
