Repository Caltech-IPAC/firefly, pull requests merged in 2022-10, with the labels that each got.

#1274 FIREFLY-1041: add feature to combine charts(spectra)
  buildScript/webpack.config.js
  docker/Dockerfile
  docker/devMode.sh
  src/firefly/html/demo/table-api.html
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
  src/firefly/js/api/ApiHighlevelBuild.js
  src/firefly/js/charts/ChartUtil.js
  src/firefly/js/charts/ChartsCntlr.js
  src/firefly/js/charts/chart-typedefs.jsdoc
  src/firefly/js/charts/dataTypes/FireflyGenericData.js
  src/firefly/js/charts/dataTypes/SpectrumUnitConversion.js
  src/firefly/js/charts/ui/ChartPanel.css
  src/firefly/js/charts/ui/ChartSelectPanel.jsx
  src/firefly/js/charts/ui/ChartWorkArea.jsx
  src/firefly/js/charts/ui/CombineChart.jsx
  src/firefly/js/charts/ui/MultiChartViewer.jsx
  src/firefly/js/charts/ui/options/BasicOptions.jsx
  src/firefly/js/charts/ui/options/SpectrumOptions.jsx
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/tables/ui/TablePanel.jsx
Labels: enhancement, Charts, UI

#1278 firefly-1103: Fix firefly fITS reader so it can read Multiple large HDUs for a 14G file
  config/app.config
  docs/server-settings-for-fits-files.md
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisContext.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsRead.java
Labels: bug

#1279 Firefly-1092 no WCS warning when trying to align by WCS
  src/firefly/js/visualize/ui/MatchLockDropDown.jsx
Labels: bug, UI

#1275 FIREFLY-1086: Click to Action
  src/firefly/html/images/b4.png
  src/firefly/js/Firefly.js
  src/firefly/js/api/ApiBuild.js
  src/firefly/js/api/webApiCommands/LcWebApiCommands.js
  src/firefly/js/api/webApiCommands/TapCommands.js
  src/firefly/js/charts/ui/ColSelectView.jsx
  src/firefly/js/core/ClickToAction.js
  src/firefly/js/core/History.js
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/core/MasterSaga.js
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/ui/ActionsDropDownButton.jsx
  src/firefly/js/ui/DefaultSearchActions.js
  src/firefly/js/ui/PopupPanel.jsx
  src/firefly/js/ui/PopupPanelHelper.js
  src/firefly/js/ui/SearchPanel.jsx
  src/firefly/js/ui/SizeInputField.jsx
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/PlotState.js
  src/firefly/js/visualize/SearchRefinementTool.jsx
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/WebPlotRequest.js
  src/firefly/js/visualize/draw/DrawLayer.js
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/saga/ActiveRowCenterWatcher.js
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/saga/DataProductsWatcher.js
  src/firefly/js/visualize/saga/MOCWatcher.js
  src/firefly/js/visualize/saga/UrlLinkWatcher.js
  src/firefly/js/visualize/ui/CommonUIKeys.js
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: enhancement, Image, UI, HiPS

#1280 Firefly-1060: Support datatype and other features in extract
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ExtractFromImage.java
  src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
  src/firefly/java/edu/caltech/ipac/table/io/FITSExtractToTable.java
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsExtract.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsRead.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
  src/firefly/js/data/ServerParams.js
  src/firefly/js/rpc/PlotServicesJson.js
  src/firefly/js/visualize/FitsHeaderUtil.js
  src/firefly/js/visualize/saga/MouseReadoutWatch.js
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
Labels: enhancement, Image

#1281 Firefly-1106: enhanced field group request
  src/firefly/js/ui/CompleteButton.jsx
  src/firefly/js/ui/ExampleDialog.jsx
  src/firefly/js/ui/FieldGroup.jsx
  src/firefly/js/ui/FieldGroupConnector.jsx
  src/firefly/js/ui/IbeSpacialType.jsx
  src/firefly/js/ui/SimpleComponent.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
Labels: enhancement, Infrastructure

#1277 FIREFLY-659: changed 2MASS ordering based on popularity
  src/firefly/java/edu/caltech/ipac/firefly/resources/irsa-image-master-table.csv
Labels: bug
