Repository Caltech-IPAC/firefly, pull requests merged in 2022-02, with the labels that each got.

#1172 Firefly-922: fixed: MOC should just be added to HiPS and not images
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java
  src/firefly/java/edu/caltech/ipac/util/download/CacheHelper.java
  src/firefly/js/Firefly.js
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/visualize/saga/MOCWatcher.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/task/PlotImageTask.js
Labels: bug

#1173 Firefly-926: now shows all headers, before is was not showing repeating headers
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java
  src/firefly/js/visualize/FitsHeaderUtil.js
  src/firefly/js/visualize/ui/FitsHeaderView.jsx
Labels: bug

#1174 Firefly-908: Allow extraction to stay on when new images are added
  src/firefly/js/drawingLayers/ExtractLineTool.js
  src/firefly/js/drawingLayers/ExtractPointsTool.js
  src/firefly/js/drawingLayers/PointSelection.js
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
Labels: enhancement

#1176 Firefly-791: remove old LSST code
  config/app.config
  src/firefly/config/app.prop
  src/firefly/html/demo/ffapi-highlevel-test.html
  src/firefly/html/lsst-api-triview.html
  src/firefly/html/lsst-pdac-triview.html
  src/firefly/java/edu/caltech/ipac/firefly/resources/LSSTMetaInfo.json
  src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTCatalogSearch.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTFileGroupProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTImageSearch.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTLightCurveQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTMetaSearch.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTMultiObjectSearch.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTTables.java
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/LsstSdssRequestList.js
  src/firefly/js/tables/TableRequestUtil.js
  src/firefly/js/templates/lightcurve/LcConverterFactory.js
  src/firefly/js/templates/lightcurve/lsst_sdss/LsstSdssMissionOptions.js
  src/firefly/js/templates/lightcurve/lsst_sdss/LsstSdssPlotRequests.js
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
  src/firefly/js/visualize/ui/LSSTImageSpatialType.jsx
Labels: Infrastructure

#1175 Firefly-907: provide a way to disable extraction
  src/firefly/html/css/global.css
  src/firefly/html/test/tests-main.html
  src/firefly/js/ui/PopupPanel.css
  src/firefly/js/visualize/MenuItemKeys.js
  src/firefly/js/visualize/iv/ImageViewerStatus.jsx
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
  src/firefly/js/visualize/ui/VisToolbarView.jsx
Labels: bug, API, multi-ticket

#1180 FIREFLY-931: Saving filtered table is broken
  src/firefly/js/tables/TableUtil.js
Labels: bug

#1181 FIREFLY-883: "Data Type" column in Radar results no longer have filter choices
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
Labels: bug

#1182 Firefly-935: Add quotes to table or columns where needed
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/util/ObsCoreSRegionParser.js
Labels: enhancement

#1183 firefly-847: fixed: TAP Panel Bug in "populate" ADQL from the SingleTable input panel
  src/firefly/js/tables/FilterInfo.js
  src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
  src/firefly/js/visualize/iv/ExpandedTools.jsx
Labels: bug, enhancement

#1189 FIREFLY-938: ZTF proprietary metadata is not returned in GUI
  src/firefly/java/edu/caltech/ipac/astro/ibe/IBE.java
  src/firefly/java/edu/caltech/ipac/astro/ibe/IbeFileUploader.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ibe/IbeFileUploaderImpl.java
Labels: bug

#1190 FIREFLY-939: Table search sometime do not return results
  src/firefly/js/tables/TablesCntlr.js
Labels: bug

#1186 firefly-45,firefly-543,Firefly-633: Multiple tickets
  src/firefly/html/test/test-image.html
  src/firefly/js/drawingLayers/Catalog.js
  src/firefly/js/visualize/MenuItemKeys.js
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/draw/DrawSymbol.js
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
  src/firefly/js/visualize/ui/ZoomButton.jsx
Labels: bug, enhancement, multi-ticket

#1187 FIREFLY-933: Upgrade Log4J to latest version 2.17.1
  buildScript/dep-init.gincl
  buildScript/global.gincl
  buildScript/tasks.gincl
  config/app.config
  config/log4j.properties
  config/log4j2.properties
  config/logging.properties
  config/test/log4j-test.properties
  config/web.xml
  docker-compose.yml
  docker/Dockerfile
  docker/Dockerfile.orig
  docker/README.md
  docker/launchTomcat.sh
  docker/sendLogsToConsole.sh
  jars/log4j/log4j-1.2.14.jar
  jars/log4j/log4j-api-2.17.1.jar
  jars/log4j/log4j-core-2.17.1.jar
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/java/edu/caltech/ipac/firefly/server/cache/EhcacheTest.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/Logger.java
  src/firefly/java/edu/caltech/ipac/firefly/tools/FitsHeaderTool.java
  src/firefly/test/edu/caltech/ipac/firefly/ConfigTest.java
  src/firefly/test/edu/caltech/ipac/firefly/ws/WsTest.java
  src/firefly/test/edu/caltech/ipac/util/cache/CachePeerProviderFactoryTest.java
Labels: build
