Repository Caltech-IPAC/firefly, pull requests merged in 2022-09, with the labels that each got.

#1263 IRSA-4796: Fixed: wise image navigation icons vanish
  src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/util/__tests__/VOAnalyzer-test.js
  src/firefly/js/visualize/saga/DataProductsWatcher.js
  src/firefly/js/visualize/ui/MetaDataMultiProductViewer.jsx
  src/firefly/js/visualize/ui/MultProductViewerContainer.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
Labels: bug

#1264 Firefly 1065 naif resolver (multiple results unrelated to input showing up)
  src/firefly/java/edu/caltech/ipac/astro/net/HorizonsEphPairs.java
Labels: bug

#1265 FIREFLY-1068: Recognize and permit default display of flux-based time series
  src/firefly/js/metaConvert/PartAnalyzer.js
Labels: enhancement

#1268 IRSA-4793: allow to use band for more than one color
  src/firefly/js/visualize/saga/DataProductsWatcher.js
  src/firefly/js/visualize/task/CreateTaskUtil.js
  src/firefly/js/visualize/ui/ColorBandChooserPopup.jsx
Labels: enhancement, Image

#1267 Firefly 1063 PointShapeSizePicker class to functional component
  src/firefly/js/ui/PointShapeSizePicker.jsx
Labels: UI

#1271 Firefly 1075 obs tap date update calendar dialog
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
Labels: bug

#1272 [FIREFLY-1079] Update Plotly to v2.18.0
  src/firefly/html/plotly-1.58.4.min.js
  src/firefly/html/plotly-2.14.0.min.js
  src/firefly/js/charts/ChartsCntlr.js
  src/firefly/js/charts/PlotlyConfig.js
  src/firefly/js/charts/ui/PlotlyChartArea.jsx
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
Labels: enhancement, Charts
