Repository Caltech-IPAC/firefly, pull requests merged in 2023-07, with the labels that each got.

#1402 FIREFLY 1073: Support for 'POINT' type s_region and prevent coverage from failing
  src/firefly/js/util/ObsCoreSRegionParser.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
Labels: bug

#1393 IRSA-5326: Create prototype Euclid App using React Router template
  package.json
  src/firefly/html/css/global.css
  src/firefly/js/Firefly.js
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/core/background/BgMonitorButton.jsx
  src/firefly/js/templates/common/FireflyLayout.jsx
  src/firefly/js/templates/common/MainPanel.jsx
  src/firefly/js/templates/router/RouterEntry.jsx
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/Menu.jsx
  yarn.lock
Labels: Infrastructure

#1401 Firefly 1150 object id tap
  src/firefly/js/ui/UploadTableChooser.js
  src/firefly/js/ui/tap/ObjectIDSearch.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TemporalSearch.jsx
Labels: bug, enhancement, UI

#1407 Firefly-1276,Firefly-1277
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/metaConvert/converterUtils.js
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
  src/firefly/js/visualize/ui/MouseReadout.css
  src/firefly/js/visualize/ui/MouseReadout.jsx
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
Labels: bug, Image, multi-ticket

#1403 FIREFLY-1260: Remove multiple copies of QueryMOS
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/JsonStringProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/mos/QueryMOS.java
Labels: Refactor

#1410 IRSA-5359: Fix Data Product Viewer not updating on changing table tabs for the 1st time
  src/firefly/js/visualize/saga/DataProductsWatcher.js
Labels: bug

#1408 Firefly-1286: DCE and search features
  src/firefly/js/drawingLayers/Catalog.js
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/TestQueriesPanel.jsx
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.css
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: UI

#1404 FIREFLY-1256: Create a property sheet (or table row details) component to use in viewer and API
  src/firefly/html/images/icons-2014/36x36-data-info.png
  src/firefly/js/Firefly.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/ui/PropertySheet.jsx
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
Labels: enhancement, Table, UI

#1411 Firefly-1291: obscore data products result should show search target
  src/firefly/js/metaConvert/ObsCoreConverter.js
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: UI

#1409 FIREFLY-1285: SPHEREx photometry table sample fails to load
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/table/DataType.java
  src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
  src/firefly/java/edu/caltech/ipac/table/io/DsvTableIO.java
  src/firefly/java/edu/caltech/ipac/table/io/IpacTableWriter.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableWriter.java
Labels: bug, Table

#1406 FIREFLY-1257: UI for identification and entry of JOINs in ADQL queries
  src/firefly/html/images/join_16x16.png
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/ui/panel/DockLayoutPanel.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.css
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
Labels: enhancement, UI

#1413 Firefly-1281: Fixing error in processing s_region values containing zeros
  src/firefly/js/util/ObsCoreSRegionParser.js
Labels: bug

#1412 Firefly-1292: TAP UI Crashes when selecting TAP_SCHEMA table
  src/firefly/js/ui/tap/TemporalSearch.jsx
Labels: bug

#1415 FIREFLY-1256: Fix property sheet causing error in loading IrsaViewer
  src/firefly/js/Firefly.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/ui/PropertySheet.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
Labels: bug
