Repository Caltech-IPAC/firefly, pull requests merged in 2023-03, with the labels that each got.

#1326 Firefly-1152: Clean up "Click to Search"
  src/firefly/js/drawingLayers/SearchSelectTool.js
  src/firefly/js/drawingLayers/SelectArea.js
  src/firefly/js/drawingLayers/SelectedShape.js
  src/firefly/js/metaConvert/ObsCoreConverter.js
  src/firefly/js/ui/ActionsDropDownButton.jsx
  src/firefly/js/ui/DefaultSearchActions.js
  src/firefly/js/ui/InputFieldView.jsx
  src/firefly/js/ui/SizeInputField.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/MenuItemKeys.js
  src/firefly/js/visualize/PlotAttribute.js
  src/firefly/js/visualize/SearchRefinementTool.jsx
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/WebPlotRequest.js
  src/firefly/js/visualize/draw/DrawUtil.js
  src/firefly/js/visualize/draw/SelectBox.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/task/PlotChangeTask.js
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
  src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx
  src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/ToolbarToolModalEnd.js
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: enhancement, UI

#1327 IRSA-5027: Fixed search-by-naifID not working when using name over id field
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/server/rpc/ResolveServerCommands.java
  src/firefly/js/ui/NaifidPanel.jsx
  src/firefly/js/ui/NaifidPanelWorker.js
Labels: enhancement

#1333 IRSA-5112: Add data preview and download button to advanced search types
  src/firefly/js/metaConvert/ShaRequestList.js
Labels: enhancement

#1332 FIREFLY-1155: fixed crash on tap search in finderchart
  src/firefly/js/core/background/BgMonitorButton.jsx
Labels: bug

#1328 Firefly-1177: atlas clean up
  src/firefly/html/css/global.css
  src/firefly/html/images/hide-left-3.png
  src/firefly/html/images/show-right-3.png
  src/firefly/js/core/ClickToAction.js
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/ImageDataProductsUtil.js
  src/firefly/js/metaConvert/ObsCoreConverter.js
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js
  src/firefly/js/templates/fireflyviewer/ResultsPanel.jsx
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/ui/ActionsDropDownButton.jsx
  src/firefly/js/ui/DefaultSearchActions.js
  src/firefly/js/ui/DropDownContainer.css
  src/firefly/js/ui/IrsaFooter.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/TestQueriesPanel.jsx
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/dynamic/FetchDatalinkTable.js
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/visualize/HiPSUtil.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/MultiViewCntlr.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/SearchRefinementTool.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/saga/DataProductsWatcher.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/MatchLockDropDown.jsx
  src/firefly/js/visualize/ui/MultiProductViewer.jsx
  src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
  src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/TargetHipsPanelToolbar.jsx
  src/firefly/js/visualize/ui/ToolbarToolModalEnd.js
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: enhancement, Image, UI, HiPS

#1329 updates for NEOWISE year9 data release
  docs/release-notes.md
  src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java
  src/firefly/java/edu/caltech/ipac/firefly/data/WiseRequest.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/QueryWise.java
  src/firefly/js/ui/PagingBar.jsx
  src/firefly/js/visualize/saga/DataProductsWatcher.js
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/MultProductViewerContainer.jsx
Labels: bug, multi-ticket

#1331 FIREFLY-1148: table chooser to load existing table into tap panel
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HttpServCommands.java
  src/firefly/js/ui/FileUploadDropdown.jsx
  src/firefly/js/ui/UploadTableChooser.js
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
Labels: UI

#1330 FIREFLY-1153: Derived Columns Updates
  src/firefly/html/images/16x16_edit_icon.png
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HttpServCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerCommands.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/js/charts/ui/ColumnOrExpression.jsx
  src/firefly/js/data/ServerParams.js
  src/firefly/js/rpc/SearchServicesJson.js
  src/firefly/js/tables/ui/AddColumn.jsx
  src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/tables/ui/TableSave.jsx
  src/firefly/test/edu/caltech/ipac/table/EmbeddedDbUtilTest.java
Labels: enhancement, Table

#1334 firefly-1186: fixes some atlas replacement bugs
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSListUtil.java
  src/firefly/js/core/AppDataCntlr.js
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/templates/fireflyviewer/ResultsPanel.jsx
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/ui/HiPSImageSelect.jsx
  src/firefly/js/ui/RadioGroupInputFieldView.jsx
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.css
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/visualize/HiPSListUtil.js
  src/firefly/js/visualize/HiPSMocUtil.js
  src/firefly/js/visualize/PlotCompleteMonitor.js
  src/firefly/js/visualize/WebPlotRequest.js
  src/firefly/js/visualize/draw/Drawer.js
  src/firefly/js/visualize/iv/HiPSRenderer.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/saga/MOCWatcher.js
  src/firefly/js/visualize/task/CreateTaskUtil.js
  src/firefly/js/visualize/task/PlotChangeTask.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
Labels: bug

#1335 FIREFLY-1141: column chooser popup
  src/firefly/js/charts/ui/ColSelectView.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
Labels: enhancement, UI

#1336 IRSA-3145: SHA migration: Added result by IRS Enhanced
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/BaseGator.java
Labels: API

#1338 Firefly-1190: optimize byte data loading based on zoom
  src/firefly/js/visualize/rawData/RawDataCache.js
  src/firefly/js/visualize/rawData/RawDataOps.js
  src/firefly/js/visualize/task/ZoomTask.js
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
Labels: enhancement

#1340 Firefly-1089: fix for nan/inf plot errors
  src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
Labels: bug

#1341 Firefly-1194: fixed date parsing in TableUtil.js
  src/firefly/js/tables/TableUtil.js
Labels: bug
