Repository Caltech-IPAC/firefly, pull requests merged in 2023-06, with the labels that each got.

#1388 IRSA-5099: SHA migration: Add abstract search
  src/firefly/html/demo/table-api.html
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
Labels: enhancement

#1389 FIREFLY-1253: TAP Query mishandled redirects originating from an "/error" status
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServiceInput.java
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/js/core/background/BackgroundUtil.js
  src/firefly/test/edu/caltech/ipac/firefly/server/network/HttpServicesTest.java
Labels: bug

#1392 Firefly-1252: spacial missing
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/js/charts/ui/ColumnOrExpression.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/ui/tap/TemportalSearch.jsx
Labels: bug

#1394 IRSA-5327: FinderChart API stopped working
  buildScript/global.gincl
  jars/xstream/xstream-1.3.1.jar
  jars/xstream/xstream-1.4.20.jar
Labels: bug

#1382 FIREFLY-1242: Preserve filters when 3 color default selection is made
  src/firefly/js/ui/ImageSelect.jsx
Labels: bug

#1395 FIREFLY-1255: heatmap failed due to uncaught exception
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
Labels: bug

#1390 FIREFLY-1232: Remove StarTable from FITS Table Reader
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
Labels: enhancement

#1391 Firefly 1250 concurrent
  src/firefly/js/api/webApiCommands/DatalinkUICommands.js
  src/firefly/js/metaConvert/ObsCoreConverter.js
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/ui/CheckboxGroupInputField.jsx
  src/firefly/js/ui/TargetFeedback.jsx
  src/firefly/js/ui/dynamic/DLGenAnalyzeSearch.js
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicDef.js
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
Labels: enhancement

#1398 Update release procedure docs
  docs/new-release-procedure.md
  docs/release-page-template.md
Labels: documentation

#1396 Firefly-1127: upgrade react to 18
  package.json
  src/firefly/js/Firefly.js
  src/firefly/js/api/ApiUtil.js
  src/firefly/js/ui/DialogRootContainer.jsx
  src/firefly/js/ui/LostConnection.jsx
  src/firefly/js/ui/SimpleComponent.jsx
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/iv/ImageViewer.jsx
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbar.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
  yarn.lock
Labels: Infrastructure

#1399 Firefly-1263: optimize fits table read
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
Labels: enhancement
