Repository Caltech-IPAC/firefly, pull requests merged in 2023-01, with the labels that each got.

#1303 FIREFLY-250: Lock position and size across RGB for 3 color image
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Labels: UI

#1305 IRSA-5005: Switch to OpenJdk from eclipse-temurin instead of deprecated openjdk.
  docker/Dockerfile
  docker/java.security.override
  docker/launchTomcat.sh
  jars/j2ee/mail.jar
Labels: Infrastructure

#1306 FIREFLY-1058: Fix synchronization problem with image outlines in target-panel polygon-search
  src/firefly/js/ui/CatalogSearchMethodType.jsx
Labels: bug

#1307 FIREFLY-1138: Make help base URL a runtime configuratable property
  config/app.config
  config/common.prop
  docker/Dockerfile
  docker/devMode.sh
  src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/js/Firefly.js
  src/firefly/js/core/AppDataCntlr.js
  src/firefly/js/tables/ui/AddColumn.jsx
Labels: Infrastructure

#1308 FIREFLY-1128: Firefly UWS support
  config/log4j2.properties
  src/firefly/java/edu/caltech/ipac/firefly/api/Async.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/Job.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/ServCmdJob.java
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/CatMasterTableQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/GatorMOS.java
  src/firefly/java/edu/caltech/ipac/firefly/server/network/DataGroupHandler.java
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
  src/firefly/java/edu/caltech/ipac/firefly/server/network/IpacTableHandler.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagedEmail.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncJob.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncSearchProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/mos/QueryMOS.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/StopWatch.java
  src/firefly/java/edu/caltech/ipac/firefly/util/Ref.java
  src/firefly/js/core/background/BackgroundMonitor.css
  src/firefly/js/core/background/BackgroundMonitor.jsx
  src/firefly/js/core/background/BgMaskPanel.jsx
  src/firefly/js/core/background/BgMonitorButton.jsx
  src/firefly/js/core/background/JobInfo.jsx
  src/firefly/js/data/ServerParams.js
  src/firefly/js/rpc/SearchServicesJson.js
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/test/edu/caltech/ipac/firefly/messaging/MessengerTest.java
  src/firefly/test/edu/caltech/ipac/firefly/server/network/HttpServicesTest.java
  src/firefly/test/edu/caltech/ipac/firefly/server/query/AsyncTapQueryTest.java
  src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/DataGroupReadTest.java
Labels: enhancement

#1309 Firefly-1139: Allow params to be passed to the datalink UI
  src/firefly/js/FFEntryPoint.js
  src/firefly/js/api/webApiCommands/DatalinkUICommands.js
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/ui/CatalogSearchMethodType.jsx
  src/firefly/js/ui/FileUploadProcessor.jsx
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicDef.js
  src/firefly/js/ui/dynamic/FetchDatalinkTable.js
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/visualize/saga/DatalinkUIWatcher.js
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: UI

#1311 FIREFLY-1136: embedded DB customization via props
  firefly-docker.env
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ResourceProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
  src/firefly/test/edu/caltech/ipac/table/EmbeddedDbUtilTest.java
Labels: Table

#1304 Firefly-1133: lsst issues
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
  src/firefly/js/charts/ChartUtil.js
  src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/WavelengthPanel.jsx
  src/firefly/js/visualize/RelatedDataUtil.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
Labels: bug, enhancement

#1310 Firefly-1134: Add default 3 color entries in ImageSearchPanel
  src/firefly/java/edu/caltech/ipac/firefly/resources/irsa-image-master-table.csv
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imagesources/ImageMasterDataEntry.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imagesources/IrsaMasterDataSource.java
  src/firefly/js/ui/ImageSelect.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/UIConst.js
Labels: enhancement

#1313 Firefly-1144: add better support tap search params for click-to-action
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/js/core/AppDataCntlr.js
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/templates/fireflyslate/FireflySlate.jsx
  src/firefly/js/ui/DefaultSearchActions.js
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
Labels: enhancement
