Repository Caltech-IPAC/firefly, pull requests merged in 2023-04, with the labels that each got.

#1343 FIREFLY-669: Fix offset in rotate image slider's handle
  src/firefly/js/ui/rc-slider.css
Labels: bug

#1342 Firefly-1192: client side obs core packaging
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
Labels: enhancement

#1339 FIREFLY-1061: Fix "Page size" appearing in client-table gears dialogs
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/templates/lightcurve/LcManager.js
Labels: bug

#1344 Several fixes and improvements
  src/firefly/js/metaConvert/DataLinkProcessor.js
  src/firefly/js/metaConvert/DataProductsType.js
  src/firefly/js/metaConvert/ObsCoreConverter.js
  src/firefly/js/metaConvert/ServDescConverter.js
  src/firefly/js/templates/fireflyslate/GridLayoutPanel.jsx
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/visualize/iv/ExpandedTools.jsx
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
  src/firefly/js/visualize/ui/MultProductViewerContainer.jsx
  src/firefly/js/visualize/ui/MultiProductViewer.jsx
  src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
  src/firefly/js/visualize/ui/multiProduct/DPDropdown.jsx
  src/firefly/js/visualize/ui/multiProduct/MPMessages.jsx
  src/firefly/js/visualize/ui/multiProduct/MetaDataMultiProductViewer.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
Labels: bug, enhancement

#1345 Firefly-1208: Multi ticket
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterList.java
  src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/visualize/saga/MouseReadoutWatch.js
  src/firefly/js/visualize/task/CreateTaskUtil.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/TargetHipsPanelToolbar.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: bug, multi-ticket

#1347 Firefly Multi ticket: fix multiple issues
  src/firefly/js/drawingLayers/SelectArea.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/iv/PlotTitle.jsx
  src/firefly/js/visualize/rawData/RawDataCache.js
  src/firefly/js/visualize/rawData/RawDataCommon.js
  src/firefly/js/visualize/rawData/RawDataOps.js
  src/firefly/js/visualize/ui/CtxToolbarFunctions.js
  src/firefly/js/visualize/ui/MouseReadPopoutAll.jsx
  src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx
  src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: bug, multi-ticket

#1349 Firefly-1209: polygon examples
  src/firefly/js/ui/FitsDownloadDialog.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicDef.js
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/visualize/iv/ExpandedTools.jsx
  src/firefly/js/visualize/ui/CtxToolbarFunctions.js
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
Labels: bug

#1348 FIREFLY-1183: Combine spectra cleanup
  src/firefly/html/css/global.css
  src/firefly/java/edu/caltech/ipac/table/DataGroupPart.java
  src/firefly/js/charts/dataTypes/FireflyGenericData.js
  src/firefly/js/charts/dataTypes/FireflySpectrum.js
  src/firefly/js/charts/dataTypes/SpectrumUnitConversion.js
  src/firefly/js/charts/ui/ChartPanel.css
  src/firefly/js/charts/ui/ChartPanel.jsx
  src/firefly/js/charts/ui/ChartsContainer.jsx
  src/firefly/js/charts/ui/CombineChart.jsx
  src/firefly/js/charts/ui/MultiChartToolbar.jsx
  src/firefly/js/charts/ui/PinnedChartPanel.jsx
  src/firefly/js/charts/ui/PlotlyChartArea.jsx
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
  src/firefly/js/charts/ui/PlotlyWrapper.jsx
  src/firefly/js/charts/ui/options/Errors.jsx
  src/firefly/js/charts/ui/options/ScatterOptions.jsx
  src/firefly/js/charts/ui/options/SpectrumOptions.jsx
  src/firefly/js/core/background/BackgroundCntlr.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/reducer/TableDataReducer.js
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
Labels: Charts

#1354 Firefly 1215: Improved TAP UI
  src/firefly/html/images/hide-down-3.png
  src/firefly/html/images/show-up-3.png
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/IrsaHiPSListSource.java
  src/firefly/js/Firefly.js
  src/firefly/js/ui/ButtonGroup.css
  src/firefly/js/ui/FormPanel.jsx
  src/firefly/js/ui/RadioGroupInputFieldView.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.css
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapKnownServices.js
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/visualize/task/PlotHipsTask.js
Labels: enhancement, UI

#1355 FIREFLY-1218: Allow onlinehelp base URL to be overridden as firefly options on the client
  config/app.config
  config/common.prop
  src/firefly/js/core/AppDataCntlr.js
Labels: Infrastructure

#1353 FIREFLY-1170: Allow HTML in link's value(Table)
  src/firefly/html/test/images/tbl_links.png
  src/firefly/html/test/tests-table.html
  src/firefly/js/tables/ui/TableRenderer.js
Labels: Table

#1351 Firefly 1193 ObsCore Packager
  src/firefly/java/edu/caltech/ipac/firefly/data/FileInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/ZipHandler.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
  src/firefly/java/edu/caltech/ipac/util/FileUtil.java
  src/firefly/js/core/background/BackgroundMonitor.jsx
  src/firefly/js/templates/common/ttFeatureWatchers.js
Labels: UI

#1352 FIREFLY-1166: Recognize Spectral order and SED proposed in SDM V1.2
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/ZipHandler.java
  src/firefly/java/edu/caltech/ipac/table/io/SpectrumMetaInspector.java
  src/firefly/js/util/VOAnalyzer.js
Labels: Charts

#1358 FIREFLY-712: Table upload not accepting compliant IPAC tables
  src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
Labels: Table

#1359 FIREFLY-1222 Bug fix in the readout of pixels with value 0.
  src/firefly/java/edu/caltech/ipac/firefly/visualize/ClientFitsHeader.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/ImageHeader.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/PixelValue.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/Zscale.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsExtract.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsRead.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/ImageStretch.java
  src/firefly/js/visualize/projection/ProjectionHeaderParser.js
Labels: bug

#1357 Firefly-1198:whole table search fix for TAP services not supporting uploads
  src/firefly/js/ui/DefaultSearchActions.js
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
Labels: bug

#1360 FIREFLY-1125: fixed csv file with bad colum names
  src/firefly/java/edu/caltech/ipac/firefly/data/SortInfo.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/java/edu/caltech/ipac/table/io/DsvTableIO.java
  src/firefly/java/edu/caltech/ipac/util/StringUtils.java
  src/firefly/js/tables/SortInfo.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/ui/TableRenderer.js
Labels: Table

#1362 Firefly-1225: fixed: multiple issues
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileDownload.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HiPSRetrieve.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSListUtil.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/charts/ui/ColumnOrExpression.jsx
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/visualize/HiPSListUtil.js
  src/firefly/js/visualize/HiPSUtil.js
  src/firefly/js/visualize/iv/EventLayer.jsx
  src/firefly/js/visualize/rawData/RawDataCommon.js
  src/firefly/js/visualize/rawData/RawDataOps.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/ui/MultiImageViewerView.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/TargetHipsPanelToolbar.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
  src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
Labels: bug, enhancement, multi-ticket

#1361 Firefly-1212: filter upload tbl columns down to user selected cols
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
  src/firefly/js/ui/DefaultSearchActions.js
  src/firefly/js/ui/UploadTableChooser.js
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
Labels: bug, enhancement

#1365 Firefly-1228: fix position of desc tag when writing to VOTable
  src/firefly/java/edu/caltech/ipac/table/io/VoTableWriter.java
Labels: bug

#1367 IRSA-5175: Fix the right-side of the tri-view to accommodate both Charts and Coverage
  src/firefly/js/charts/ChartUtil.js
  src/firefly/js/charts/ui/ChartPanel.jsx
  src/firefly/js/charts/ui/ChartsContainer.jsx
  src/firefly/js/charts/ui/CombineChart.jsx
  src/firefly/js/charts/ui/PinnedChartContainer.jsx
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
Labels: UI

#1366 Firefly-1229: Clean up and fix bug related to Rubin
  docs/older-release-notes-2022.md
  docs/release-notes.md
  src/firefly/html/css/global.css
  src/firefly/html/firefly-dev.html
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HiPSRetrieve.java
  src/firefly/java/edu/caltech/ipac/table/io/SpectrumMetaInspector.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/Firefly.js
  src/firefly/js/drawingLayers/Catalog.js
  src/firefly/js/fieldGroup/FieldGroupUtils.js
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/util/ObsCoreSRegionParser.js
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
  src/firefly/js/visualize/ui/ThumbnailView.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
  src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
Labels: bug

#1369 Firefly-1237: fixed
  src/firefly/js/ui/CatalogSearchMethodType.jsx
Labels: bug

#1372 Firefly 1238: clear polygon
  docs/release-notes.md
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: bug

#1370 FIREFLY-1236: fixed Save table dialog badly rendered when Workspace is chosen
  src/firefly/js/tables/ui/TableSave.jsx
  src/firefly/js/ui/DownloadOptionsDialog.jsx
Labels: UI

#1371 FIREFLY-1156: better SQL error message for added column failure
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
  src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
  src/firefly/test/edu/caltech/ipac/table/EmbeddedDbUtilTest.java
Labels: Table
