Repository Caltech-IPAC/firefly, pull requests merged in 2023-02, with the labels that each got.

#1312 Firefly 1130 Modify FileUploadViewPanel to take an accept list
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/FileUploadDropdown.jsx
  src/firefly/js/ui/FileUploadProcessor.jsx
  src/firefly/js/ui/FileUploadUtil.js
  src/firefly/js/ui/HiPSImageSelect.jsx
  src/firefly/js/ui/TestQueriesPanel.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Labels: enhancement

#1318 Firefly-1147: Modify upload panel to accept/allow one item
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/FileUploadDropdown.jsx
  src/firefly/js/ui/FileUploadProcessor.jsx
  src/firefly/js/ui/TestQueriesPanel.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Labels: enhancement

#1315 FIREFLY-613: remember table options selection
  package.json
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/js/tables/TableConnector.js
  src/firefly/js/tables/TablePref.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/reducer/TableUiReducer.js
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/util/BrowserCache.js
  src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
  yarn.lock
Labels: enhancement

#1317 Firefly-1142: upload from tap
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/VosiCapabilityRetrieve.java
  src/firefly/js/data/ServerParams.js
  src/firefly/js/fieldGroup/FieldGroupUtils.js
  src/firefly/js/rpc/SearchServicesJson.js
  src/firefly/js/ui/CatalogSearchMethodType.jsx
  src/firefly/js/ui/DropDownMenu.css
  src/firefly/js/ui/SuggestBoxInputField.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/UploadTableChooser.js
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/Constraints.js
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableColumnsConstraints.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapKnownServices.js
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
Labels: enhancement, UI, multi-ticket

#1322 FIREFLY-1146: Fix target field not updating when searching at selected region in image viewer
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Labels: bug

#1321 FIREFLY-1154: Update 3 color plot defaults
  src/firefly/java/edu/caltech/ipac/firefly/resources/irsa-image-master-table.csv
Labels: bug

#1320 IRSA-3143: SHA migration: Add search by Program, Campaign, Observer, and Observation Date
  src/firefly/java/edu/caltech/ipac/firefly/server/query/JsonFromExternalTask.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/JsonStringProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
  src/firefly/js/ui/TimePanel.jsx
  src/firefly/js/ui/TimeUIUtil.js
  src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
  src/firefly/js/ui/tap/TemportalSearch.jsx
  src/firefly/js/ui/tap/TimeRangePanel.jsx
Labels: enhancement

#1319 FIREFLY-1129: Support UWS job file uploads via the upload panel
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysisReport.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
  src/firefly/java/edu/caltech/ipac/firefly/util/Ref.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/js/core/background/JobInfo.jsx
  src/firefly/js/data/FileAnalysis.js
  src/firefly/js/ui/FileUploadDropdown.jsx
  src/firefly/js/ui/FileUploadProcessor.jsx
  src/firefly/js/ui/FileUploadUtil.js
  src/firefly/js/ui/TestQueriesPanel.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.css
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Labels: enhancement, UI
