Repository Caltech-IPAC/firefly, pull requests merged in 2023-12, with the labels that each got.

#1446 FIREFLY-1318: Add documentation link to DCE result table
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/MultiSpectrumProcessor.java
  src/firefly/java/edu/caltech/ipac/table/TableMeta.java
  src/firefly/js/tables/TableRequestUtil.js
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/ui/dynamic/DLGenAnalyzeSearch.js
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
Labels: enhancement

#1455 FIREFLY-1352: Implement property sheet feedback
  src/firefly/js/Firefly.js
  src/firefly/js/tables/TableConnector.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/tables/ui/PropertySheet.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
Labels: enhancement

#1456 Firefly-1350: Add MOC outline style
  src/firefly/js/Firefly.js
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/drawingLayers/HiPSMOCUI.jsx
  src/firefly/js/util/Color.js
  src/firefly/js/visualize/draw/Drawer.js
  src/firefly/js/visualize/draw/DrawingDef.js
  src/firefly/js/visualize/draw/MocObj.js
  src/firefly/js/visualize/draw/ShapeDataObj.js
Labels: enhancement, HiPS

#1452 Firefly-1235: Adding region file format to table save when position columns are available
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HttpServCommands.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/java/edu/caltech/ipac/table/io/RegionTableWriter.java
  src/firefly/js/tables/ui/TableSave.jsx
Labels: enhancement

#1457 Firefly Multi ticket: Firefly-1335,Firefly-1321,Firefly-1361
  src/firefly/js/drawingLayers/HiPSMOCUI.jsx
  src/firefly/js/ui/dynamic/ServiceDefTools.js
Labels: bug, enhancement, multi-ticket

#1460 Firefly-1357: Update image viewer and related components to JoyUI
  src/firefly/html/css/global.css
  src/firefly/js/drawingLayers/CatalogUI.jsx
  src/firefly/js/drawingLayers/HiPSMOCUI.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/fireflyviewer/ResultsPanel.jsx
  src/firefly/js/ui/ActionsDropDownButton.jsx
  src/firefly/js/ui/FireflyRoot.jsx
  src/firefly/js/ui/ImageSelect.jsx
  src/firefly/js/ui/InputFieldView.jsx
  src/firefly/js/ui/ListBoxInputField.jsx
  src/firefly/js/ui/PopupPanel.jsx
  src/firefly/js/ui/PopupUtil.jsx
  src/firefly/js/ui/RadioGroupInputFieldView.jsx
  src/firefly/js/ui/StatedInputfield.jsx
  src/firefly/js/ui/ThemeSetup.js
  src/firefly/js/ui/ToolbarButton.css
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/VersionInfo.jsx
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableColumnsConstraints.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/util/BrowserInfo.js
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/iv/ExpandedTools.css
  src/firefly/js/visualize/iv/ExpandedTools.jsx
  src/firefly/js/visualize/iv/ImageExpandedMode.jsx
  src/firefly/js/visualize/iv/ImageViewer.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.css
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/iv/ImageViewerStatus.jsx
  src/firefly/js/visualize/iv/PlotTitle.css
  src/firefly/js/visualize/iv/PlotTitle.jsx
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
  src/firefly/js/visualize/ui/FitsHeaderView.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/MagnifiedView.jsx
  src/firefly/js/visualize/ui/MouseReadPopoutAll.jsx
  src/firefly/js/visualize/ui/MouseReadout.css
  src/firefly/js/visualize/ui/MouseReadout.jsx
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
  src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx
  src/firefly/js/visualize/ui/MultiImageViewerView.jsx
  src/firefly/js/visualize/ui/MultiItemViewerView.jsx
  src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
  src/firefly/js/visualize/ui/TargetHipsPanelToolbar.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
  src/firefly/js/visualize/ui/VisInlineToolbarView.jsx
  src/firefly/js/visualize/ui/multiProduct/DPDropdown.jsx
  src/firefly/js/visualize/ui/multiProduct/MPMessages.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
Labels: UI

#1462 Firefly-1366 dialogs
  src/firefly/js/drawingLayers/ActiveTargetUI.jsx
  src/firefly/js/drawingLayers/CatalogUI.jsx
  src/firefly/js/drawingLayers/DistanceToolUI.jsx
  src/firefly/js/drawingLayers/FixedMarker.js
  src/firefly/js/drawingLayers/HiPSGridlUI.jsx
  src/firefly/js/drawingLayers/ImageRoot.js
  src/firefly/js/drawingLayers/MarkerToolUI.jsx
  src/firefly/js/drawingLayers/NorthUpCompassUI.jsx
  src/firefly/js/drawingLayers/SearchTarget.js
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/ui/ImageSelect.jsx
  src/firefly/js/ui/PopupPanel.css
  src/firefly/js/ui/PopupPanel.jsx
  src/firefly/js/ui/PopupUtil.jsx
  src/firefly/js/ui/ThemeSetup.js
  src/firefly/js/visualize/ui/DrawLayerItemView.jsx
  src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
  src/firefly/js/visualize/ui/DrawLayerUIComponents.jsx
  src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
  src/firefly/js/visualize/ui/VisInlineToolbarView.jsx
Labels: UI

#1458 FIREFLY-1358: Convert Range Slider and Version Info to JoyUI
  package-json-doc.md
  package.json
  src/firefly/js/ui/DropDownToolbarButton.jsx
  src/firefly/js/ui/FitsRotationDialog.jsx
  src/firefly/js/ui/PopupPanel.jsx
  src/firefly/js/ui/RangeSliderView.jsx
  src/firefly/js/ui/ThemeSetup.js
  src/firefly/js/ui/VersionInfo.jsx
  src/firefly/js/ui/rc-slider.css
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  yarn.lock
Labels: UI

#1465 Firefly-1367: toolbar converted to JoyUI
  src/firefly/html/css/global.css
  src/firefly/js/charts/ui/MultiChartToolbar.jsx
  src/firefly/js/charts/ui/PinnedChartContainer.jsx
  src/firefly/js/tables/ui/TablesContainer.jsx
  src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx
  src/firefly/js/ui/ActionsDropDownButton.jsx
  src/firefly/js/ui/CloseButton.jsx
  src/firefly/js/ui/CompleteButton.jsx
  src/firefly/js/ui/DropDownMenu.css
  src/firefly/js/ui/DropDownMenu.jsx
  src/firefly/js/ui/DropDownToolbarButton.jsx
  src/firefly/js/ui/FormPanel.jsx
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/ui/PopupPanel.jsx
  src/firefly/js/ui/PopupUtil.jsx
  src/firefly/js/ui/ThemeSetup.js
  src/firefly/js/ui/ToolbarButton.css
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/VersionInfo.jsx
  src/firefly/js/ui/tap/TableColumnsConstraints.jsx
  src/firefly/js/visualize/SearchRefinementTool.jsx
  src/firefly/js/visualize/iv/ExpandedTools.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
  src/firefly/js/visualize/ui/ImageCenterDropDown.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/ImagePager.jsx
  src/firefly/js/visualize/ui/ImageTableRowViewer.jsx
  src/firefly/js/visualize/ui/MaskAddPanel.jsx
  src/firefly/js/visualize/ui/MatchLockDropDown.jsx
  src/firefly/js/visualize/ui/MouseReadPopoutAll.jsx
  src/firefly/js/visualize/ui/MouseReadout.css
  src/firefly/js/visualize/ui/MouseReadout.jsx
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
  src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx
  src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
  src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx
  src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
  src/firefly/js/visualize/ui/StretchDropDownView.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
  src/firefly/js/visualize/ui/VisInlineToolbarView.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
  src/firefly/js/visualize/ui/WorldPtFormat.jsx
  src/firefly/js/visualize/ui/ZoomButton.jsx
  src/firefly/js/visualize/ui/multiProduct/DPDropdown.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx
Labels: UI, multi-ticket

#1466 Firefly 1374 color dialog and other dialogs
  src/firefly/js/charts/ui/PinnedChartContainer.jsx
  src/firefly/js/ui/ColorPicker.jsx
  src/firefly/js/ui/DialogRootContainer.jsx
  src/firefly/js/ui/DropDownMenu.jsx
  src/firefly/js/ui/DropDownToolbarButton.jsx
  src/firefly/js/ui/FieldGroup.jsx
  src/firefly/js/ui/FireflyRoot.jsx
  src/firefly/js/ui/PagingBar.jsx
  src/firefly/js/ui/PointShapeSizePicker.jsx
  src/firefly/js/ui/PopupPanel.jsx
  src/firefly/js/ui/RangeSlider.jsx
  src/firefly/js/ui/RangeSliderView.jsx
  src/firefly/js/ui/SizeInputField.jsx
  src/firefly/js/ui/TargetFeedback.jsx
  src/firefly/js/ui/ThemeSetup.js
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/visualize/SearchRefinementTool.jsx
  src/firefly/js/visualize/iv/PlotTitle.jsx
  src/firefly/js/visualize/ui/ColorBandChooserPopup.jsx
  src/firefly/js/visualize/ui/ColorBandPanel.jsx
  src/firefly/js/visualize/ui/ColorDialog.jsx
  src/firefly/js/visualize/ui/ColorPanelReducer.js
  src/firefly/js/visualize/ui/ColorRGBHuePreservingPanel.jsx
  src/firefly/js/visualize/ui/DrawLayerItemView.jsx
  src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/ImageStatsPopup.jsx
  src/firefly/js/visualize/ui/MouseReadout.css
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
  src/firefly/js/visualize/ui/PngViewer.jsx
  src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx
  src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
  src/firefly/js/visualize/ui/ThumbnailView.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
  src/firefly/js/visualize/ui/VisInlineToolbarView.jsx
  src/firefly/js/visualize/ui/multiProduct/MPMessages.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
Labels: UI
