Repository Caltech-IPAC/firefly, pull requests merged in 2023-09, with the labels that each got.

#1423 FIREFLY-1282: Add multi-results support for UWS jobs
  src/firefly/java/edu/caltech/ipac/firefly/core/background/Job.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagedEmail.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/js/core/background/JobInfo.jsx
Labels: enhancement

#1424 FIREFLY-1118: Update recenter action to allow coordinate system to be a string
  src/firefly/js/visualize/task/PlotChangeTask.js
Labels: enhancement, API

#1420 Firefly-1298: Update obscore to support related grids of images
  src/firefly/js/api/ApiUtilImage.jsx
  src/firefly/js/data/MetaConst.js
  src/firefly/js/metaConvert/AnalysisUtils.js
  src/firefly/js/metaConvert/DataLinkProcessor.js
  src/firefly/js/metaConvert/DataProductsCntlr.js
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/DataProductsType.js
  src/firefly/js/metaConvert/DataProductsWatcher.js
  src/firefly/js/metaConvert/DefaultConverter.js
  src/firefly/js/metaConvert/ImageDataProductsUtil.js
  src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
  src/firefly/js/metaConvert/ObsCoreConverter.js
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/metaConvert/ServDescConverter.js
  src/firefly/js/metaConvert/TableDataProductUtils.js
  src/firefly/js/metaConvert/UploadAndAnalysis.js
  src/firefly/js/metaConvert/missions/AtlasRequestList.js
  src/firefly/js/metaConvert/missions/ShaRequestList.js
  src/firefly/js/metaConvert/missions/TwoMassRequestList.js
  src/firefly/js/metaConvert/missions/WiseRequestList.js
  src/firefly/js/metaConvert/missions/ZtfRequestList.js
  src/firefly/js/metaConvert/vo/DataLinkProcessor.js
  src/firefly/js/metaConvert/vo/DatalinkFetch.js
  src/firefly/js/metaConvert/vo/DatalinkProducts.js
  src/firefly/js/metaConvert/vo/ObsCoreConverter.js
  src/firefly/js/metaConvert/vo/ServDescConverter.js
  src/firefly/js/metaConvert/vo/ServDescProducts.js
  src/firefly/js/metaConvert/vo/VORequest.js
  src/firefly/js/templates/fireflyslate/FireflySlateManager.js
  src/firefly/js/templates/fireflyslate/GridLayoutPanel.jsx
  src/firefly/js/ui/UploadTableChooser.js
  src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/visualize/FitsHeaderUtil.js
  src/firefly/js/visualize/PlotCompleteMonitor.js
  src/firefly/js/visualize/WebPlotRequest.js
  src/firefly/js/visualize/ui/ColorBandChooserPopup.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbar.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/MultProductViewerContainer.jsx
  src/firefly/js/visualize/ui/multiProduct/MetaDataMultiProductViewer.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
Labels: bug, enhancement, Refactor

#1429 Firefly-1311: fixed: hips tile should not be smoothed at highest resolution
  docs/release-notes.md
  src/firefly/js/visualize/HiPSUtil.js
  src/firefly/js/visualize/iv/HiPSRenderer.js
  src/firefly/js/visualize/iv/HiPSTileDrawer.js
Labels: bug

#1427 FIREFLY-1308: ROUTER template to support initArgs
  src/firefly/js/Firefly.js
  src/firefly/js/core/AppDataCntlr.js
  src/firefly/js/templates/fireflyslate/FireflySlate.jsx
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/hydra/HydraViewer.jsx
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/templates/router/RouteHelper.jsx
  src/firefly/js/templates/router/RouterEntry.jsx
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/FormPanel.jsx
  src/firefly/js/ui/Menu.jsx
Labels: enhancement

#1431 Firefly-1312,1315: hips render & Bug Fix: FITS GnomicProjection using cd matrix
  src/firefly/js/visualize/iv/HiPSRenderer.js
  src/firefly/js/visualize/iv/HiPSSingleTileRender.js
  src/firefly/js/visualize/iv/HiPSTileDrawer.js
  src/firefly/js/visualize/projection/ProjectionHeaderParser.js
Labels: bug, Image, HiPS, multi-ticket

#1432 Firefly-1313: fixed HiPS missing tiles on deep zoom
  src/firefly/js/drawingLayers/HiPSGrid.js
  src/firefly/js/visualize/HiPSUtil.js
  src/firefly/js/visualize/iv/HiPSCellFinder.js
  src/firefly/js/visualize/iv/HiPSSingleTileRender.js
  src/firefly/js/visualize/iv/HiPSTileDrawer.js
  src/firefly/js/visualize/task/PlotHipsTask.js
Labels: bug, HiPS
