Repository Caltech-IPAC/firefly, pull requests merged in 2023-05, with the labels that each got.

#1374 FIREFLY-1240: flipped y axis doesn't persist in chart thumbnail view
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/js/charts/ui/PlotlyChartArea.jsx
  src/firefly/js/tables/ui/TableRenderer.js
Labels: bug, UI

#1375 Firefly-1241: Fix: Search search showing fits in wrong viewer
  src/firefly/js/ui/DefaultSearchActions.js
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Labels: bug

#1368 FIREFLY-987 Identify tables by EXTNAME, EXTVERSION, EXTLEVEL
  src/firefly/java/edu/caltech/ipac/firefly/data/RelatedData.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/SpectralCubeEval.java
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/projection/Wavelength.js
  src/firefly/js/visualize/projection/WavelengthHeaderParser.js
  src/firefly/js/visualize/task/PlotImageTask.js
Labels: enhancement

#1376 Firefly-1243: make sure the string conversion has spaces between number
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
Labels: bug

#1379 IRSA-3356: Added validator in download dialog for SHA
  src/firefly/js/ui/DownloadDialog.jsx
Labels: enhancement

#1380 FIREFLY-1245: handle undefined pageSize
  src/firefly/html/test/tests-table.html
  src/firefly/js/drawingLayers/Artifact.js
  src/firefly/js/tables/TableConnector.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/tables/__tests__/TableUtil-test.js
Labels: bug, Table

#1381 Firefly-1246: Fixed: obs_title not showing up for datalink. wavelength wrong my order of magnitude
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/URLFileRetriever.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/drawingLayers/SearchSelectTool.js
  src/firefly/js/metaConvert/DataLinkProcessor.js
  src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
  src/firefly/js/metaConvert/ObsCoreConverter.js
  src/firefly/js/metaConvert/ServDescConverter.js
  src/firefly/js/util/VOAnalyzer.js
  src/firefly/js/visualize/draw/PointDataObj.js
  src/firefly/js/visualize/ui/multiProduct/MPMessages.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
Labels: bug

#1384 Firefly-1247: fix GPU.js to create window.GPUX to no longer class with chrome GPU
  src/firefly/html/gpu-browser.min-2.15.0-FIX-GPUX.js
  src/firefly/js/visualize/rawData/GpuJsConfig.js
Labels: bug

#1385 Firefly-1234: Convert all non EQJ2000 coords to EQJ2000 coords
  src/firefly/js/ui/PositionFieldDef.js
Labels: enhancement

#1386 Firefly-1248 bugs
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/SDSSQuery.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsExtract.java
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
Labels: bug
