Repository Caltech-IPAC/firefly, pull requests merged in 2024-01, with the labels that each got.

#1468 FIREFLY-1355: Convert TabPanel to Joy UI
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/tables/ui/TablesContainer.jsx
  src/firefly/js/ui/DialogRootContainer.jsx
  src/firefly/js/ui/MultiSearchPanel.jsx
  src/firefly/js/ui/PagingBar.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
Labels: UI

#1469 Firefly-1381: JoyUI: converrt small components and clean up
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/ui/CatalogSearchMethodType.jsx
  src/firefly/js/ui/CheckboxGroupInputField.jsx
  src/firefly/js/ui/CompleteButton.jsx
  src/firefly/js/ui/FormPanel.jsx
  src/firefly/js/ui/HiPSImageSelect.jsx
  src/firefly/js/ui/ImageSelect.css
  src/firefly/js/ui/ImageSelect.jsx
  src/firefly/js/ui/ListBoxInputField.jsx
  src/firefly/js/ui/MultiSearchPanel.jsx
  src/firefly/js/ui/NedSearchPanel.jsx
  src/firefly/js/ui/PopupPanel.jsx
  src/firefly/js/ui/RadioGroupInputFieldView.jsx
  src/firefly/js/ui/ThemeSetup.js
  src/firefly/js/ui/VoSearchPanel.css
  src/firefly/js/ui/VoSearchPanel.jsx
  src/firefly/js/ui/panel/AccordionPanel.jsx
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/Select.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableColumnsConstraints.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.css
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/visualize/iv/ExpandedTools.jsx
  src/firefly/js/visualize/iv/PlotTitle.css
  src/firefly/js/visualize/iv/PlotTitle.jsx
  src/firefly/js/visualize/region/RegionFileUploadView.jsx
  src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
  src/firefly/js/visualize/ui/CatalogSelectViewPanel.css
  src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
  src/firefly/js/visualize/ui/CatalogTableListField.css
  src/firefly/js/visualize/ui/CatalogTableListField.jsx
  src/firefly/js/visualize/ui/DrawLayerItemView.jsx
  src/firefly/js/visualize/ui/DrawLayerUIComponents.jsx
  src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
  src/firefly/js/visualize/ui/ExtraIpacSearches.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.css
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/MouseReadout.css
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
  src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
  src/firefly/js/visualize/ui/VisInlineToolbarView.jsx
  src/firefly/js/visualize/ui/WorkspaceViewPanel.jsx
Labels: UI

#1474 Firefly-1384: file upload to Joy UI
  src/firefly/html/css/global.css
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/ui/DropDownMenu.jsx
  src/firefly/js/ui/FileUpload.jsx
  src/firefly/js/ui/FileUploadDropdown.jsx
  src/firefly/js/ui/FormPanel.jsx
  src/firefly/js/ui/InputFieldView.jsx
  src/firefly/js/ui/TestSearchPanel.jsx
  src/firefly/js/ui/ThemeSetup.js
  src/firefly/js/ui/UploadOptionsDialog.jsx
  src/firefly/js/ui/UploadTableChooser.js
  src/firefly/js/visualize/iv/ExpandedTools.jsx
  src/firefly/js/visualize/region/RegionFileUploadView.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.css
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/MaskAddPanel.jsx
  src/firefly/js/visualize/ui/MouseReadout.css
  src/firefly/js/visualize/ui/MouseReadout.jsx
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
Labels: UI

#1475 FIREFLY-1387: UI Conversion: Additional core functionalities
  src/firefly/html/firefly.html
  src/firefly/js/Firefly.js
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/ui/FireflyRoot.jsx
  src/firefly/js/ui/Menu.css
  src/firefly/js/ui/PagingBar.jsx
  src/firefly/js/ui/ThemeSetup.js
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
Labels: enhancement

#1477 Firefly-1391: convert miscellaneous components to JoyUI
  src/firefly/html/css/global.css
  src/firefly/js/charts/ui/PinnedChartContainer.jsx
  src/firefly/js/drawingLayers/ActiveTargetUI.jsx
  src/firefly/js/drawingLayers/CatalogUI.jsx
  src/firefly/js/drawingLayers/FixedMarker.js
  src/firefly/js/drawingLayers/FixedPtControl.jsx
  src/firefly/js/drawingLayers/FootprintToolUI.jsx
  src/firefly/js/drawingLayers/HiPSMOCUI.jsx
  src/firefly/js/drawingLayers/ImageLineFootPrintUI.jsx
  src/firefly/js/drawingLayers/MarkerToolUI.jsx
  src/firefly/js/drawingLayers/SearchTarget.js
  src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
  src/firefly/js/tables/ui/ObjectTree.jsx
  src/firefly/js/templates/common/FireflyLayout.jsx
  src/firefly/js/templates/common/MainPanel.jsx
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/templates/hydra/HydraViewer.jsx
  src/firefly/js/ui/ActionsDropDownButton.jsx
  src/firefly/js/ui/DropDownMenu.jsx
  src/firefly/js/ui/HelpIcon.css
  src/firefly/js/ui/HelpIcon.jsx
  src/firefly/js/ui/ImageSelect.jsx
  src/firefly/js/ui/ModalDialog.css
  src/firefly/js/ui/ModalDialog.jsx
  src/firefly/js/ui/PopupPanel.jsx
  src/firefly/js/ui/SizeInputField.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/TimePanel.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/VersionInfo.jsx
  src/firefly/js/ui/WebApiHelpInfoPage.css
  src/firefly/js/ui/WebApiHelpInfoPage.jsx
  src/firefly/js/ui/ZoomOptionsPopup.jsx
  src/firefly/js/ui/panel/AccordionPanel.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TemporalSearch.jsx
  src/firefly/js/ui/tap/TimeRangePanel.jsx
  src/firefly/js/ui/tap/WavelengthPanel.jsx
  src/firefly/js/visualize/SearchRefinementTool.jsx
  src/firefly/js/visualize/region/RegionFileUploadView.jsx
  src/firefly/js/visualize/ui/ColorBandPanel.jsx
  src/firefly/js/visualize/ui/ColorRGBHuePreservingPanel.jsx
  src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
  src/firefly/js/visualize/ui/MouseReadout.jsx
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
  src/firefly/js/visualize/ui/TargetHipsPanelToolbar.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
  src/firefly/js/visualize/ui/WorldPtFormat.jsx
Labels: UI

#1478 FIREFLY-1376: Convert textarea to JoyUI
  docs/ui-notes.md
  src/firefly/js/tables/ui/FilterEditor.jsx
  src/firefly/js/ui/CatalogSearchMethodType.css
  src/firefly/js/ui/CatalogSearchMethodType.jsx
  src/firefly/js/ui/InputAreaField.jsx
  src/firefly/js/ui/InputAreaFieldView.css
  src/firefly/js/ui/InputAreaFieldView.jsx
  src/firefly/js/ui/InputFieldView.jsx
  src/firefly/js/ui/ThemeSetup.js
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/visualize/SearchRefinementTool.jsx
  src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
  src/firefly/js/visualize/ui/CatalogSelectViewPanel.css
  src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
Labels: UI

#1479 Firelfy-1385: convert advance adql panel and other stuff
  package.json
  src/firefly/html/images/popout-arrow_12x12.png
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/ui/ActionsDropDownButton.jsx
  src/firefly/js/ui/CloseButton.jsx
  src/firefly/js/ui/DropDownToolbarButton.jsx
  src/firefly/js/ui/FileUpload.jsx
  src/firefly/js/ui/HelpIcon.jsx
  src/firefly/js/ui/ListBoxInputField.jsx
  src/firefly/js/ui/MultiSearchPanel.jsx
  src/firefly/js/ui/PagingBar.jsx
  src/firefly/js/ui/SizeInputField.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/ThemeSetup.js
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/UploadTableChooser.js
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.css
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.css
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
  src/firefly/js/ui/panel/AccordionPanel.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.css
  src/firefly/js/ui/tap/WavelengthPanel.jsx
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/iv/ExpandedTools.jsx
  src/firefly/js/visualize/iv/HiPSTileDrawer.js
  src/firefly/js/visualize/iv/ImageRender.jsx
  src/firefly/js/visualize/iv/ImageTileDrawer.js
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/ui/Buttons.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/ImageCenterDropDown.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/MatchLockDropDown.jsx
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
  yarn.lock
Labels: UI

#1482 FIREFLY-1395: Firefly layout UI conversion
  src/firefly/html/css/global.css
  src/firefly/html/firefly-dev.html
  src/firefly/html/firefly.html
  src/firefly/html/hydra.html
  src/firefly/html/slate.html
  src/firefly/html/ts.html
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/templates/common/FireflyLayout.jsx
  src/firefly/js/templates/common/MainPanel.jsx
  src/firefly/js/templates/fireflyslate/FireflySlate.jsx
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/hydra/HydraViewer.jsx
  src/firefly/js/ui/App.jsx
  src/firefly/js/ui/AppInitLoadingMessage.jsx
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/FireflyRoot.jsx
  src/firefly/js/ui/ImageSelect.css
  src/firefly/js/ui/ImageSelect.jsx
  src/firefly/js/ui/IrsaFooter.jsx
  src/firefly/js/ui/Menu.css
  src/firefly/js/ui/SearchPanel.jsx
  src/firefly/js/ui/VersionInfo.jsx
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/panel/CollapsiblePanel.jsx
  src/firefly/js/ui/panel/DockLayoutPanel.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Labels: enhancement, UI

#1481 FIREFLY-1397: some js api conversion to Joy UI
  src/firefly/js/api/ApiExpandedView.jsx
  src/firefly/js/api/ApiHighlevelBuild.js
  src/firefly/js/ui/DropDownMenu.jsx
  src/firefly/js/ui/DropDownToolbarButton.jsx
  src/firefly/js/ui/FileUpload.jsx
  src/firefly/js/ui/FileUploadDropdown.jsx
  src/firefly/js/ui/ImageSelect.jsx
  src/firefly/js/ui/TargetFeedback.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/ui/ApiExpandedDisplay.jsx
  src/firefly/js/visualize/ui/ApiFullImageDisplay.jsx
  src/firefly/js/visualize/ui/ApiToolbarImageDisplay.jsx
  src/firefly/js/visualize/ui/Buttons.jsx
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/FitsHeaderView.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/MatchLockDropDown.jsx
  src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
  src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
Labels: UI

#1480 Firefly 1392: Convert BackgroundMonitor and a few other components to JoyUI
  docs/ui-notes.md
  src/firefly/js/core/background/BackgroundMonitor.css
  src/firefly/js/core/background/BackgroundMonitor.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/ui/DownloadDialog.jsx
  src/firefly/js/ui/PopupPanel.jsx
  src/firefly/js/ui/WorkspaceSelectPane.jsx
Labels: UI

#1485 FIREFLY-1386: Convert chart options panel to joy UI
  src/firefly/js/charts/ui/ChartSelectPanel.jsx
  src/firefly/js/charts/ui/ColumnOrExpression.jsx
  src/firefly/js/charts/ui/CombineChart.jsx
  src/firefly/js/charts/ui/HistogramOptions.jsx
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
  src/firefly/js/charts/ui/options/BasicOptions.jsx
  src/firefly/js/charts/ui/options/Errors.jsx
  src/firefly/js/charts/ui/options/FireflyHistogramOptions.jsx
  src/firefly/js/charts/ui/options/HeatmapOptions.jsx
  src/firefly/js/charts/ui/options/NewTracePanel.jsx
  src/firefly/js/charts/ui/options/PlotlyHistogramOptions.jsx
  src/firefly/js/charts/ui/options/ScatterOptions.jsx
  src/firefly/js/charts/ui/options/SpectrumOptions.jsx
  src/firefly/js/ui/CheckboxGroupInputField.jsx
  src/firefly/js/ui/FormPanel.jsx
  src/firefly/js/ui/ListBoxInputField.jsx
  src/firefly/js/ui/SuggestBoxInputField.jsx
Labels: UI

#1486 FIREFLY-1394: Convert Chart and related components to JoyUI.
  src/firefly/js/charts/ui/ChartPanel.css
  src/firefly/js/charts/ui/ChartPanel.jsx
  src/firefly/js/charts/ui/CombineChart.jsx
  src/firefly/js/charts/ui/FilterEditorWrapper.jsx
  src/firefly/js/charts/ui/MultiChartToolbar.jsx
  src/firefly/js/charts/ui/MultiChartViewer.jsx
  src/firefly/js/charts/ui/PinnedChartContainer.jsx
  src/firefly/js/charts/ui/PlotlyChartArea.jsx
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
  src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/ui/FireflyRoot.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/panel/CollapsiblePanel.jsx
  src/firefly/js/visualize/ui/Buttons.jsx
Labels: enhancement, UI
