Repository Caltech-IPAC/firefly, pull requests merged in 2024-06, with the labels that each got.

#1566 Irsa 5500 fix missing artifacts layer on wise scanid search result
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/IbeFileRetrieve.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ibe/IbeQueryArtifact.java
  src/firefly/js/metaConvert/missions/WiseRequestList.js
Labels: Image

#1567 FIREFLY-1485: Clean up dark mode
  src/firefly/html/css/global.css
  src/firefly/js/charts/ChartUtil.js
  src/firefly/js/charts/ui/PlotlyChartArea.jsx
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TablePanel.jsx
Labels: enhancement, UI

#1569 Firefly-1495: sd parsing and extraction fixes
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
  src/firefly/java/edu/caltech/ipac/firefly/data/table/MetaConst.java
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsExtract.java
  src/firefly/js/data/MetaConst.js
  src/firefly/js/metaConvert/AnalysisUtils.js
  src/firefly/js/metaConvert/DataProductsCntlr.js
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/metaConvert/TableDataProductUtils.js
  src/firefly/js/metaConvert/UploadAndAnalysis.js
  src/firefly/js/metaConvert/vo/DataLinkProcessor.js
  src/firefly/js/metaConvert/vo/DatalinkProducts.js
  src/firefly/js/metaConvert/vo/ObsCoreConverter.js
  src/firefly/js/metaConvert/vo/ServDescConverter.js
  src/firefly/js/metaConvert/vo/VORequest.js
  src/firefly/js/ui/ColorPicker.jsx
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/ui/Buttons.jsx
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
  src/firefly/js/visualize/ui/multiProduct/DPDropdown.jsx
  src/firefly/js/voAnalyzer/TableAnalysis.js
  src/firefly/js/voAnalyzer/VoConst.js
  src/firefly/js/voAnalyzer/VoDataLinkServDef.js
  src/firefly/js/voAnalyzer/VoTableRecognizer.js
Labels: bug

#1570 Firefly-1498: fixed: polygon does not default on first click
  src/firefly/js/core/background/BackgroundMonitor.jsx
  src/firefly/js/drawingLayers/SearchSelectTool.js
  src/firefly/js/ui/DownloadDialog.jsx
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: bug

#1572 Firefly-1500,1501: Fixes multiple tickets
  src/firefly/js/drawingLayers/ExtractLineTool.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/visualize/iv/PlotTitle.jsx
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Labels: bug, multi-ticket

#1575 IRSA-6134: Fix blinking "choose tab" hint in finder chart and other apps
  src/firefly/js/core/core-typedefs.jsdoc
  src/firefly/js/templates/common/FireflyLayout.jsx
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/fireflyviewer/LandingPage.jsx
  src/firefly/js/templates/hydra/HydraViewer.jsx
Labels: bug

#1574 Firefly 1494 column reset
  src/firefly/html/css/global.css
  src/firefly/js/charts/ui/PlotlyWrapper.jsx
  src/firefly/js/core/ComponentCntlr.js
  src/firefly/js/core/background/BackgroundCntlr.js
  src/firefly/js/core/background/BackgroundMonitor.css
  src/firefly/js/core/background/BackgroundMonitor.jsx
  src/firefly/js/core/background/BgMaskPanel.jsx
  src/firefly/js/core/background/JobInfo.jsx
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/ui/DownloadDialog.jsx
  src/firefly/js/ui/FileUploadDropdown.jsx
  src/firefly/js/ui/ThemeSetup.js
  src/firefly/js/ui/WorkspaceDropdown.jsx
  src/firefly/js/ui/WorkspaceSelectPane.jsx
  src/firefly/js/ui/WorkspaceViewer.jsx
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/panel/MaskPanel.jsx
  src/firefly/js/ui/tap/ObjectIDSearch.jsx
  src/firefly/js/ui/tap/TapViewType.jsx
  src/firefly/js/visualize/iv/ImageViewerStatus.jsx
  src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
  src/firefly/js/visualize/ui/ColorBandPanel.jsx
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/IrsaCatalogSearch.jsx
Labels: bug, multi-ticket

#1576 Firefly-1506: Update buttons to material icons
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
Labels: bug, UI

#1578 Firefly-1505: Euclid issues
  src/firefly/js/metaConvert/vo/DataLinkProcessor.js
  src/firefly/js/visualize/draw/ShapeDataObj.js
  src/firefly/js/visualize/saga/ActiveRowCenterWatcher.js
  src/firefly/js/visualize/ui/ColorBandChooserPopup.jsx
Labels: bug

#1573 FIREFLY-1497: Remove CSS files post JoyUI
  src/firefly/js/api/ApiBuild.js
  src/firefly/js/api/ApiStyle.css
  src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/PropertySheet.jsx
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/ui/Banner.css
  src/firefly/js/ui/DropDownContainer.css
  src/firefly/js/ui/ImageSelect.css
  src/firefly/js/ui/ImageSelect.jsx
  src/firefly/js/ui/LinkButton.css
  src/firefly/js/ui/ModalDialog.css
  src/firefly/js/ui/ModalDialog.jsx
  src/firefly/js/ui/PointerPopup.css
  src/firefly/js/ui/PopupUtil.jsx
  src/firefly/js/ui/ProgressBar.css
  src/firefly/js/ui/VersionInfo.css
  src/firefly/js/ui/VersionInfo.jsx
  src/firefly/js/ui/WebApiHelpInfoPage.css
  src/firefly/js/ui/WebApiHelpInfoPage.jsx
  src/firefly/js/ui/dynamic/DynamicUI.css
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/panel/AccordionPanel.jsx
  src/firefly/js/ui/panel/CollapsiblePanel.css
  src/firefly/js/ui/panel/CollapsiblePanel.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.css
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapViewType.jsx
  src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
  src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
  src/firefly/js/visualize/ui/ImageTableRowViewer.css
  src/firefly/js/visualize/ui/ImageTableRowViewer.jsx
  src/firefly/js/visualize/ui/MouseReadPopoutAll.jsx
  src/firefly/js/visualize/ui/MouseReadout.css
  src/firefly/js/visualize/ui/MouseReadout.jsx
Labels: Refactor

#1579 FIREFLY-1504: Update plotly to latest version
  src/firefly/html/plotly-2.14.0.min.js
  src/firefly/html/plotly-2.32.0.min.js
  src/firefly/js/charts/PlotlyConfig.js
Labels: dependencies, Charts
