Repository Caltech-IPAC/firefly, pull requests merged in 2024-07, with the labels that each got.

#1581 Firefly-1503: Update eslint, node and other dependencies
  .eslint-strict.json
  .eslintrc
  README.md
  docker/Dockerfile
  eslint.config.mjs
  package.json
  yarn.lock
Labels: enhancement, dependencies, Infrastructure

#1580 Firefly-1491: add cutout support to data product viewer
  src/firefly/js/core/ComponentCntlr.js
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/DataProductsType.js
  src/firefly/js/metaConvert/ImageDataProductsUtil.js
  src/firefly/js/metaConvert/vo/DataLinkProcessor.js
  src/firefly/js/metaConvert/vo/DatalinkProducts.js
  src/firefly/js/metaConvert/vo/ServDescProducts.js
  src/firefly/js/ui/CutoutSizeDialog.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/visualize/projection/ProjectionHeaderParser.js
  src/firefly/js/visualize/ui/ImageMetaDataToolbar.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/multiProduct/MetaDataMultiProductViewer.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx
  src/firefly/js/voAnalyzer/VoConst.js
  src/firefly/js/voAnalyzer/VoDataLinkServDef.js
Labels: UI

#1583 Firelfy-1490: TAP catalogs can now be locked to a schema
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
  src/firefly/js/metaConvert/vo/DataLinkProcessor.js
  src/firefly/js/metaConvert/vo/DatalinkProducts.js
  src/firefly/js/templates/router/RoutedApp.jsx
  src/firefly/js/ui/FileUploadProcessor.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapViewType.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/voAnalyzer/VoDataLinkServDef.js
Labels: UI

#1585 Firefly-1512: Update nom.tam.fits to 1.20.0
  buildScript/dependencies.gradle
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/ModFileWriter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/FitsEvaluation.java
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
  src/firefly/java/edu/caltech/ipac/util/FitsHDUUtil.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsExtract.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsRead.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadFactory.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FlipXY.java
Labels: Image

#1589 Firefly-1514: fixed: popup not closing until second click
  src/firefly/js/ui/PopupPanel.jsx
Labels: bug

#1588 Firefly-1515: fix deprecations to prepare for react 19
  src/firefly/js/charts/ui/ChartPanel.jsx
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablesContainer.jsx
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/hydra/HydraViewer.jsx
  src/firefly/js/templates/lightcurve/LcImageViewerContainer.jsx
  src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/ui/AutoCompleteInput.jsx
  src/firefly/js/ui/ChartSelectDropdown.jsx
  src/firefly/js/ui/DownloadDialog.jsx
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/FileUpload.jsx
  src/firefly/js/ui/InputAreaField.jsx
  src/firefly/js/ui/InputField.jsx
  src/firefly/js/ui/InputFieldView.jsx
  src/firefly/js/ui/PagingBar.jsx
  src/firefly/js/ui/SizeInputField.jsx
  src/firefly/js/ui/SuggestBoxInputField.jsx
  src/firefly/js/ui/WorkspaceViewer.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
Labels: Infrastructure

#1584 Firefly-1507: Adding search radius to multi object uploads
  src/firefly/js/ui/UploadTableSelectorPosCol.jsx
  src/firefly/js/ui/UploadTableSelectorSingleCol.jsx
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/ui/tap/ObjectIDSearch.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
Labels: enhancement

#1591 FIREFLY-1517: use SQL to create decimate data
  compose.yml
  docker/launchTomcat.sh
  src/firefly/java/edu/caltech/ipac/firefly/data/DecimateInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbInstance.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbMonitor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/spring/JdbcFactory.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/DecimationProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
  src/firefly/java/edu/caltech/ipac/util/StringUtils.java
  src/firefly/java/edu/caltech/ipac/util/decimate/DecimateKey.java
  src/firefly/test/edu/caltech/ipac/table/EmbeddedDbUtilTest.java
Labels: Table

#1594 FIREFLY-1519: add logic to pick up table title from table_ui table space
  src/firefly/html/test/tests-table.html
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
  src/firefly/js/tables/reducer/TableUiReducer.js
  src/firefly/js/tables/ui/FilterEditor.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablesContainer.jsx
Labels: Table, UI

#1590 FIREFLY-1509: Polish dark mode for ADQL entry screen
  buildScript/webpack.config.js
  src/firefly/js/externalSource/prismLive/prism-sql.js
  src/firefly/js/externalSource/prismLive/prism.css
  src/firefly/js/ui/CssStrThemeWrapper.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
Labels: enhancement, UI

#1596 FIREFLY-1519: fix table tab switcher not showing table title as a string
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/tables/ui/TablesContainer.jsx
Labels: bug

#1593 Firefly-1520: refactor VisUtil
  src/firefly/js/drawingLayers/Catalog.js
  src/firefly/js/drawingLayers/ComputeWebGridData.js
  src/firefly/js/drawingLayers/DistanceTool.js
  src/firefly/js/drawingLayers/ExtractLineTool.js
  src/firefly/js/drawingLayers/FixedPtControl.jsx
  src/firefly/js/drawingLayers/HiPSGrid.js
  src/firefly/js/drawingLayers/ImageLineBasedFootprint.js
  src/firefly/js/drawingLayers/NorthUpCompass.js
  src/firefly/js/drawingLayers/WebGrid.js
  src/firefly/js/ui/FitsRotationDialog.jsx
  src/firefly/js/ui/PositionFieldDef.js
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/util/ObsCoreSRegionParser.js
  src/firefly/js/visualize/CsysConverter.js
  src/firefly/js/visualize/HiPSUtil.js
  src/firefly/js/visualize/ImageBoundsData.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/WebPlotAnalysis.js
  src/firefly/js/visualize/draw/DirectionArrowDrawObj.js
  src/firefly/js/visualize/draw/FootprintFactory.js
  src/firefly/js/visualize/draw/MocObj.js
  src/firefly/js/visualize/draw/PointDataObj.js
  src/firefly/js/visualize/draw/SelectBox.js
  src/firefly/js/visualize/draw/ShapeDataObj.js
  src/firefly/js/visualize/draw/ShapeHighlight.js
  src/firefly/js/visualize/projection/Projection.js
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/reducer/HandlePlotCreation.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/saga/ActiveRowCenterWatcher.js
  src/firefly/js/visualize/task/CreateTaskUtil.js
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/task/WcsMatchTask.js
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
  src/firefly/js/visualize/ui/ThumbnailView.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: Image

#1595 FIREFLY-1516: The chart is not recognizing short as a numeric type
  src/firefly/js/tables/TableUtil.js
Labels: Charts

#1597 Support datalink tables as a primary product type
  src/firefly/js/metaConvert/AnalysisUtils.js
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/DataProductsWatcher.js
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/metaConvert/UploadAndAnalysis.js
  src/firefly/js/metaConvert/vo/DataLinkProcessor.js
  src/firefly/js/metaConvert/vo/DataLinkStandAloneConverter.js
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/voAnalyzer/TableAnalysis.js
  src/firefly/js/voAnalyzer/VoConst.js
  src/firefly/js/voAnalyzer/VoDataLinkServDef.js
Labels: enhancement
