Repository Caltech-IPAC/firefly, pull requests merged in 2024-09, with the labels that each got.

#1614 FIREFLY-1521: a few chart related bugs
  src/firefly/js/charts/ChartUtil.js
  src/firefly/js/charts/TableStatsCntlr.js
  src/firefly/js/charts/ui/ChartSelectPanel.jsx
  src/firefly/js/charts/ui/CombineChart.jsx
  src/firefly/js/charts/ui/options/BasicOptions.jsx
  src/firefly/js/charts/ui/options/FireflyHistogramOptions.jsx
  src/firefly/js/charts/ui/options/HeatmapOptions.jsx
  src/firefly/js/charts/ui/options/ScatterOptions.jsx
  src/firefly/js/charts/ui/options/SpectrumOptions.jsx
Labels: bug, Charts

#1610 IRSA-6308: pass along credential to IRSA backend services
  src/firefly/java/edu/caltech/ipac/firefly/server/security/JOSSOAdapter.java
Labels: enhancement

#1611 IRSA-6308: add logic to pass along basic-auth credential to IRSA backend services
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
  src/firefly/java/edu/caltech/ipac/firefly/server/security/JOSSOAdapter.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
Labels: enhancement

#1616 Firefly-1524: refactor EmbeddedPositionSearchPanel.jsx
  src/firefly/js/ui/TestQueriesPanel.jsx
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/DLuiRootSearchPanel.jsx
  src/firefly/js/ui/dynamic/DLuiServDescPanel.jsx
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/visualize/saga/CatalogWatcher.js
Labels: Refactor

#1615 Firelfy-1551: hpx feedback
  package.json
  src/firefly/js/charts/ChartUtil.js
  src/firefly/js/charts/ui/HistogramOptions.jsx
  src/firefly/js/drawingLayers/CatalogUI.jsx
  src/firefly/js/drawingLayers/hpx/HpxCatalog.js
  src/firefly/js/drawingLayers/hpx/HpxCatalogUtil.js
  src/firefly/js/drawingLayers/hpx/HpxDraw.js
  src/firefly/js/drawingLayers/hpx/TileDataMaker.jsx
  src/firefly/js/tables/HpxIndexCntlr.js
  src/firefly/js/ui/RadioGroupInputField.jsx
  src/firefly/js/ui/RadioGroupInputFieldView.jsx
  src/firefly/js/util/Color.js
  src/firefly/js/visualize/HiPSUtil.js
  src/firefly/js/visualize/draw/DrawUtil.js
  src/firefly/js/visualize/draw/FootprintObj.js
  src/firefly/js/visualize/draw/PointDataObj.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/ui/DrawLayerItemView.jsx
  yarn.lock
Labels: enhancement

#1617 FIREFLY-1548 fix-irsa-app-search-cleanup-issue
  src/firefly/js/core/AppDataCntlr.js
  src/firefly/js/templates/hydra/HydraManager.js
  src/firefly/js/ui/Menu.jsx
Labels: bug

#1618 Firefly 1533 runid jobname
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/network/IpacTableHandler.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/js/core/background/JobInfo.jsx
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/ui/PopupPanel.jsx
  src/firefly/js/ui/tap/TapKnownServices.js
Labels: Table

#1619 IRSA-6331: change logic to convert VOTable's description into IPAC table comments
  src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
  src/firefly/java/edu/caltech/ipac/table/TableMeta.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableWriter.java
  src/firefly/java/edu/caltech/ipac/util/StringUtils.java
  src/firefly/js/tables/ui/TableInfo.jsx
Labels: bug

#1620 FIREFLY-1556: clean up of wrapperStyle, labelWidth, and inline
  src/firefly/js/charts/ui/options/BasicOptions.jsx
  src/firefly/js/charts/ui/options/ScatterOptions.jsx
  src/firefly/js/drawingLayers/HiPSGridlUI.jsx
  src/firefly/js/templates/hydra/SampleHydra.jsx
  src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/ui/CatalogSearchMethodType.jsx
  src/firefly/js/ui/DialogRootContainer.jsx
  src/firefly/js/ui/DownloadDialog.jsx
  src/firefly/js/ui/HiPSImageSelect.jsx
  src/firefly/js/ui/ImageSelect.jsx
  src/firefly/js/ui/InputField.jsx
  src/firefly/js/ui/InputFieldView.jsx
  src/firefly/js/ui/ListBoxInputField.jsx
  src/firefly/js/ui/NedSearchPanel.jsx
  src/firefly/js/ui/RangeSlider.jsx
  src/firefly/js/ui/ScriptDownloadDialog.jsx
  src/firefly/js/ui/StatedInputfield.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/TestSearchPanel.jsx
  src/firefly/js/ui/UploadOptionsDialog.jsx
  src/firefly/js/ui/VoSearchPanel.jsx
  src/firefly/js/ui/dynamic/DLuiServDescPanel.jsx
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicDef.js
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/WavelengthPanel.jsx
  src/firefly/js/visualize/SearchRefinementTool.jsx
  src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
  src/firefly/js/visualize/ui/ColorBandChooserPopup.jsx
  src/firefly/js/visualize/ui/ColorBandPanel.jsx
  src/firefly/js/visualize/ui/ColorDialog.jsx
  src/firefly/js/visualize/ui/ColorRGBHuePreservingPanel.jsx
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/ImageCenterDropDown.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/MaskAddPanel.jsx
  src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx
  src/firefly/js/visualize/ui/MultiImageViewerView.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx
Labels: Refactor

#1621 FIREFLY-1552: IpacTableFromSource processor unnecessarily re-fetches data
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbMonitor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
  src/firefly/test/edu/caltech/ipac/table/DuckDbAdapterTest.java
Labels: Table

#1622 Firefly-1541: web api 'hipsPanel' url can setup hips services and load multiple hips
  src/firefly/js/api/webApiCommands/ImageCommands.js
Labels: enhancement, HiPS

#1624 FIREFLY-1553: Upload table chooser popup UI bug fixes
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Labels: bug

#1623 Firelfy-1558: Save user add TAP servers as a preference and show it in the list.
  src/firefly/html/test/test-hips-mocs.html
  src/firefly/java/edu/caltech/ipac/firefly/server/Counters.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/VosiCapabilityRetrieve.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/drawingLayers/WebGrid.js
  src/firefly/js/drawingLayers/hpx/HpxCatalog.js
  src/firefly/js/tables/HpxIndexCntlr.js
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/ui/tap/TapViewType.jsx
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
Labels: enhancement, TAP

#1628 FIREFLY-1559: Upgrade Java from version 17 to 21
  README.md
  buildScript/app.gincl
  buildScript/dependencies.gradle
  buildScript/tasks.gincl
  docker/Dockerfile
  src/firefly/build.gradle
Labels: Infrastructure

#1632 FIREFLY-1535: Chart fix for reversal of axes bug
  src/firefly/js/charts/ui/PlotlyWrapper.jsx
Labels: bug

#1627 Firefly-1180: improve table from fits image HDU uploads
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/server/SrvParam.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ExtractFromImage.java
  src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
  src/firefly/java/edu/caltech/ipac/table/io/FITSExtractToTable.java
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsExtract.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
  src/firefly/js/Firefly.js
  src/firefly/js/data/ServerParams.js
  src/firefly/js/drawingLayers/ExtractLineTool.js
  src/firefly/js/rpc/PlotServicesJson.js
  src/firefly/js/ui/FileUploadProcessor.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/tap/TapKnownServices.js
  src/firefly/js/visualize/FitsHeaderUtil.js
  src/firefly/js/visualize/projection/ProjectionHeaderParser.js
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/ui/Buttons.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
  src/firefly/js/visualize/ui/extraction/ExtractionChart.jsx
  src/firefly/js/visualize/ui/extraction/ExtractionDialog.jsx
  src/firefly/js/visualize/ui/extraction/ExtractionTable.jsx
Labels: enhancement, Image, Table, multi-ticket
