Repository Caltech-IPAC/firefly, pull requests merged in 2024-10, with the labels that each got.

#1634 FIREFLY-1562: scrollbar appears when there are more tabs than can fit within the available space
  src/firefly/js/ui/panel/TabPanel.jsx
Labels: bug

#1633 FIREFLY-1550: Save table in Parquet format
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/H2DbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/HsqlDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/SqliteDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/DecimationProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ResourceProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SharedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
  src/firefly/java/edu/caltech/ipac/table/DataType.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/java/edu/caltech/ipac/table/io/DataGroupStarTable.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/java/edu/caltech/ipac/util/StringUtils.java
  src/firefly/js/tables/ui/TableSave.jsx
  src/firefly/test/edu/caltech/ipac/table/DuckDbAdapterTest.java
  src/firefly/test/edu/caltech/ipac/table/EmbeddedDbUtilTest.java
Labels: enhancement, Table, Refactor

#1635 Firefly-1564: fix some bug found durring testing
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/SpectralCubeEval.java
  src/firefly/js/drawingLayers/WebGridUI.jsx
  src/firefly/js/metaConvert/DataProductsType.js
  src/firefly/js/metaConvert/vo/ObsCoreConverter.js
  src/firefly/js/metaConvert/vo/ServDescProducts.js
  src/firefly/js/ui/CutoutSizeDialog.jsx
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
  src/firefly/js/ui/tap/TapViewType.jsx
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbar.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx
  src/firefly/js/voAnalyzer/VoConst.js
Labels: bug

#1639 Firefly-1570: fix 7(41),10,17
  docs/next-release-details.md
  src/firefly/java/edu/caltech/ipac/visualize/plot/Histogram.java
  src/firefly/js/drawingLayers/ExtractLineTool.js
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/metaConvert/UploadAndAnalysis.js
  src/firefly/js/ui/InputFieldView.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/ui/extraction/ExtractionDialog.jsx
  src/firefly/js/visualize/ui/multiProduct/MPMessages.jsx
Labels: bug

#1636 FIREFLY-1534: Check for utype in the table's resources if one does not exist in the table.
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/voAnalyzer/SpectrumDM.js
Labels: Charts

#1638 FIREFLY-1567: Fix upload popup style for HiPS MOC dialog
  src/firefly/js/ui/HiPSImageSelect.jsx
Labels: bug

#1642 Firefly-1571: support image sub-highlighting
  src/firefly/js/api/ApiBuild.js
  src/firefly/js/metaConvert/AnalysisUtils.js
  src/firefly/js/metaConvert/ImageDataProductsUtil.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/MultiViewCntlr.js
  src/firefly/js/visualize/PlotAttribute.js
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/saga/ActiveRowToImageWatcher.js
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/task/PlotHipsTask.js
Labels: enhancement, Image

#1647 FIREFLY-1578: nvl2 function does not exists in DuckDB
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java
  src/firefly/js/util/__tests__/VOAnalyzer-test.js
Labels: Table

#1644 FIREFLY-1492: Timeseries Period Finder Layout Issues
  src/firefly/js/templates/lightcurve/LCPanels.css
  src/firefly/js/templates/lightcurve/LcPeriodPlotly.jsx
Labels: bug

#1650 IRSA-5xxx: multiple tickets: IRSA-5577, IRSA-5779, IRSA-5390
  docs/next-release-details.md
  src/firefly/java/edu/caltech/ipac/table/io/SpectrumMetaInspector.java
  src/firefly/js/drawingLayers/hpx/HpxCatalog.js
  src/firefly/js/metaConvert/vo/ServDescProducts.js
  src/firefly/js/tables/HpxIndexCntlr.js
  src/firefly/js/ui/VersionInfo.jsx
  src/firefly/js/visualize/PlotAttribute.js
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/saga/CoverageUtil.jsx
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/ui/Buttons.jsx
  src/firefly/js/visualize/ui/VisInlineToolbarView.jsx
Labels: bug, enhancement

#1652 FIREFLY-1575: Simbad query returns duplicate columns
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
  src/firefly/java/edu/caltech/ipac/table/DataGroup.java
  src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/java/edu/caltech/ipac/table/io/DataGroupStarTable.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
Labels: bug, Table

#1653 Firefly-1581: recognize cutout default from service
  src/firefly/js/metaConvert/vo/ServDescProducts.js
  src/firefly/js/visualize/ui/multiProduct/MetaDataMultiProductViewer.jsx
Labels: enhancement

#1654 Firelfy-1582: fixed: region saving as ellipse
  src/firefly/java/edu/caltech/ipac/util/RegionFactory.java
  src/firefly/js/drawingLayers/hpx/HpxDraw.js
  src/firefly/js/drawingLayers/hpx/TileDataMaker.jsx
  src/firefly/js/tables/HpxIndexCntlr.js
  src/firefly/js/visualize/draw/DrawObj.js
  src/firefly/js/visualize/draw/ShapeToRegion.js
Labels: bug

#1655 IRSA-6427: encodeUrlString() returning bad hash segment
  src/firefly/js/util/WebUtil.js
  src/firefly/js/util/__tests__/WebUtil-test.js
Labels: bug

#1657 FIREFLY-1583: IpacTableFromSource fail to inject table meta when ingesting data directly from source
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
  src/firefly/java/edu/caltech/ipac/table/DataGroup.java
Labels: Table

#1656 Firefly-1585: improved hdu title options, use by SHA
  src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotRequest.java
  src/firefly/js/metaConvert/missions/ShaRequestList.js
  src/firefly/js/visualize/FitsHeaderUtil.js
  src/firefly/js/visualize/PlotAttribute.js
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Labels: enhancement, Image

#1659 Firefly-1584: Upload not showing table summary after multi extension FITS
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Labels: bug

#1651 FIREFLY-1568: Periodogram Render bug fix
  src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
Labels: bug

#1660 Firefly-1587: improving overlays
  docs/release-notes.md
  src/firefly/js/drawingLayers/FixedPtControl.jsx
  src/firefly/js/drawingLayers/FootprintTool.js
  src/firefly/js/drawingLayers/MarkerTool.js
  src/firefly/js/drawingLayers/WebGrid.js
  src/firefly/js/drawingLayers/WebGridUI.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/visualize/draw/DrawLayer.js
  src/firefly/js/visualize/saga/MouseReadoutWatch.js
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
  src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx
  src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
  src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx
  src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
  src/firefly/js/voAnalyzer/VoTableRecognizer.js
Labels: bug, multi-ticket

#1661 IRSA-6431: Firefly tables in expanded mode was unable to switch tabs.
  src/firefly/html/test/tests-table.html
  src/firefly/js/tables/ui/TablesContainer.jsx
Labels: bug
