Repository Caltech-IPAC/firefly, pull requests merged in 2024-05, with the labels that each got.

#1551 Firefly-1473: clean up HiPS toolbar
  src/firefly/js/ui/DropDownMenu.jsx
  src/firefly/js/ui/FileUpload.jsx
  src/firefly/js/ui/InputAreaFieldView.jsx
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/tap/ObjectIDSearch.jsx
  src/firefly/js/util/HttpErrorMessage.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/iv/EventLayer.jsx
  src/firefly/js/visualize/iv/ImageExpandedMode.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/ui/Buttons.jsx
  src/firefly/js/visualize/ui/MouseReadPopoutAll.jsx
  src/firefly/js/visualize/ui/MouseReadout.css
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Labels: enhancement, HiPS

#1553 FIREFLY-1468 Non-celestial coordinate readout.
  src/firefly/js/drawingLayers/SelectArea.js
  src/firefly/js/ui/PositionFieldDef.js
  src/firefly/js/visualize/ChangePrime.js
  src/firefly/js/visualize/CoordSys.js
  src/firefly/js/visualize/CsysConverter.js
  src/firefly/js/visualize/MouseReadoutCntlr.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/projection/Projection.js
  src/firefly/js/visualize/projection/ProjectionHeaderParser.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/saga/MouseReadoutWatch.js
  src/firefly/js/visualize/task/PlotImageTask.js
  src/firefly/js/visualize/task/WcsMatchTask.js
  src/firefly/js/visualize/ui/MatchLockDropDown.jsx
  src/firefly/js/visualize/ui/MouseReadPopoutAll.jsx
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
  src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx
  src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
  src/firefly/js/visualize/ui/ThumbnailView.jsx
Labels: enhancement, Image

#1548 Firefly-1451: Embedded Position Search Panel Enhancements
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/ui/panel/CollapsiblePanel.jsx
Labels: enhancement, UI

#1558 Firefly-1476: fixes: readout bug with compressed files
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/FitsCacher.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
Labels: bug, Image

#1552 FIREFLY-1187: Update TAP ObsCore.jsx to support more options
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCoreMetadataQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/js/ui/AutoCompleteInput.jsx
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/ui/tap/TapViewType.jsx
Labels: UI, API

#1560 Firefly-1478: fixes items: 3,4,6,7
  src/firefly/js/api/ApiHighlevelBuild.js
  src/firefly/js/charts/ui/ChartsContainer.jsx
  src/firefly/js/charts/ui/MultiChartToolbar.jsx
  src/firefly/js/charts/ui/MultiChartViewer.jsx
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableChooser.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/ui/tap/TapViewType.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/ui/ApiFullImageDisplay.jsx
  src/firefly/js/visualize/ui/ApiToolbarImageDisplay.jsx
Labels: enhancement, UI

#1557 Firefly-1483: change firefly_client to better support triview and plan to deprecate slate
  src/firefly/js/Firefly.js
  src/firefly/js/api/ApiExpandedView.jsx
  src/firefly/js/api/ApiViewer.js
  src/firefly/js/charts/ui/CombineChart.jsx
  src/firefly/js/charts/ui/PinnedChartContainer.jsx
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/metaConvert/DataProductsType.js
  src/firefly/js/metaConvert/DataProductsWatcher.js
  src/firefly/js/metaConvert/DefaultConverter.js
  src/firefly/js/metaConvert/UploadAndAnalysis.js
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js
  src/firefly/js/templates/fireflyviewer/LayoutChoice.jsx
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/visualize/MultiViewCntlr.js
  src/firefly/js/visualize/task/PlotChangeTask.js
  src/firefly/js/visualize/ui/MultiImageViewerView.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
  src/firefly/js/voAnalyzer/TableAnalysis.js
Labels: bug, enhancement, UI, Infrastructure, API

#1561 FIREFLY-1487: Remove user-visible instances of "spacial"
  src/firefly/js/ui/TestQueriesPanel.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
Labels: bug

#1564 Firefly-1486: Don't include hidden columns in column count
  src/firefly/js/metaConvert/DefaultConverter.js
  src/firefly/js/ui/DefaultSearchActions.js
  src/firefly/js/ui/UploadTableChooser.js
  src/firefly/js/ui/UploadTableSelector.jsx
Labels: bug

#1565 Firefly-1488: grid icons cleanup and alignment
  src/firefly/js/visualize/ui/Buttons.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/ImagePager.jsx
  src/firefly/js/visualize/ui/multiProduct/DPDropdown.jsx
Labels: bug, enhancement, UI
