Repository Caltech-IPAC/firefly, pull requests merged in 2024-02, with the labels that each got.

#1487 Firefly-1403: Fixes: #6 #7 #11 #13 #23 #24 #26 #27 #13.7 #30 #31 #33 …
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
  src/firefly/js/ui/ActionsDropDownButton.jsx
  src/firefly/js/ui/PositionFieldDef.js
  src/firefly/js/ui/RadioGroupInputFieldView.jsx
  src/firefly/js/ui/RangeSliderView.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/TimePanel.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/tap/ObjectIDSearch.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/visualize/iv/ExpandedTools.jsx
  src/firefly/js/visualize/ui/Buttons.jsx
  src/firefly/js/visualize/ui/ColorDialog.jsx
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/DrawLayerItemView.jsx
  src/firefly/js/visualize/ui/ImageCenterDropDown.jsx
  src/firefly/js/visualize/ui/MatchLockDropDown.jsx
  src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx
  src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
  src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
  src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
Labels: bug, UI

#1472 Firefly-1341: Enhanced EmeddedPositionSearchPanel for upload
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/data/MetaConst.js
  src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js
  src/firefly/js/templates/hydra/HydraManager.js
  src/firefly/js/ui/SearchPanel.jsx
  src/firefly/js/ui/UploadTableChooser.js
  src/firefly/js/ui/UploadTableSelector.jsx
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicDef.js
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/ui/tap/Constraints.js
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/visualize/ui/CommonUIKeys.js
Labels: enhancement

#1489 FIREFLY-1398: Export additional functions to JS API
  src/firefly/js/api/ApiBuild.js
  src/firefly/js/api/ApiUtilChart.jsx
  src/firefly/js/api/ApiUtilTable.jsx
Labels: API

#1490 Firefly-1406: fixes 1, 29, 54 (partial, not all tables), 62, 64
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/ui/PopupPanel.jsx
  src/firefly/js/ui/PositionFieldDef.js
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/ui/CatalogTableListField.css
  src/firefly/js/visualize/ui/CatalogTableListField.jsx
  src/firefly/js/visualize/ui/ColorDialog.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Labels: UI

#1491 FIREFLY-1402: more chart related UI conversion changes
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/ui/FireflyRoot.jsx
  src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
  src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
Labels: enhancement, UI

#1493 Firefly-1407: response to some CCB-D feedback and #9, #10, #19, 24.5,…
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/templates/lightcurve/LcPeriodPlotly.jsx
  src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
  src/firefly/js/templates/lightcurve/LcResult.jsx
  src/firefly/js/ui/DownloadDialog.jsx
  src/firefly/js/ui/FileUpload.jsx
  src/firefly/js/ui/HiPSImageSelect.jsx
  src/firefly/js/ui/ImageSelect.jsx
  src/firefly/js/ui/InputAreaFieldView.jsx
  src/firefly/js/ui/SizeInputField.jsx
  src/firefly/js/ui/TargetFeedback.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/visualize/iv/PlotTitle.jsx
  src/firefly/js/visualize/region/RegionFileUploadView.jsx
  src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
  src/firefly/js/visualize/ui/DrawLayerItemView.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
Labels: UI

#1492 FIREFLY-1359: UI Conversion: convert date/time picker to Joy UI
  package.json
  src/firefly/js/ui/DateTimePickerField.jsx
  src/firefly/js/ui/JoyToMUIThemeWrapper.jsx
  src/firefly/js/ui/SuggestBoxInputField.jsx
  src/firefly/js/ui/TimePanel.jsx
  src/firefly/js/ui/TimeUIUtil.js
  src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
  src/firefly/js/ui/tap/TemporalSearch.jsx
  src/firefly/js/ui/tap/TimeRangePanel.jsx
  src/firefly/js/ui/tap/react-datetime.css
  yarn.lock
Labels: UI

#1495 IRSA-5700 & FIREFLY-1289: packaging and zoom
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/visualize/ZoomUtil.js
  src/firefly/js/visualize/reducer/HandlePlotCreation.js
  src/firefly/js/visualize/task/PlotImageTask.js
Labels: enhancement, multi-ticket

#1494 FIREFLY-1364 more updates and cleanup
  src/firefly/js/charts/ui/PlotlySaveDialog.jsx
  src/firefly/js/tables/ui/TableSave.jsx
  src/firefly/js/ui/DownloadOptionsDialog.jsx
  src/firefly/js/ui/FitsDownloadDialog.jsx
Labels: UI

#1496 FIREFLY-1408: JoyUI reported bugs
  src/firefly/html/css/global.css
  src/firefly/js/charts/ui/ChartPanel.jsx
  src/firefly/js/charts/ui/ChartSelectPanel.jsx
  src/firefly/js/charts/ui/ChartsContainer.jsx
  src/firefly/js/charts/ui/MultiChartViewer.jsx
  src/firefly/js/charts/ui/PinnedChartContainer.jsx
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/ui/ActionsDropDownButton.jsx
  src/firefly/js/ui/InputField.jsx
  src/firefly/js/ui/InputFieldView.jsx
  src/firefly/js/visualize/ui/Buttons.jsx
Labels: UI

#1497 FIREFLY-1412: Finish Charts conversion left over from FIREFLY-1408
  src/firefly/js/charts/ui/ChartPanel.jsx
  src/firefly/js/charts/ui/ChartsContainer.jsx
  src/firefly/js/charts/ui/ColSelectView.jsx
  src/firefly/js/charts/ui/ColumnOrExpression.jsx
  src/firefly/js/charts/ui/CombineChart.jsx
  src/firefly/js/charts/ui/MultiChartToolbar.jsx
  src/firefly/js/charts/ui/PlotlySaveDialog.jsx
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/FilterEditor.jsx
  src/firefly/js/tables/ui/TablePanel.css
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/ui/AutoCompleteInput.jsx
  src/firefly/js/ui/ChartSelectDropdown.jsx
  src/firefly/js/ui/CloseButton.jsx
  src/firefly/js/ui/InputAreaField.jsx
  src/firefly/js/ui/InputAreaFieldView.jsx
  src/firefly/js/ui/InputFieldView.jsx
  src/firefly/js/ui/panel/CollapsiblePanel.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/ObjectIDSearch.jsx
Labels: UI

#1498 Firefly-1413: Implement new button menu
  src/firefly/js/FFEntryPoint.js
  src/firefly/js/Firefly.js
  src/firefly/js/api/webApiCommands/TapCommands.js
  src/firefly/js/charts/ui/ChartSelectPanel.jsx
  src/firefly/js/charts/ui/MultiChartToolbar.jsx
  src/firefly/js/charts/ui/PinnedChartContainer.jsx
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
  src/firefly/js/core/ComponentCntlr.js
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/core/background/BgMonitorButton.jsx
  src/firefly/js/templates/common/FireflyLayout.jsx
  src/firefly/js/templates/common/MainPanel.jsx
  src/firefly/js/templates/fireflyslate/FireflySlate.jsx
  src/firefly/js/templates/fireflyviewer/DefaultLandingPage.jsx
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/fireflyviewer/LayoutChoice.jsx
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/templates/lightcurve/LcResult.jsx
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/ui/App.jsx
  src/firefly/js/ui/AppConfigDrawer.jsx
  src/firefly/js/ui/AppPropertiesCtx.jsx
  src/firefly/js/ui/Banner.jsx
  src/firefly/js/ui/CompleteButton.jsx
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/FileUploadDropdown.jsx
  src/firefly/js/ui/FireflyRoot.jsx
  src/firefly/js/ui/FormPanel.jsx
  src/firefly/js/ui/IrsaFooter.jsx
  src/firefly/js/ui/ListBoxInputField.jsx
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/ui/TestQueriesPanel.jsx
  src/firefly/js/ui/TestSearchPanel.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/VersionInfo.jsx
  src/firefly/js/ui/WorkspaceDropdown.jsx
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TableSelectViewPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/ui/Buttons.jsx
  src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
  src/firefly/js/visualize/ui/ExtraIpacSearches.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Labels: UI

#1501 FIREFLY-1415: Table options default size is too small
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TableRenderer.js
Labels: UI

#1503 Firefly-1418: UI cleanup
  src/firefly/js/Firefly.js
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/templates/common/FireflyLayout.jsx
  src/firefly/js/templates/fireflyslate/FireflySlate.jsx
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/ui/App.jsx
  src/firefly/js/ui/AppConfigDrawer.jsx
  src/firefly/js/ui/DialogRootContainer.jsx
  src/firefly/js/ui/DropDownDirContext.js
  src/firefly/js/ui/DropDownMenu.jsx
  src/firefly/js/ui/DropDownToolbarButton.jsx
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/UploadTableSelector.jsx
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/ui/tap/TapViewType.jsx
  src/firefly/js/visualize/ui/ImageCenterDropDown.jsx
Labels: bug, UI

#1504 FIREFLY-1419: Package download is no longer working
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/js/core/background/BackgroundCntlr.js
  src/firefly/js/core/background/BackgroundMonitor.jsx
  src/firefly/js/tables/SortInfo.js
  src/firefly/js/ui/DownloadDialog.jsx
  src/firefly/js/ui/dynamic/ServiceDefTools.js
Labels: bug

#1506 Firefly-1421: fixed multiple issues
  src/firefly/js/api/ApiUtil.js
  src/firefly/js/charts/ui/MultiChartToolbar.jsx
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/fireflyviewer/LayoutChoice.jsx
  src/firefly/js/templates/fireflyviewer/ResultsPanel.jsx
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/ui/CatalogSearchMethodType.jsx
  src/firefly/js/ui/DropDownToolbarButton.jsx
  src/firefly/js/ui/FileUpload.jsx
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/tap/TapViewType.jsx
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/ui/DrawLayerItemView.jsx
  src/firefly/js/visualize/ui/ExtraIpacSearches.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Labels: bug

#1505 Firefly 1420 cleanup items
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
  src/firefly/js/tables/ui/BasicTableView.jsx
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/tables/ui/TableSave.jsx
  src/firefly/js/ui/DialogRootContainer.jsx
  src/firefly/js/ui/ImageSelect.jsx
  src/firefly/js/ui/SimpleComponent.jsx
  src/firefly/js/ui/Stacker.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/visualize/ui/Buttons.jsx
Labels: UI
