Repository Caltech-IPAC/firefly, pull requests merged in 2024-04, with the labels that each got.

#1528 FIREFLY-1452: fix bugs in UploadTableChooser popup
  src/firefly/js/ui/UploadTableChooser.js
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Labels: bug

#1529 Firefly-1453: fixes
  src/firefly/js/ui/ColorPicker.jsx
  src/firefly/js/ui/FitsDownloadDialog.jsx
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/MultiViewCntlr.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/iv/ExpandedTools.jsx
  src/firefly/js/visualize/iv/ImageExpandedMode.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
  src/firefly/js/visualize/ui/MultiItemViewerView.jsx
Labels: bug, enhancement

#1524 IRSA-5925: Convert Euclid to JoyUI
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
Labels: UI

#1531 Firefly-1454: update landing page and menu
  src/firefly/js/templates/fireflyviewer/LandingPage.jsx
  src/firefly/js/ui/AppConfigDrawer.jsx
  src/firefly/js/ui/Menu.jsx
Labels: UI

#1532 IRSA-5926: Convert PlotlyChartArea into a functional component
  src/firefly/js/charts/ui/PlotlyChartArea.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/ui/FireflyRoot.jsx
  src/firefly/js/ui/JoyToMUIThemeWrapper.jsx
  src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
  src/firefly/js/visualize/ui/IrsaCatalogSearch.jsx
Labels: Charts

#1535 FIREFLY-1445: adjust cleanup script to keep upload files for 1 day
  docker/cleanup.sh
  src/firefly/java/edu/caltech/ipac/firefly/server/ExternalTaskHandlerImpl.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServCommand.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/BaseGator.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/CatMasterTableQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/GatorQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/IBEUtils.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/IbeFileRetrieve.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/MultiSpectrumProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryIBE.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryVOTABLE.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/DataAccessException.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/ConcurrentSearchUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/WorkdspaceImageFileRetriever.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerUtils.java
  src/firefly/js/core/JsonUtils.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/tables/reducer/TableDataReducer.js
  src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
Labels: Infrastructure

#1538 Firefly-1457, Firefly-1458: fixes
  src/firefly/js/core/AppDataReducers.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/visualize/MenuItemKeys.js
Labels: bug, multi-ticket

#1537 Firefly-1456: generalize and clean up DLGeneratedDropDown.js
  config/app.config
  src/firefly/js/FFEntryPoint.js
  src/firefly/js/api/webApiCommands/DatalinkUICommands.js
  src/firefly/js/api/webApiCommands/ViewerWebApiCommands.js
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/FileUploadProcessor.jsx
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/DLuiDecoration.jsx
  src/firefly/js/ui/dynamic/DLuiRootSearchPanel.jsx
  src/firefly/js/ui/dynamic/FetchDatalinkTable.js
  src/firefly/js/visualize/iv/ImageViewer.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/ui/MultiImageViewer.jsx
  src/firefly/js/visualize/ui/MultiImageViewerView.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/TargetHipsPanelToolbar.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Labels: UI

#1540 FIREFLY-1396: Display overflow indicator when present in VOTable.
  src/firefly/js/core/background/JobInfo.jsx
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/ui/PagingBar.jsx
  src/firefly/js/ui/Stacker.jsx
Labels: enhancement

#1534 IRSA-5960: Added PDF icon for use in FinderChart
  src/firefly/js/templates/hydra/HydraViewer.jsx
  src/firefly/js/visualize/ui/Buttons.jsx
Labels: enhancement

#1542 FIREFLY-1396: Display TAP overflow indicator when present in VOTable
  src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
  src/firefly/java/edu/caltech/ipac/table/ResourceInfo.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/js/core/background/JobInfo.jsx
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/tables-typedefs.jsdoc
  src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/tables/ui/TablesContainer.jsx
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
Labels: bug

#1543 Firefly-1448 & Firefly-1462: multiple fixes
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
  src/firefly/java/edu/caltech/ipac/util/download/ResponseMessage.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/tables/SelectInfo.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/ui/FileUpload.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/tap/ObjectIDSearch.jsx
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/ImViewFilterDisplay.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/iv/ExpandedTools.jsx
  src/firefly/js/visualize/projection/ProjectionHeaderParser.js
  src/firefly/js/visualize/projection/WavelengthHeaderParser.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
  src/firefly/js/visualize/ui/MultiImageViewer.jsx
  src/firefly/js/visualize/ui/MultiImageViewerView.jsx
  src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
  src/firefly/js/voAnalyzer/TableAnalysis.js
Labels: Image, UI, multi-ticket

#1541 FIREFLY-1459: Create DALI utility functions to support standard parameters like UPLOAD and MAX_REC.
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServiceInput.java
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/DaliQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/DaliUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/test/edu/caltech/ipac/firefly/server/query/AsyncTapQueryTest.java
  src/firefly/test/edu/caltech/ipac/firefly/server/query/DaliUtilTest.java
Labels: enhancement

#1544 FIREFLY-1461: Refactor FormPanel and introduce slots
  src/firefly/js/charts/ui/ChartSelectPanel.jsx
  src/firefly/js/core/core-typedefs.jsdoc
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/ui/CompleteButton.jsx
  src/firefly/js/ui/DownloadDialog.jsx
  src/firefly/js/ui/FileUploadDropdown.jsx
  src/firefly/js/ui/FormPanel.jsx
  src/firefly/js/ui/HiPSImageSelect.jsx
  src/firefly/js/ui/ScriptDownloadDialog.jsx
  src/firefly/js/ui/SearchPanel.jsx
  src/firefly/js/ui/SimpleComponent.jsx
  src/firefly/js/ui/TestQueriesPanel.jsx
  src/firefly/js/ui/TestSearchPanel.jsx
  src/firefly/js/ui/UploadTableChooser.js
  src/firefly/js/ui/UploadTableSelector.jsx
  src/firefly/js/ui/WorkspaceDropdown.jsx
  src/firefly/js/ui/dynamic/DLuiRootSearchPanel.jsx
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/ObjectIDSearch.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/visualize/ui/Buttons.jsx
  src/firefly/js/visualize/ui/ExtraIpacSearches.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/IrsaCatalogSearch.jsx
Labels: Refactor

#1550 Firefly-1472: bug fix: menu should adjust with browser set fonts sizes
  src/firefly/js/FFEntryPoint.js
  src/firefly/js/ui/Banner.jsx
  src/firefly/js/ui/Menu.jsx
Labels: bug, UI

#1549 FIREFLY-1471: Add server-side support for NULL values
  src/firefly/java/edu/caltech/ipac/table/PrimitiveList.java
  src/firefly/js/charts/ui/CombineChart.jsx
  src/firefly/js/charts/ui/PinnedChartContainer.jsx
  src/firefly/js/core/AppDataCntlr.js
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/ui/FormPanel.jsx
  src/firefly/js/ui/HelpIcon.jsx
  src/firefly/js/ui/HelpText.jsx
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/visualize/SearchRefinementTool.jsx
  src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
  src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
  src/firefly/js/visualize/ui/ExtractionDialog.jsx
  src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx
  src/firefly/js/visualize/ui/TargetHipsPanelToolbar.jsx
  src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/DataGroupReadTest.java
Labels: multi-ticket
