Repository Caltech-IPAC/firefly, pull requests merged in 2024-03, with the labels that each got.

#1509 FIREFLY-1422-ui-rubin-irsa: Multiple fixes from IRSA and Rubin testing
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/drawingLayers/Catalog.js
  src/firefly/js/drawingLayers/SearchTarget.js
  src/firefly/js/ui/AppConfigDrawer.jsx
  src/firefly/js/ui/InputFieldView.jsx
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/ui/SizeInputField.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapViewType.jsx
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Labels: bug, UI

#1510 IRSA-5873: Create SpherexForcedPhot processor
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/js/visualize/ui/ImageTableRowViewer.jsx
Labels: enhancement

#1512 Firefly 1424 more UI conversion fix
  src/firefly/js/charts/ui/ChartPanel.jsx
  src/firefly/js/charts/ui/MultiChartViewer.jsx
  src/firefly/js/charts/ui/PinnedChartContainer.jsx
  src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
  src/firefly/js/tables/ui/FilterEditor.jsx
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/tables/ui/TableSave.jsx
  src/firefly/js/tables/ui/TablesContainer.jsx
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/ui/DialogRootContainer.jsx
  src/firefly/js/ui/DownloadOptionsDialog.jsx
  src/firefly/js/ui/ExampleDialog.jsx
  src/firefly/js/ui/FitsDownloadDialog.jsx
  src/firefly/js/ui/InputFieldView.jsx
  src/firefly/js/ui/MultiSearchPanel.jsx
  src/firefly/js/ui/SearchPanel.jsx
  src/firefly/js/ui/TestQueriesPanel.jsx
  src/firefly/js/ui/UploadTableChooser.js
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/visualize/ui/ColorDialog.jsx
  src/firefly/js/visualize/ui/FitsHeaderView.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/ImageStatsPopup.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
Labels: bug, UI

#1508 FIREFLY-1416: UI Conversion: Update landing page to have a polished look
  src/firefly/js/FFEntryPoint.js
  src/firefly/js/Firefly.js
  src/firefly/js/templates/fireflyviewer/DefaultLandingPage.jsx
  src/firefly/js/templates/fireflyviewer/LandingPage.jsx
  src/firefly/js/ui/AppConfigDrawer.jsx
  src/firefly/js/ui/AppPropertiesCtx.jsx
  src/firefly/js/ui/Banner.jsx
  src/firefly/js/ui/ImageSelect.css
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/ui/VersionInfo.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Labels: UI

#1511 Firefly-1425: Multi: joyUI cleanup, upload fix, region warning
  src/firefly/html/css/global.css
  src/firefly/js/charts/ui/PinnedChartContainer.jsx
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
  src/firefly/js/drawingLayers/Catalog.js
  src/firefly/js/drawingLayers/CatalogUI.jsx
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/tables/ui/ActiveTableButton.jsx
  src/firefly/js/ui/DropDownToolbarButton.jsx
  src/firefly/js/ui/FileUploadProcessor.jsx
  src/firefly/js/ui/FitsDownloadDialog.jsx
  src/firefly/js/ui/FitsRotationDialog.jsx
  src/firefly/js/ui/HelpIcon.jsx
  src/firefly/js/ui/IbeSpacialType.jsx
  src/firefly/js/ui/InputFieldLabel.jsx
  src/firefly/js/ui/InputFieldView.jsx
  src/firefly/js/ui/LinkButton.jsx
  src/firefly/js/ui/PointerPopup.jsx
  src/firefly/js/ui/ProgressBar.jsx
  src/firefly/js/ui/StatedInputfield.jsx
  src/firefly/js/ui/TextButton.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/HiPSPropertyView.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/MultiImageViewer.jsx
  src/firefly/js/visualize/ui/MultiImageViewerContainer.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: bug, UI, multi-ticket

#1514 Firefly-1404: multiple mask layer fix and other tickets
  src/firefly/java/edu/caltech/ipac/firefly/data/RelatedData.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/MaskEval.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/SpectralCubeEval.java
  src/firefly/java/edu/caltech/ipac/util/FitsHDUUtil.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
  src/firefly/js/metaConvert/vo/ObsCoreConverter.js
  src/firefly/js/visualize/RelatedDataUtil.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/task/CreateTaskUtil.js
  src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
  src/firefly/js/voAnalyzer/TableAnalysis.js
Labels: bug, multi-ticket

#1516 Firefly-1434: fixes: irsa 9, rubin-chart 2,3, empty FITS table
  src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
  src/firefly/js/charts/ui/ColSelectView.jsx
  src/firefly/js/charts/ui/ColumnOrExpression.jsx
  src/firefly/js/charts/ui/MultiChartToolbar.jsx
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/UploadTableSelector.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableColumnsConstraints.jsx
  src/firefly/js/ui/tap/TemporalSearch.jsx
  src/firefly/js/visualize/iv/ExpandedTools.jsx
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/ui/Buttons.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Labels: bug, UI, multi-ticket

#1518 Firefly-1441: clean up icons for pngs
  src/firefly/html/images/icons-2014/24x24_Log.png
  src/firefly/js/charts/ui/ChartPanel.jsx
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
  src/firefly/js/drawingLayers/FixedPtControl.jsx
  src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
  src/firefly/js/ui/ImageSelect.jsx
  src/firefly/js/ui/PagingBar.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/visualize/iv/ExpandedTools.jsx
  src/firefly/js/visualize/ui/Buttons.jsx
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/MatchLockDropDown.jsx
  src/firefly/js/visualize/ui/MouseReadout.jsx
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
  src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx
  src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/VisMiniToolbar.jsx
  src/firefly/js/visualize/ui/ZoomButton.jsx
Labels: UI

#1517 FIREFLY-1427: Provide option for HydraViewer apps to use Menu instead of search panel.
  src/firefly/html/css/global.css
  src/firefly/js/FFEntryPoint.js
  src/firefly/js/core/AppDataCntlr.js
  src/firefly/js/core/AppDataReducers.js
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/core/core-typedefs.jsdoc
  src/firefly/js/templates/common/FireflyLayout.jsx
  src/firefly/js/templates/fireflyslate/FireflySlate.jsx
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/fireflyviewer/LandingPage.jsx
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/templates/hydra/HydraViewer.jsx
  src/firefly/js/templates/lightcurve/LcViewer.jsx
  src/firefly/js/ui/App.jsx
  src/firefly/js/ui/AppConfigDrawer.jsx
  src/firefly/js/ui/Banner.jsx
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/FormPanel.jsx
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/ui/MultiSearchPanel.jsx
  src/firefly/js/ui/SearchPanel.jsx
  src/firefly/js/ui/SimpleComponent.jsx
  src/firefly/js/ui/Stacker.jsx
  src/firefly/js/ui/ThemeSetup.js
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/ui/FitsHeaderView.jsx
  src/firefly/js/visualize/ui/TriViewImageSection.jsx
Labels: UI

#1519 FIREFLY-1401: UI Conversion: Improve chart options panel
  src/firefly/js/charts/ui/ColumnOrExpression.jsx
  src/firefly/js/charts/ui/CombineChart.jsx
  src/firefly/js/charts/ui/options/BasicOptions.jsx
  src/firefly/js/charts/ui/options/Errors.jsx
  src/firefly/js/charts/ui/options/FireflyHistogramOptions.jsx
  src/firefly/js/charts/ui/options/HeatmapOptions.jsx
  src/firefly/js/charts/ui/options/NewTracePanel.jsx
  src/firefly/js/charts/ui/options/ScatterOptions.jsx
  src/firefly/js/charts/ui/options/SpectrumOptions.jsx
  src/firefly/js/ui/AutoCompleteInput.jsx
  src/firefly/js/ui/CheckboxGroupInputField.jsx
  src/firefly/js/ui/CloseButton.jsx
  src/firefly/js/ui/SwitchInputField.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/visualize/iv/ExpandedTools.jsx
  src/firefly/js/visualize/ui/ImageTableRowViewer.jsx
  src/firefly/js/visualize/ui/MultiItemViewerView.jsx
Labels: UI

#1520 Firefly-1439: fix regression issues
  src/firefly/html/test/test-coverage.html
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/templates/fireflyslate/FireflySlate.jsx
  src/firefly/js/templates/fireflyviewer/FireflyViewer.js
  src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
  src/firefly/js/ui/ToolbarButton.jsx
Labels: bug

#1521 Firefly-1443: improve tab resizing
  src/firefly/js/api/webApiCommands/TapCommands.js
  src/firefly/js/api/webApiCommands/ViewerWebApiCommands.js
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/core/background/BgMonitorButton.jsx
  src/firefly/js/templates/router/RouteHelper.jsx
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/ui/WebApiHelpInfoPage.jsx
Labels: UI

#1522 FIREFLY-1436: Route-based apps with the new Menu/SideBar features.
  buildScript/tasks.gincl
  src/firefly/js/core/AppDataReducers.js
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/core/core-typedefs.jsdoc
  src/firefly/js/templates/hydra/HydraViewer.jsx
  src/firefly/js/templates/router/RouteHelper.jsx
  src/firefly/js/templates/router/RoutedApp.jsx
  src/firefly/js/ui/App.jsx
  src/firefly/js/ui/AppConfigDrawer.jsx
  src/firefly/js/ui/Banner.jsx
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/ui/SearchPanel.jsx
Labels: UI

#1523 FIREFLY-1447: Table model isFetching failed to unset when background job failed
  src/firefly/js/core/background/BackgroundUtil.js
  src/firefly/js/tables/ui/TableRenderer.js
Labels: bug

#1526 Firefly-1450: Multi fixes and object id feature
  src/firefly/js/tables/ui/TablePanel.jsx
  src/firefly/js/ui/CheckboxGroupInputField.jsx
  src/firefly/js/ui/ListBoxInputField.jsx
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/ui/RadioGroupInputField.jsx
  src/firefly/js/ui/RadioGroupInputFieldView.jsx
  src/firefly/js/ui/SwitchInputField.jsx
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
  src/firefly/js/ui/tap/Constraints.js
  src/firefly/js/ui/tap/ObjectIDSearch.jsx
  src/firefly/js/ui/tap/TableChooser.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapViewType.jsx
  src/firefly/js/visualize/ui/Buttons.jsx
  src/firefly/js/visualize/ui/ExtraIpacSearches.jsx
  src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
  src/firefly/js/visualize/ui/IrsaCatalogSearch.jsx
  src/firefly/js/visualize/ui/MatchLockDropDown.jsx
  src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Labels: bug, enhancement, UI
