Repository Caltech-IPAC/firefly, pull requests merged in 2024-11, with the labels that each got.

#1662 FIREFLY-1591: Directly import VOTable data into the database.
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbDataIngestor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableHandler.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/DataGroupReadTest.java
Labels: Table

#1665 Firefly-1601: coverage supports up to 36 million rows
  src/firefly/js/drawingLayers/hpx/HpxCatalog.js
  src/firefly/js/drawingLayers/hpx/TileDataMaker.jsx
  src/firefly/js/tables/HpxIndexCntlr.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
Labels: bug

#1666 FIREFLY-1606-links-missing-port
  src/firefly/js/util/WebUtil.js
  src/firefly/js/util/__tests__/WebUtil-test.js
Labels: bug

#1669 FIREFLY-1593: Column filter in table option does not track previous f…
  src/firefly/js/tables/ui/TablePanelOptions.jsx
Labels: bug, Table

#1667 FIREFLY-1592: Directly import IPAC table data into the database
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbDataIngestor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
  src/firefly/java/edu/caltech/ipac/table/io/IpacTableReader.java
  src/firefly/java/edu/caltech/ipac/table/io/TableParseHandler.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/js/tables/TableUtil.js
  src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/DataGroupReadTest.java
Labels: Table

#1668 FIREFLY-1607: Server-side implementation of Healpix index
  src/firefly/java/edu/caltech/ipac/firefly/resources/healpix-java.sql
  src/firefly/java/edu/caltech/ipac/firefly/server/ServCommand.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbInstance.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbUDF.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/spring/JdbcFactory.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/HealpixProcessor.java
  src/firefly/java/edu/caltech/ipac/util/StringUtils.java
  src/firefly/js/charts/ChartsCntlr.js
  src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
  src/firefly/test/edu/caltech/ipac/table/HealpixProcessorTest.java
Labels: Infrastructure

#1672 Firefly-1621: fixed race condition when images loading
  src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/Firefly.js
  src/firefly/js/api/webApiCommands/ImageCommands.js
  src/firefly/js/api/webApiCommands/TableCommands.js
Labels: bug, multi-ticket

#1673 Firefly-1620: more spectrum types for the guesser
  src/firefly/java/edu/caltech/ipac/table/io/SpectrumMetaInspector.java
  src/firefly/js/charts/dataTypes/FireflySpectrum.js
Labels: enhancement
