Repository Caltech-IPAC/firefly, pull requests merged in 2024-12, with the labels that each got.

#1674 FIREFLY-1572: Improve copying of coordinates from image panel
  src/firefly/js/visualize/MouseReadoutCntlr.js
  src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx
  src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
Labels: enhancement, Image

#1679 Firelfy-1597: fixes: things with null ra/dec shouldn't be plotted on coverage map
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
  src/firefly/js/tables/HpxIndexCntlr.js
Labels: bug

#1678 FIREFLY-1627: filtering on spectral plots with >1 order causes chaos
  src/firefly/js/charts/ui/ChartPanel.jsx
Labels: bug, Charts

#1677 Firefly-1622: SIAv2 Implementation
  src/firefly/js/Firefly.js
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/ui/tap/Constraints.js
  src/firefly/js/ui/tap/ObjectIDSearch.jsx
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
  src/firefly/js/ui/tap/SIASearchRootPanel.jsx
  src/firefly/js/ui/tap/SiaUI.jsx
  src/firefly/js/ui/tap/SiaUtil.js
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/ui/tap/TemporalSearch.jsx
  src/firefly/js/ui/tap/WavelengthPanel.jsx
  src/firefly/js/voAnalyzer/VoCoreUtils.js
Labels: enhancement, Image, UI

#1680 FIREFLY-1632: Enhance HTTP fetch error messages with response body details
  src/firefly/java/edu/caltech/ipac/firefly/core/background/Job.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
  src/firefly/test/edu/caltech/ipac/table/IpacTableFromSourceTest.java
Labels: enhancement

#1681 Firefly-1612: bug fix: table tab color wrong
  src/firefly/js/visualize/saga/CatalogWatcher.js
Labels: bug

#1682 Firefly-1624: improve bottom mouse readout layout
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
Labels: bug

#1670 FIREFLY-1615: Improve file type detection
  buildScript/dependencies.gradle
  buildScript/tasks.gincl
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/ExtractSpectraSample.java
  src/firefly/java/edu/caltech/ipac/firefly/data/sofia/Sofia1DSpectraExtractor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/SrvParam.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbDataIngestor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbInstance.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbMonitor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbUDF.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/DaliUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTablePartProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/IrsaLightCurveHandler.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HealthCheck.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HttpServCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/Logger.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerCommands.java
  src/firefly/java/edu/caltech/ipac/table/DataGroup.java
  src/firefly/java/edu/caltech/ipac/table/DataType.java
  src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/java/edu/caltech/ipac/table/io/DsvTableIO.java
  src/firefly/java/edu/caltech/ipac/table/io/IpacTableReader.java
  src/firefly/java/edu/caltech/ipac/table/io/TableParseHandler.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableWriter.java
  src/firefly/java/edu/caltech/ipac/util/FileUtil.java
  src/firefly/java/edu/caltech/ipac/util/FitsHDUUtil.java
  src/firefly/java/edu/caltech/ipac/util/FormatUtil.java
  src/firefly/java/edu/caltech/ipac/util/StringUtils.java
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/test/edu/caltech/ipac/firefly/ConfigTest.java
  src/firefly/test/edu/caltech/ipac/firefly/server/query/AsyncTapQueryTest.java
  src/firefly/test/edu/caltech/ipac/table/DuckDbAdapterTest.java
  src/firefly/test/edu/caltech/ipac/util/FormatUtilTest.java
Labels: Infrastructure

#1684 FIREFLY-1599: cascade combining spectra is broken
  buildScript/tasks.gincl
  src/firefly/java/edu/caltech/ipac/firefly/server/query/StatisticsProcessor.java
  src/firefly/js/charts/ui/CombineChart.jsx
Labels: bug

#1683 FIREFLY-1635: bug fix for CADC prepare download
  src/firefly/js/templates/common/ttFeatureWatchers.js
Labels: bug
