Repository Caltech-IPAC/firefly, pull requests merged in 2024-08, with the labels that each got.

#1599 Restore normal reverse order of patches
  docs/release-notes.md
Labels: documentation

#1600 Firefly-1510: Color shows in table tabs
  src/firefly/js/drawingLayers/Catalog.js
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/tables/ui/TablesContainer.jsx
  src/firefly/js/ui/ColorPicker.jsx
  src/firefly/js/ui/RadioGroupInputField.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/ui/tap/ResultTitleDialog.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TableSearchMethods.jsx
  src/firefly/js/ui/tap/TapKnownServices.js
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/js/ui/tap/TapViewType.jsx
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
  src/firefly/js/visualize/ui/DrawLayerUIComponents.jsx
Labels: enhancement, UI

#1601 Firefly-1529: fixed datalink issue with gaia
  src/firefly/java/edu/caltech/ipac/firefly/server/util/JsonToDataGroup.java
  src/firefly/java/edu/caltech/ipac/table/TableUtil.java
  src/firefly/java/edu/caltech/ipac/table/io/DsvTableIO.java
  src/firefly/java/edu/caltech/ipac/table/io/IpacTableReader.java
  src/firefly/java/edu/caltech/ipac/table/io/SpectrumMetaInspector.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/metaConvert/PartAnalyzer.js
Labels: bug

#1602 IRSA-6112: Support Euclid combine results
  src/firefly/js/metaConvert/DataProductsWatcher.js
  src/firefly/js/tables/TableUtil.js
Labels: enhancement

#1604 Hotfix: one char bug fix for spectra in euclid
  src/firefly/js/metaConvert/PartAnalyzer.js
Labels: bug

#1606 FIREFLT-1535: Timeseries bug fix
  src/firefly/js/charts/ChartsCntlr.js
  src/firefly/js/charts/ui/PlotlyWrapper.jsx
  src/firefly/js/templates/lightcurve/LcViewer.jsx
Labels: bug

#1609 FIREFLY-1536: Support for standalone dispatchTblResultsAdded to support reordering of tables
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/tables/reducer/TableUiReducer.js
  src/firefly/js/tables/ui/TablePanel.jsx
Labels: enhancement

#1608 IRSA-6084: changing x/y axis does not work when using column search popup
  src/firefly/js/charts/ui/options/BasicOptions.jsx
  src/firefly/js/charts/ui/options/ScatterOptions.jsx
  src/firefly/js/charts/ui/options/SpectrumOptions.jsx
  src/firefly/js/ui/panel/CollapsiblePanel.jsx
Labels: Charts

#1607 Firefly-1537: implement hierarchical catalogs
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/data/table/MetaConst.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
  src/firefly/js/api/ApiBuild.js
  src/firefly/js/charts/ChartUtil.js
  src/firefly/js/core/BootstrapRegistry.js
  src/firefly/js/data/MetaConst.js
  src/firefly/js/data/ServerParams.js
  src/firefly/js/drawingLayers/CatalogUI.jsx
  src/firefly/js/drawingLayers/HiPSGrid.js
  src/firefly/js/drawingLayers/HiPSGridlUI.jsx
  src/firefly/js/drawingLayers/hpx/HpxCatalog.js
  src/firefly/js/drawingLayers/hpx/HpxCatalogUtil.js
  src/firefly/js/drawingLayers/hpx/HpxDraw.js
  src/firefly/js/drawingLayers/hpx/TileDataMaker.jsx
  src/firefly/js/externalSource/aladinProj/HealpixIndex.js
  src/firefly/js/metaConvert/vo/DataLinkProcessor.js
  src/firefly/js/metaConvert/vo/ObsCoreConverter.js
  src/firefly/js/metaConvert/vo/ServDescConverter.js
  src/firefly/js/rpc/SearchServicesJson.js
  src/firefly/js/tables/HpxIndexCntlr.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/visualize/DrawLayerCntlr.js
  src/firefly/js/visualize/HiPSUtil.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/VisMouseSync.js
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/draw/DrawSymbol.js
  src/firefly/js/visualize/draw/DrawUtil.js
  src/firefly/js/visualize/draw/DrawingDef.js
  src/firefly/js/visualize/draw/PointDataObj.js
  src/firefly/js/visualize/draw/ShapeDataObj.js
  src/firefly/js/visualize/iv/HiPSTileDrawer.js
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/reducer/DrawLayerReducer.js
  src/firefly/js/visualize/saga/ActiveRowCenterWatcher.js
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/saga/CoverageWatcher.js
  src/firefly/js/visualize/ui/CtxToolbarFunctions.js
  src/firefly/js/voAnalyzer/TableAnalysis.js
Labels: enhancement, Image, Table, UI, HiPS

#1612 Firefly-1547: fixed: color table not inverting
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
Labels: bug

#1613 Firefly-1525, Firefly-1549: two tickets
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/DynamicDef.js
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
Labels: bug, enhancement, multi-ticket
