Repository Caltech-IPAC/firefly, pull requests merged in 2025-05, with the labels that each got.

#1749 FIREFLY-1686: Invalid SQL statement generated when expressions are used in charts requiring decimation.
  src/firefly/java/edu/caltech/ipac/firefly/server/query/DecimationProcessor.java
Labels: bug

#1753 FIREFLY-1731: Download Dialog UI Improvement
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PtfFileGroupsProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/WiseLightCurveFileGroupsProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/ZtfLCFileGroupsProcessor.java
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/ui/DownloadDialog.jsx
Labels: enhancement

#1752 Firelfly-1730: MultiProductViewer: more aggressively call Service Descriptors
  src/firefly/js/metaConvert/AnalysisUtils.js
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/DataProductsType.js
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/metaConvert/UploadAndAnalysis.js
  src/firefly/js/metaConvert/vo/ObsCoreConverter.js
  src/firefly/js/metaConvert/vo/ServDescConverter.js
  src/firefly/js/metaConvert/vo/ServDescProducts.js
  src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
  src/firefly/js/visualize/ui/Buttons.jsx
  src/firefly/js/visualize/ui/multiProduct/DPDropdown.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx
Labels: enhancement, UI

#1755 FIREFLY-1711: Table ingestion bug
  src/firefly/java/edu/caltech/ipac/table/io/TableParseHandler.java
Labels: bug

#1754 FIREFLY-1727: Handle Redis failure
  src/firefly/java/edu/caltech/ipac/firefly/core/RedisService.java
  src/firefly/java/edu/caltech/ipac/firefly/messaging/Messenger.java
  src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
  src/firefly/js/Firefly.js
  src/firefly/js/core/AppDataCntlr.js
  src/firefly/js/core/AppDataReducers.js
  src/firefly/js/core/messaging/WebSocketClient.js
  src/firefly/js/templates/common/FireflyLayout.jsx
  src/firefly/js/ui/LostConnection.jsx
  src/firefly/test/edu/caltech/ipac/firefly/core/RedisServiceTest.java
  src/firefly/test/edu/caltech/ipac/firefly/messaging/MessengerTest.java
  src/firefly/test/edu/caltech/ipac/util/cache/CachePeerProviderFactoryTest.java
  src/firefly/test/edu/caltech/ipac/util/cache/CacheTest.java
Labels: enhancement

#1756 FIREFLY-1695: Display error message when upload table can't be read
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/js/ui/FileUploadProcessor.jsx
  src/firefly/js/ui/UploadTableChooser.js
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Labels: bug, enhancement

#1758 FIREFLY-1723,1726,IRSA-6891: SPHEREx LVF improvements
  src/firefly/js/ui/WavelengthInputField.jsx
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/ui/tap/WavelengthPanel.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: bug, enhancement, multi-ticket

#1757 FIREFLY-1729: Client tables reset scroll on column width change
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/tables/reducer/TableUiReducer.js
  src/firefly/js/tables/ui/BasicTableView.jsx
Labels: bug

#1760 FIREFLY-1735: Job Monitor related tasks
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/js/core/background/JobHistory.jsx
  src/firefly/js/core/background/JobInfo.jsx
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/TablesCntlr.js
Labels: enhancement

#1761 Firefly-1390 table upload ignore overlay
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbDataIngestor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
  src/firefly/java/edu/caltech/ipac/table/io/TableParseHandler.java
  src/firefly/js/visualize/saga/CatalogWatcher.js
  src/firefly/js/visualize/ui/IrsaCatalogSearch.jsx
Labels: bug

#1763 Firefly-1736: URL API: add a go to tab
  src/firefly/js/Firefly.js
  src/firefly/js/api/webApiCommands/ImageCommands.js
  src/firefly/js/api/webApiCommands/TabCommands.js
  src/firefly/js/api/webApiCommands/ViewerWebApiCommands.js
  src/firefly/js/tables/ui/TablePanelOptions.jsx
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/ui/WebApiHelpInfoPage.jsx
Labels: enhancement

#1762 Firefly-1164,1734: multiple tickets
  src/firefly/js/drawingLayers/SelectArea.js
  src/firefly/js/drawingLayers/hpx/HpxCatalog.js
  src/firefly/js/drawingLayers/hpx/HpxCatalogUtil.js
Labels: bug, multi-ticket

#1764 FIREFLY-1721: fixed added columns go away
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
Labels: bug

#1766 Firefly-1740,48: clean up the color,strech,and otherlay sync button and add to other places
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/DirectStretchUtils.java
  src/firefly/js/metaConvert/vo/DataLinkProcessor.js
  src/firefly/js/metaConvert/vo/DatalinkProducts.js
  src/firefly/js/metaConvert/vo/ObsCoreConverter.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/ui/ColorBandPanel.jsx
  src/firefly/js/visualize/ui/ColorDialog.jsx
  src/firefly/js/visualize/ui/ColorPanelReducer.js
  src/firefly/js/visualize/ui/ColorRGBHuePreservingPanel.jsx
  src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
  src/firefly/js/visualize/ui/StretchDropDownView.jsx
  src/firefly/js/voAnalyzer/VoDataLinkServDef.js
Labels: bug, enhancement, multi-ticket

#1765 FIREFLY-1327: Update job info dialog
  src/firefly/js/core/background/BackgroundUtil.js
  src/firefly/js/core/background/JobInfo.jsx
  src/firefly/js/core/core-typedefs.jsdoc
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/ui/CssStrThemeWrapper.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
Labels: enhancement

#1767 Firefly-1743: Data product viewer: support related grid based on table filter
  src/firefly/js/fieldGroup/FieldGroupCntlr.js
  src/firefly/js/fieldGroup/FieldGroupUtils.js
  src/firefly/js/metaConvert/AnalysisUtils.js
  src/firefly/js/metaConvert/DataProductConst.js
  src/firefly/js/metaConvert/DataProductsType.js
  src/firefly/js/metaConvert/DataProductsWatcher.js
  src/firefly/js/metaConvert/UploadAndAnalysis.js
  src/firefly/js/metaConvert/vo/DataLinkProcessor.js
  src/firefly/js/metaConvert/vo/DatalinkFetch.js
  src/firefly/js/metaConvert/vo/DatalinkProducts.js
  src/firefly/js/metaConvert/vo/ObsCoreConverter.js
  src/firefly/js/metaConvert/vo/ServDescConverter.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
  src/firefly/js/visualize/ui/CoveraeViewer.jsx
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx
  src/firefly/js/voAnalyzer/VoDataLinkServDef.js
  src/firefly/js/voAnalyzer/vo-typedefs.jsdoc
Labels: enhancement

#1768 Firefly-1739: better handle table filtering when nothing is selected
  src/firefly/js/drawingLayers/hpx/HpxCatalogUtil.js
Labels: enhancement

#1769 IRSA-6898: SPHEREx: Reconcile LVF and Spectrophotometry Results
  src/firefly/html/css/global.css
  src/firefly/js/ui/panel/DockLayoutPanel.jsx
  src/firefly/js/visualize/ui/ImageTableRowViewer.jsx
Labels: enhancement, UI

#1771 IRSA-6794: Add Search Type Options optionally inside Embed panel
  src/firefly/js/ui/UploadTableSelector.jsx
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/ui/tap/AdvancedADQL.jsx
Labels: enhancement

#1772 FIREFLY-1749: HTML sanitizer removes supported features
  src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
  src/firefly/java/edu/caltech/ipac/table/TableMeta.java
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/ui/TableRenderer.js
Labels: bug

#1773 FIREFLY-1265: Table column filter misinterpret 'NOT LIKE'.
  src/firefly/js/tables/FilterInfo.js
Labels: bug

#1775 FIREFLY-1753: Fix Charts X/Y Ratio ui cutting off problem
  src/firefly/js/charts/ui/options/BasicOptions.jsx
Labels: bug

#1776 FIREFLY-1752: Send to background requires 2 clicks
  src/firefly/js/core/background/BgMaskPanel.jsx
Labels: bug

#1778 FIREFLY-1761: Add help to Email Notification field
  src/firefly/js/Firefly.js
  src/firefly/js/core/AppDataCntlr.js
  src/firefly/js/core/background/BackgroundCntlr.js
  src/firefly/js/core/background/BgMaskPanel.jsx
  src/firefly/js/core/background/JobMonitor.jsx
  src/firefly/js/ui/DropDownContainer.jsx
Labels: bug

#1780 Firefly-1760: SPHEREx Issues
  src/firefly/js/Firefly.js
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/metaConvert/TableDataProductUtils.js
  src/firefly/js/metaConvert/vo/DataLinkProcessor.js
  src/firefly/js/metaConvert/vo/ServDescProducts.js
  src/firefly/js/ui/CutoutSizeDialog.jsx
  src/firefly/js/ui/TargetPanelWorker.js
  src/firefly/js/ui/UploadTableSelector.jsx
  src/firefly/js/ui/panel/TabPanel.jsx
  src/firefly/js/ui/tap/Cutout.js
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TapKnownServices.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/ImageViewerLayout.jsx
  src/firefly/js/visualize/PlotAttribute.js
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/saga/ActiveRowToImageWatcher.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/task/WcsMatchTask.js
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/ImageTableRowViewer.jsx
  src/firefly/js/visualize/ui/multiProduct/MetaDataMultiProductViewer.jsx
  src/firefly/js/voAnalyzer/ColumnsModelInfo.js
  src/firefly/js/voAnalyzer/TableAnalysis.js
  src/firefly/js/voAnalyzer/VoConst.js
Labels: bug, enhancement, multi-ticket

#1779 FIREFLY-1703: SPHEREx: support URL API
  src/firefly/js/api/WebApi.js
  src/firefly/js/api/webApiCommands/TapCommands.js
  src/firefly/js/ui/CatalogSearchMethodType.jsx
  src/firefly/js/ui/CompleteButton.jsx
  src/firefly/js/ui/SearchPanel.jsx
  src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TapSearchRootPanel.jsx
  src/firefly/js/ui/tap/TapSearchSubmit.js
  src/firefly/js/ui/tap/WavelengthPanel.jsx
Labels: enhancement, API, TAP

#1783 Firefly-1769: SPHEREx: fix two issues
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/TableDataProductUtils.js
  src/firefly/js/metaConvert/vo/DataLinkProcessor.js
  src/firefly/js/visualize/ui/ImageTableRowViewer.jsx
Labels: bug
