Repository Caltech-IPAC/firefly, pull requests merged in 2025-07, with the labels that each got.

#1797 FIREFLY-1759: Enable downloads for Datalink tables
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
  src/firefly/js/metaConvert/TableDataProductUtils.js
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/ui/DefaultSearchActions.js
  src/firefly/js/ui/tap/Cutout.js
  src/firefly/js/voAnalyzer/VoDataLinkServDef.js
Labels: enhancement

#1811 `user-name` switching unexpectedly for same user
  src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/java/edu/caltech/ipac/firefly/server/filters/CommonFilter.java
  src/firefly/js/ui/Menu.jsx
  src/firefly/test/edu/caltech/ipac/firefly/ConfigTest.java
Labels: bug

#1813 FIREFLY-1798: Fix downloads for routed apps and improve obs core tbl recognition
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/templates/router/RoutedApp.jsx
  src/firefly/js/ui/tap/TapSearchSubmit.js
  src/firefly/js/voAnalyzer/TableAnalysis.js
Labels: bug, enhancement

#1816 FIREFLY-1803: Fix cutout size, ra, dec not updating in download script
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/ui/CutoutSizeDialog.jsx
Labels: bug
