Repository Caltech-IPAC/firefly, pull requests merged in 2025-09, with the labels that each got.

#1835 IRSA-7239: target entry bug
  src/firefly/js/ui/PositionFieldDef.js
Labels: bug

#1838 FIREFLY-1343: Enable tooltip text for ADQL JOINs
  src/firefly/js/ui/tap/AdvancedADQL.jsx
Labels: bug

#1836 FIREFLY-1788: Add LaTeX support to unit labels in charts and input fields + upgrade plotly to v3
  __jest__/jest.base.config.js
  buildScript/tasks.gincl
  buildScript/webpack.config.js
  docs/jstest-notes.md
  package.json
  src/firefly/html/plotly-2.32.0.min.js
  src/firefly/js/charts/PlotlyConfig.js
  src/firefly/js/charts/__tests__/SpectrumUnitConversion-test.js
  src/firefly/js/charts/dataTypes/FireflySpectrum.js
  src/firefly/js/charts/dataTypes/SpectrumUnitConversion.js
  src/firefly/js/charts/ui/ColumnOrExpression.jsx
  src/firefly/js/charts/ui/PlotlyChartArea.jsx
  src/firefly/js/charts/ui/options/SpectrumOptions.jsx
  src/firefly/js/ui/AutoCompleteInput.jsx
  src/firefly/js/ui/FireflyRoot.jsx
  src/firefly/js/util/LatexUtil.jsx
  yarn.lock
Labels: enhancement, Charts, UI

#1837 FIREFLY-1791: Fix username display issue
  src/firefly/java/edu/caltech/ipac/astro/ibe/IBE.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/RequestAgent.java
  src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
  src/firefly/java/edu/caltech/ipac/firefly/server/WebDAVWorkspaceManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/WebDAVWorkspaceManagerBase.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/BaseGator.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/GatorMOS.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/SDSSQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/events/FluxAction.java
  src/firefly/java/edu/caltech/ipac/firefly/server/events/MessageEventWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServiceInput.java
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/TempTable.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/DaliQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/IbeTemplateProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTablePartProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/URLFileInfoProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PtfFileGroupsProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/ZtfLCFileGroupsProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ptf/PtfIbeResolver.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
  src/firefly/java/edu/caltech/ipac/firefly/server/security/JOSSOAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/security/OidcAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/security/SsoAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileDownload.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/CommandService.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/Logger.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerUtils.java
  src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/core/AppDataReducers.js
  src/firefly/test/edu/caltech/ipac/firefly/ConfigTest.java
  src/firefly/test/edu/caltech/ipac/firefly/server/network/HttpServicesTest.java
  src/firefly/test/edu/caltech/ipac/firefly/server/query/DaliUtilTest.java
Labels: bug

#1846 Firefly-1850: Fixed: Wrong cutout warning with search by ID
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java
  src/firefly/js/ui/tap/SIASearchRootPanel.jsx
  src/firefly/js/ui/tap/TapSearchSubmit.js
Labels: bug

#1844 FIREFLY-1847: Render Euclid spectral units in charts
  src/firefly/js/charts/dataTypes/SpectrumUnitConversion.js
Labels: Charts

#1845 IRSA-7231: Fix extra Prepare Download button in Spherex Spectrophotometry results
  src/firefly/js/templates/common/ttFeatureWatchers.js
Labels: bug

#1850 FIREFLY-1638: Fix TAP selected cols number missing upon filtering
  src/firefly/js/ui/tap/TableColumnsConstraints.jsx
Labels: bug

#1851 Firefly 1836 tomcat upgrade
  README.md
  build.gradle
  buildScript/base.gincl
  buildScript/dependencies.gradle
  config/web.xml
  docker/Dockerfile
  gradle.properties
  src/firefly/java/edu/caltech/ipac/firefly/api/Async.java
  src/firefly/java/edu/caltech/ipac/firefly/server/RequestAgent.java
  src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServCommand.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/java/edu/caltech/ipac/firefly/server/events/WebsocketConnector.java
  src/firefly/java/edu/caltech/ipac/firefly/server/filters/CommonFilter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/filters/CorsFilter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/filters/NoCacheFilter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/security/JOSSOAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/security/OidcAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/security/SsoAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/security/SsoCheckFilter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/security/SsoVerifyServlet.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileDownload.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/BaseHttpServlet.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/CommandService.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HealthCheck.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HttpServCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/MultiPartHandler.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/MultipartDataUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/VersionUtil.java
Labels: Infrastructure
