Repository Caltech-IPAC/firefly, pull requests merged in 2025-01, with the labels that each got.

#1689 Firefly-1633: Multi Product viewer improvements
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java
  src/firefly/java/edu/caltech/ipac/table/io/SpectrumMetaInspector.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/core/ClickToAction.js
  src/firefly/js/data/MetaConst.js
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/drawingLayers/PointSelection.js
  src/firefly/js/metaConvert/AnalysisUtils.js
  src/firefly/js/metaConvert/DataProductsCntlr.js
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/DataProductsType.js
  src/firefly/js/metaConvert/DataProductsWatcher.js
  src/firefly/js/metaConvert/ImageDataProductsUtil.js
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/metaConvert/TableDataProductUtils.js
  src/firefly/js/metaConvert/UploadAndAnalysis.js
  src/firefly/js/metaConvert/vo/DataLinkProcessor.js
  src/firefly/js/metaConvert/vo/DataLinkStandAloneConverter.js
  src/firefly/js/metaConvert/vo/DatalinkFetch.js
  src/firefly/js/metaConvert/vo/DatalinkProducts.js
  src/firefly/js/metaConvert/vo/ObsCoreConverter.js
  src/firefly/js/metaConvert/vo/ServDescConverter.js
  src/firefly/js/metaConvert/vo/ServDescProducts.js
  src/firefly/js/metaConvert/vo/VORequest.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/ui/ActionsDropDownButton.jsx
  src/firefly/js/ui/CutoutSizeDialog.jsx
  src/firefly/js/ui/DefaultSearchActions.js
  src/firefly/js/ui/PopupUtil.jsx
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/ObsCoreOptions.js
  src/firefly/js/ui/tap/SIASearchRootPanel.jsx
  src/firefly/js/ui/tap/SiaUtil.js
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TapSearchSubmit.js
  src/firefly/js/ui/tap/TapViewType.jsx
  src/firefly/js/ui/tap/WavelengthPanel.jsx
  src/firefly/js/visualize/HiPSMocUtil.js
  src/firefly/js/visualize/ImViewFilterDisplay.js
  src/firefly/js/visualize/SearchRefinementTool.jsx
  src/firefly/js/visualize/reducer/HandlePlotChange.js
  src/firefly/js/visualize/reducer/PlotView.js
  src/firefly/js/visualize/task/PlotAdminTask.js
  src/firefly/js/visualize/task/PlotHipsTask.js
  src/firefly/js/visualize/ui/ImageMetaDataToolbar.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
  src/firefly/js/visualize/ui/multiProduct/DPDropdown.jsx
  src/firefly/js/visualize/ui/multiProduct/MetaDataMultiProductViewer.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx
  src/firefly/js/voAnalyzer/TableAnalysis.js
  src/firefly/js/voAnalyzer/VoDataLinkServDef.js
  src/firefly/js/voAnalyzer/vo-typedefs.jsdoc
Labels: enhancement, UI

#1690 IRSA-6468: Support for Packager Script of URLs (Euclid, SphereX, Rubin, etc.)
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/DownloadScriptWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/DownloadScript.java
  src/firefly/js/core/background/BackgroundCntlr.js
  src/firefly/js/core/background/BackgroundUtil.js
  src/firefly/js/data/ServerParams.js
  src/firefly/js/rpc/SearchServicesJson.js
  src/firefly/js/ui/DownloadDialog.jsx
Labels: enhancement

#1691 Firefly-1641: new FIREFLY_OPTIONS aproach
  firefly-docker.env
  src/firefly/java/edu/caltech/ipac/firefly/messaging/JsonHelper.java
  src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
  src/firefly/java/edu/caltech/ipac/util/AppProperties.java
Labels: Infrastructure

#1694 Firefly 1646 moc loading
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
Labels: enhancement

#1693 Firefly-1643: improve cutouts
  src/firefly/js/data/MetaConst.js
  src/firefly/js/metaConvert/TableDataProductUtils.js
  src/firefly/js/metaConvert/vo/DataLinkStandAloneConverter.js
  src/firefly/js/metaConvert/vo/ServDescProducts.js
  src/firefly/js/ui/CutoutSizeDialog.jsx
  src/firefly/js/ui/ToolbarButton.jsx
  src/firefly/js/ui/panel/CollapsiblePanel.jsx
  src/firefly/js/ui/tap/ObsCoreOptions.js
  src/firefly/js/ui/tap/SIASearchRootPanel.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/ui/tap/TableSearchHelpers.jsx
  src/firefly/js/ui/tap/TapSearchSubmit.js
  src/firefly/js/visualize/VisUtil.js
  src/firefly/js/visualize/projection/Projection.js
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/VisInlineToolbarView.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx
  src/firefly/js/voAnalyzer/TableAnalysis.js
  src/firefly/js/voAnalyzer/VoDataLinkServDef.js
  src/firefly/js/voAnalyzer/vo-typedefs.jsdoc
Labels: enhancement

#1695 FIREFLY-1610: Store Job information in Redis to support clustered deployment
  src/firefly/java/edu/caltech/ipac/firefly/api/Async.java
  src/firefly/java/edu/caltech/ipac/firefly/core/RedisService.java
  src/firefly/java/edu/caltech/ipac/firefly/core/Util.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/Job.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/ServCmdJob.java
  src/firefly/java/edu/caltech/ipac/firefly/messaging/JsonHelper.java
  src/firefly/java/edu/caltech/ipac/firefly/messaging/Message.java
  src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
  src/firefly/java/edu/caltech/ipac/firefly/server/cache/DistribMapCache.java
  src/firefly/java/edu/caltech/ipac/firefly/server/cache/DistributedCache.java
  src/firefly/java/edu/caltech/ipac/firefly/server/cache/EhcacheImpl.java
  src/firefly/java/edu/caltech/ipac/firefly/server/cache/EhcacheProvider.java
  src/firefly/java/edu/caltech/ipac/firefly/server/cache/LocalMapCache.java
  src/firefly/java/edu/caltech/ipac/firefly/server/cache/UserCache.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/BaseGator.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/events/ReplicatedQueueList.java
  src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/events/WebsocketConnector.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/DownloadScriptWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagedEmail.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/GuestHistoryCache.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryIBE.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryVOTABLE.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/BaseFileInfoProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/FileGroupsProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTablePartProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/JsonStringProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/security/OidcAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/MultipartDataUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/FitsCacher.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
  src/firefly/java/edu/caltech/ipac/util/cache/Cache.java
  src/firefly/java/edu/caltech/ipac/util/cache/CacheManager.java
  src/firefly/java/edu/caltech/ipac/util/cache/StringKey.java
  src/firefly/java/edu/caltech/ipac/util/download/CacheHelper.java
  src/firefly/test/edu/caltech/ipac/firefly/core/UtilTest.java
  src/firefly/test/edu/caltech/ipac/firefly/server/query/AsyncTapQueryTest.java
  src/firefly/test/edu/caltech/ipac/util/cache/CacheTest.java
Labels: Infrastructure

#1696 Firefly-441: provide target panel example config and make example clickable
  src/firefly/java/edu/caltech/ipac/astro/ibe/IBE.java
  src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/URLFileInfoProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/AllSkyRetriever.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/URLFileRetriever.java
  src/firefly/java/edu/caltech/ipac/util/FileUtil.java
  src/firefly/java/edu/caltech/ipac/visualize/net/AnyUrlParams.java
  src/firefly/js/Firefly.js
  src/firefly/js/api/webApiCommands/TableCommands.js
  src/firefly/js/ui/PositionFieldDef.js
  src/firefly/js/ui/TargetFeedback.jsx
  src/firefly/js/ui/TargetPanel.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/util/PositionParser.js
Labels: enhancement, UI
