Repository Caltech-IPAC/firefly, pull requests merged in 2025-03, with the labels that each got.

#1716 Firefly-1663: fixed multiple MOC issues
  src/firefly/js/drawingLayers/HiPSMOC.js
  src/firefly/js/tables/HpxIndexCntlr.js
  src/firefly/js/visualize/draw/DrawUtil.js
  src/firefly/js/visualize/draw/Drawer.js
  src/firefly/js/visualize/draw/MocObj.js
Labels: bug

#1717 Firefly-1666: Update data link to recognize extension columns and imp…
  src/firefly/js/drawingLayers/Catalog.js
  src/firefly/js/drawingLayers/hpx/HpxCatalog.js
  src/firefly/js/metaConvert/DataProductsFactory.js
  src/firefly/js/metaConvert/ImageDataProductsUtil.js
  src/firefly/js/metaConvert/vo/DataLinkProcessor.js
  src/firefly/js/metaConvert/vo/DatalinkProducts.js
  src/firefly/js/metaConvert/vo/ObsCoreConverter.js
  src/firefly/js/metaConvert/vo/ServDescConverter.js
  src/firefly/js/metaConvert/vo/ServDescProducts.js
  src/firefly/js/metaConvert/vo/VORequest.js
  src/firefly/js/util/WebUtil.js
  src/firefly/js/visualize/PlotAttribute.js
  src/firefly/js/visualize/ui/MouseReadout.jsx
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
  src/firefly/js/voAnalyzer/TableAnalysis.js
  src/firefly/js/voAnalyzer/VoDataLinkServDef.js
  src/firefly/js/voAnalyzer/vo-typedefs.jsdoc
Labels: enhancement

#1718 IRSA-6701: LVF image search minimized dialog incorrectly shows polygon search
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
Labels: bug, enhancement

#1719 FIREFLY-1609: Job completion notification framework
  buildScript/dependencies.gradle
  src/firefly/java/edu/caltech/ipac/firefly/api/Async.java
  src/firefly/java/edu/caltech/ipac/firefly/core/Util.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/EmailNotification.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/Job.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobCompletedHandler.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/ScriptAttributes.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/ServCmdJob.java
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/messaging/Message.java
  src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
  src/firefly/java/edu/caltech/ipac/firefly/server/cache/DistributedCache.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/BaseGator.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/DownloadScriptWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagedEmail.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryVOTABLE.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileDownload.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/DownloadScript.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/EMailUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
  src/firefly/js/Firefly.js
  src/firefly/js/core/background/BackgroundCntlr.js
  src/firefly/js/core/background/BackgroundMonitor.jsx
  src/firefly/js/core/background/BackgroundUtil.js
  src/firefly/js/core/core-typedefs.jsdoc
  src/firefly/js/data/ServerParams.js
  src/firefly/js/rpc/SearchServicesJson.js
  src/firefly/js/ui/DownloadDialog.jsx
  src/firefly/test/edu/caltech/ipac/firefly/core/UtilTest.java
  src/firefly/test/edu/caltech/ipac/firefly/messaging/MessengerTest.java
  src/firefly/test/edu/caltech/ipac/firefly/util/DownloadScriptTest.java
Labels: enhancement

#1720 FIREFLY-1673: Ensure userKey is consistent enforced
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
  src/firefly/java/edu/caltech/ipac/firefly/data/userdata/UserInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/java/edu/caltech/ipac/firefly/server/UserCache.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UserCatalogQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/MultiPartHandler.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/PlotServUtils.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/LocalFileRetriever.java
  src/firefly/java/edu/caltech/ipac/util/StringUtils.java
  src/firefly/java/edu/caltech/ipac/util/cache/CacheManager.java
Labels: enhancement

#1715 FIREFLY-1662: Support for Cutout Service Descriptor URL generation
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileDownload.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/DownloadScript.java
  src/firefly/js/metaConvert/vo/DatalinkFetch.js
  src/firefly/js/metaConvert/vo/ServDescProducts.js
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/ui/tap/Cutout.js
Labels: enhancement

#1722 FIREFLY-1672: fix left-shift negative number error in HEALpix UDFs
  src/firefly/java/edu/caltech/ipac/firefly/resources/healpix-java.sql
  src/firefly/test/edu/caltech/ipac/table/healpy/Dockerfile
  src/firefly/test/edu/caltech/ipac/table/healpy/README.md
  src/firefly/test/edu/caltech/ipac/table/healpy/compose.yaml
  src/firefly/test/edu/caltech/ipac/table/healpy/run_healpy.py
Labels: bug

#1724 IRSA-6706, IRSA-6571: Add Image on background of Results tab
  buildScript/webpack.config.js
  src/firefly/js/templates/fireflyviewer/LandingPage.jsx
  src/firefly/js/templates/hydra/HydraViewer.jsx
  src/firefly/js/util/Color.js
Labels: UI, multi-ticket

#1727 FIREFLY-1683: prevent excessive thread use
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DbMonitor.java
Labels: bug

#1726 FIREFLY-1378: Chart filter icon does not work on column mapped to a label
  src/firefly/html/test/tests-chart.html
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServiceInput.java
  src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
  src/firefly/js/charts/ui/FilterEditorWrapper.jsx
  src/firefly/js/charts/ui/PlotlyToolbar.jsx
  src/firefly/js/tables/ui/FilterEditor.jsx
  src/firefly/js/tables/ui/TablePanelOptions.jsx
Labels: bug

#1729 FIREFLY-1675: Chart area selection does not work for scatter plot with 'lines' mode
  src/firefly/js/charts/ui/PlotlyChartArea.jsx
Labels: Charts

#1731 FIREFLY-1670: Refactor download script creation and email notification
  src/firefly/java/edu/caltech/ipac/firefly/core/Util.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/EmailNotification.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/Job.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/DownloadScriptWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/FileGroup.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagedEmail.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/DownloadScript.java
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/core/background/BackgroundMonitor.jsx
  src/firefly/js/core/background/BackgroundUtil.js
  src/firefly/js/templates/fireflyviewer/LandingPage.jsx
  src/firefly/test/edu/caltech/ipac/firefly/util/DownloadScriptTest.java
Labels: Refactor

#1725 Firefly-1680: FITS image optimizations
  config/app.config
  src/firefly/java/edu/caltech/ipac/astro/net/HorizonsEphPairs.java
  src/firefly/java/edu/caltech/ipac/astro/net/TargetNetwork.java
  src/firefly/java/edu/caltech/ipac/firefly/server/rpc/ResolveServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/DirectStretchUtils.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/ImagePlotCreator.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
  src/firefly/java/edu/caltech/ipac/firefly/visualize/WebFitsData.java
  src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotResult.java
  src/firefly/java/edu/caltech/ipac/util/CollectionUtil.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/Histogram.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/ImageData.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/ImagePlot.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsRead.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadFactory.java
  src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
  src/firefly/js/metaConvert/ImageDataProductsUtil.js
  src/firefly/js/visualize/WebPlot.js
  src/firefly/js/visualize/rawData/RawDataOps.js
  src/firefly/js/visualize/saga/MouseReadoutWatch.js
  src/firefly/js/visualize/task/CreateTaskUtil.js
  src/firefly/js/visualize/ui/ColorBandPanel.jsx
  src/firefly/js/visualize/ui/extraction/ExtractionChart.jsx
  src/firefly/js/visualize/ui/extraction/ExtractionTable.jsx
  src/firefly/test/edu/caltech/ipac/firefly/server/rpc/ResolveNaifidNameTest.java
Labels: enhancement, Image

#1732 Firefly-1688, Firefly-1689: multi ticket
  docs/release-notes.md
  src/firefly/js/visualize/ImViewFilterDisplay.js
  src/firefly/js/visualize/iv/ExpandedTools.jsx
  src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
  src/firefly/js/visualize/ui/multiProduct/MPMessages.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
Labels: bug

#1734 FIREFLY-1653: Create a WavelengthInputField component to handle trailing units
  src/firefly/js/ui/WavelengthInputField.jsx
  src/firefly/js/ui/tap/WavelengthPanel.jsx
  src/firefly/js/util/Validate.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/VisUtil.js
Labels: enhancement, UI

#1733 Firefly-1482: implement bandwidth in readout
  src/firefly/js/visualize/MouseReadoutCntlr.js
  src/firefly/js/visualize/PlotViewUtil.js
  src/firefly/js/visualize/saga/MouseReadoutWatch.js
  src/firefly/js/visualize/ui/MouseReadPopoutAll.jsx
  src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
  src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
Labels: enhancement, Image
