Repository Caltech-IPAC/firefly, pull requests merged in 2025-04, with the labels that each got.

#1736 Firefly-1696: changes for url api to work with a routed app and EmbededPositionSearchPanel
  src/firefly/js/api/webApiCommands/DatalinkUICommands.js
  src/firefly/js/drawingLayers/DistanceTool.js
  src/firefly/js/templates/common/FireflyLayout.jsx
  src/firefly/js/templates/common/InitArgsCtx.jsx
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/visualize/ImViewFilterDisplay.js
  src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
  src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
Labels: bug, enhancement, multi-ticket

#1740 Firefly-1702: Experimental LSDB panel is enabled behind url api option
  src/firefly/html/firefly-dev.html
  src/firefly/js/Firefly.js
  src/firefly/js/api/WebApi.js
  src/firefly/js/api/webApiCommands/LsdbCommands.js
  src/firefly/js/api/webApiCommands/ViewerWebApiCommands.js
  src/firefly/js/ui/DropDownContainer.jsx
  src/firefly/js/visualize/ui/GatorProtocolRootPanel.jsx
  src/firefly/js/visualize/ui/GatorProtocolUtil.jsx
Labels: enhancement

#1739 IRSA-6747: Changes in the job-submission UI
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
  src/firefly/js/ui/tap/TimeRangePanel.jsx
  src/firefly/js/ui/tap/WavelengthPanel.jsx
  src/firefly/js/visualize/MouseReadoutCntlr.js
  src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
  src/firefly/js/visualize/ui/WorldPtFormat.jsx
Labels: enhancement, UI

#1741 Firefly-1701: DataProductViewer: add pdf, yaml, json and text files
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
  src/firefly/java/edu/caltech/ipac/firefly/server/SrvParam.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileDownload.java
  src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/URLFileRetriever.java
  src/firefly/java/edu/caltech/ipac/visualize/net/AnyUrlParams.java
  src/firefly/js/core/JsonUtils.js
  src/firefly/js/data/ServerParams.js
  src/firefly/js/metaConvert/AnalysisUtils.js
  src/firefly/js/metaConvert/DataProductsCntlr.js
  src/firefly/js/metaConvert/DataProductsType.js
  src/firefly/js/metaConvert/PartAnalyzer.js
  src/firefly/js/metaConvert/UploadAndAnalysis.js
  src/firefly/js/metaConvert/vo/DataLinkProcessor.js
  src/firefly/js/metaConvert/vo/DataLinkStandAloneConverter.js
  src/firefly/js/metaConvert/vo/DatalinkProducts.js
  src/firefly/js/metaConvert/vo/ObsCoreConverter.js
  src/firefly/js/rpc/CoreServices.js
  src/firefly/js/ui/PositionFieldDef.js
  src/firefly/js/visualize/ui/multiProduct/DPDropdown.jsx
  src/firefly/js/visualize/ui/multiProduct/MPMessages.jsx
  src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
  src/firefly/js/voAnalyzer/TableAnalysis.js
  src/firefly/js/voAnalyzer/VoDataLinkServDef.js
  src/firefly/js/voAnalyzer/vo-typedefs.jsdoc
Labels: enhancement

#1738 FIREFLY-1693: ObsCore improvements
  src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/ZipHandler.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/Firefly.js
  src/firefly/js/metaConvert/vo/DatalinkFetch.js
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/ui/DownloadDialog.jsx
Labels: enhancement

#1742 Firefly-1469: Update DCE to support rubin needs
  src/firefly/js/api/webApiCommands/LsdbCommands.js
  src/firefly/js/metaConvert/AnalysisUtils.js
  src/firefly/js/metaConvert/vo/ServDescProducts.js
  src/firefly/js/ui/Menu.jsx
  src/firefly/js/ui/TargetFeedback.jsx
  src/firefly/js/ui/dynamic/DLGenAnalyzeSearch.js
  src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
  src/firefly/js/ui/dynamic/DLuiServDescPanel.jsx
  src/firefly/js/ui/dynamic/DynComponents.jsx
  src/firefly/js/ui/dynamic/DynamicDef.js
  src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/ui/dynamic/ServiceDefTools.js
  src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
  src/firefly/js/ui/tap/ObsCore.jsx
  src/firefly/js/ui/tap/SiaUI.jsx
  src/firefly/js/ui/tap/SiaUtil.js
  src/firefly/js/ui/tap/WavelengthPanel.jsx
  src/firefly/js/visualize/HiPSUtil.js
  src/firefly/js/visualize/ImagePlotCntlr.js
  src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
Labels: enhancement

#1744 Firefly-1706, Firefly-1195: fixed two tickets
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
  src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysisReport.java
  src/firefly/java/edu/caltech/ipac/util/FormatUtil.java
  src/firefly/js/data/FileAnalysis.js
  src/firefly/js/metaConvert/AnalysisUtils.js
  src/firefly/js/metaConvert/UploadAndAnalysis.js
  src/firefly/js/ui/FileUpload.jsx
  src/firefly/js/ui/dynamic/DLGenAnalyzeSearch.js
  src/firefly/js/ui/tap/SpatialSearch.jsx
  src/firefly/js/visualize/SearchRefinementTool.jsx
  src/firefly/js/visualize/ui/ImageStatsPopup.jsx
  src/firefly/js/visualize/ui/VisualSearchUtils.js
Labels: bug, multi-ticket

#1746 FIREFLY-1715: Failed to recognize single column CSV file
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
  src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
  src/firefly/java/edu/caltech/ipac/util/FormatUtil.java
  src/firefly/test/edu/caltech/ipac/util/FormatUtilTest.java
Labels: bug

#1743 Firefly 1698 job merge history
  package.json
  src/firefly/java/edu/caltech/ipac/firefly/api/Async.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/EmailNotification.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/Job.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobCompletedHandler.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/JobUtil.java
  src/firefly/java/edu/caltech/ipac/firefly/core/background/ServCmdJob.java
  src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
  src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
  src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
  src/firefly/java/edu/caltech/ipac/firefly/server/cache/DistribMapCache.java
  src/firefly/java/edu/caltech/ipac/firefly/server/cache/DistributedCache.java
  src/firefly/java/edu/caltech/ipac/firefly/server/catquery/BaseGator.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/DownloadScriptWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
  src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryVOTABLE.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
  src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileDownload.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/DownloadScript.java
  src/firefly/js/core/LayoutCntlr.js
  src/firefly/js/core/background/BackgroundCntlr.js
  src/firefly/js/core/background/BackgroundUtil.js
  src/firefly/js/core/background/BgMaskPanel.jsx
  src/firefly/js/core/background/JobHistory.jsx
  src/firefly/js/core/background/JobInfo.jsx
  src/firefly/js/core/core-typedefs.jsdoc
  src/firefly/js/data/ServerParams.js
  src/firefly/js/rpc/SearchServicesJson.js
  src/firefly/js/tables/TableRequestUtil.js
  src/firefly/js/tables/TableUtil.js
  src/firefly/js/tables/TablesCntlr.js
  src/firefly/js/tables/ui/TableInfo.jsx
  src/firefly/js/tables/ui/TableRenderer.js
  src/firefly/js/templates/fireflyviewer/LandingPage.jsx
  src/firefly/js/ui/tap/TapUtil.js
  src/firefly/test/edu/caltech/ipac/firefly/core/background/JobUtilTest.java
  yarn.lock
Labels: enhancement

#1747 Firefly-1718: Better handle data product catalog that connect to images
  src/firefly/js/drawingLayers/CatalogUI.jsx
  src/firefly/js/drawingLayers/hpx/HpxCatalog.js
  src/firefly/js/metaConvert/TableDataProductUtils.js
  src/firefly/js/visualize/MultiViewCntlr.js
  src/firefly/js/visualize/PlotAttribute.js
  src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbar.jsx
  src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
  src/firefly/js/visualize/ui/MultiImageViewer.jsx
  src/firefly/js/visualize/ui/MultiImageViewerView.jsx
Labels: enhancement

#1748 Firefly-1676: improve the titling and position for the 'Show table with all data products' option
  src/firefly/js/data/MetaConst.js
  src/firefly/js/drawingLayers/CatalogUI.jsx
  src/firefly/js/ui/CutoutSizeDialog.jsx
  src/firefly/js/ui/DefaultSearchActions.js
  src/firefly/js/ui/tap/DataServicesOptions.js
Labels: enhancement, multi-ticket

#1750 Firefly-1725: improve center on selected table row so the data products images are never scrolled off screen
  src/firefly/js/drawingLayers/hpx/HpxCatalog.js
  src/firefly/js/metaConvert/ImageDataProductsUtil.js
  src/firefly/js/metaConvert/vo/ObsCoreConverter.js
  src/firefly/js/visualize/PlotAttribute.js
  src/firefly/js/visualize/saga/ActiveRowToImageWatcher.js
  src/firefly/js/visualize/ui/ImageCenterDropDown.jsx
Labels: bug

#1745 FIREFLY-1704: Download Script Enhancement
  src/firefly/java/edu/caltech/ipac/firefly/core/background/EmailNotification.java
  src/firefly/java/edu/caltech/ipac/firefly/data/DownloadRequest.java
  src/firefly/java/edu/caltech/ipac/firefly/data/FileInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/data/HttpResultInfo.java
  src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/ZipHandler.java
  src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
  src/firefly/java/edu/caltech/ipac/firefly/server/util/DownloadScript.java
  src/firefly/java/edu/caltech/ipac/util/FileUtil.java
  src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
  src/firefly/js/templates/common/ttFeatureWatchers.js
  src/firefly/js/templates/lightcurve/LcResult.jsx
  src/firefly/js/templates/router/RouteHelper.jsx
  src/firefly/js/ui/DownloadDialog.jsx
  src/firefly/js/ui/WorkspaceSelectPane.jsx
Labels: enhancement

#1751 FIREFLY-1720: Generalize UploadTableSelector for handling shape fit columns in Spectrophotometry tool
  src/firefly/js/charts/ui/ColumnOrExpression.jsx
  src/firefly/js/ui/UploadTableChooser.js
  src/firefly/js/ui/UploadTableSelector.jsx
  src/firefly/js/ui/UploadTableSelectorPosCol.jsx
  src/firefly/js/ui/UploadTableSelectorSingleCol.jsx
  src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
  src/firefly/js/ui/tap/ObjectIDSearch.jsx
  src/firefly/js/ui/tap/SpatialSearch.jsx
Labels: bug, enhancement, multi-ticket
